// Page strings: statistics, feed, closed, keys, new session, commands, jump, agents. Keys start with "stats / feed / closed / keys / new / cmd / jump / agent."; en and ru have the same key set.
// Plurals are arrays: ru [one, few, many], en [one, other]; {n} is the number.
// Statistics numbers: in ru a non-breaking space (U+00A0) separates the number and the unit.
(function (root) {
  const I = root.I18N;
  I.add({
    en: {
      // --- Statistics: logic (stats-logic.js) ---
      "stats.period.today": "Today",
      "stats.period.today.prev": "vs. yesterday at this time",
      "stats.period.7d": "7 days",
      "stats.period.7d.prev": "vs. the previous 7 days",
      "stats.period.30d": "30 days",
      "stats.period.30d.prev": "vs. the previous 30 days",
      "stats.period.90d": "90 days",
      "stats.period.90d.prev": "vs. the previous 90 days",
      "stats.period.all": "All time",
      "stats.metric.cost": "Cost",
      "stats.metric.tokens": "Tokens",
      "stats.metric.time": "Time",
      "stats.num.billion": "{n}B",
      "stats.num.million": "{n}M",
      "stats.num.thousand": "{n}k",
      "stats.num.hours": "{h} h",
      "stats.num.minutes": "{m} min",
      "stats.num.hoursMinutes": "{h} h {m} min",
      // --- Statistics: view (stats.js) ---
      "stats.weekdays": "Mon Tue Wed Thu Fri Sat Sun",
      "stats.auto": "background runs",
      "stats.auto.hint": "Sessions without a human: nightly, hooks, claude -p, codex exec. They use the same subscription",
      "stats.updated": "updated {time}",
      "stats.loading": "calculating…",
      "stats.error": "error: {msg}",
      "stats.tok.input": "input",
      "stats.tok.cache": "cache read",
      "stats.tok.output": "output",
      "stats.unpriced": " · no price: {list}",
      "stats.tile.sessions": "Sessions",
      "stats.tile.sessions.sub": "prompts {prompts} · replies {answers}",
      "stats.tile.sessions.hint": "Sessions with work in the period — including ones started earlier",
      "stats.tile.tokens": "Tokens",
      "stats.tile.tokens.hint": "Input — new tokens and cache writes; cache read — context read again",
      "stats.tile.time": "Active time",
      "stats.tile.time.sub": "sessions combined {time}",
      "stats.tile.time.hint": "When at least one session was running. Pauses longer than 15 minutes don't count; "
        + "parallel sessions add up in “combined”",
      "stats.tile.cost": "API cost",
      "stats.tile.cost.sub": "estimate at API prices, not the subscription",
      "stats.tile.cost.hint": "Each reply at its own model's API prices (Anthropic for Claude Code, OpenAI for Codex), "
        + "including cache writes and reads. Codex prices can be fixed in config.json, openai_prices",
      "stats.tile.cache": "Cache hit rate",
      "stats.tile.cache.sub": "share of input read from cache",
      "stats.tile.cache.hint": "Cache read ÷ (input + cache write + cache read). The higher, the cheaper long sessions are",
      "stats.chart.hours": "By hour",
      "stats.chart.days": "By day",
      "stats.chart.empty": "nothing in this period",
      "stats.chart.pointHint": "{when}: {cost} · {tokens} tokens · {time} · sessions {sessions}",
      "stats.noData": "no data",
      "stats.row.hint": "{name}: {cost} · {tokens} tokens · {time}",
      "stats.row.prompts": " · prompts {n}",
      "stats.rhythm": "Rhythm · active time by hour of the week",
      "stats.panel.domains": "Domains",
      "stats.panel.models": "Models",
      "stats.panel.topics": "Topics",
      "stats.panel.projects": "Projects",
      "stats.panel.sessions": "Sessions",
      "stats.panel.tools": "Tools · calls",
      "stats.panel.skills": "Skills and commands · calls",
      "stats.panel.agents": "Subagents · runs",
      "stats.panel.byAgent": "Agents",
      // --- Agent filter and badge (agent-filter.js) ---
      "agent.filter": "Agent",
      "agent.claude": "Claude Code",
      "agent.codex": "Codex",
      "agent.claudeShort": "Claude",
      "agent.codexShort": "Codex",
      "agent.badgeHint": "Agent: {agent}",
      "agent.lastOne": "At least one agent stays selected",

      // --- Session feed (active-feed.js, active-feed-views.js) ---
      "feed.views.hint": "Turns — prompts and replies; steps — every call in order; files — what the session edited",
      "feed.button": "feed",
      "feed.button.hint": "The whole session: your prompts, what the agent did, its replies. Latest first; scroll up for earlier turns",
      "feed.loadEarlier": "Earlier turns",
      "feed.loadingEarlier": "loading earlier turns…",
      "feed.start": "Start of the session",
      "feed.button.label": "Session feed",
      "feed.loading": "loading…",
      "feed.error": "error: {msg}",
      "feed.noPrompts": "No prompts from you in this session yet.",
      "feed.you": "You · {time}",
      "feed.images": ["+ {n} image", "+ {n} images"],
      "feed.interrupted": "interrupted",
      "feed.replyCut": "… the start of the reply is above",
      "feed.noReply": "No reply yet",
      "feed.view.turns": "Turns",
      "feed.view.steps": "Steps",
      "feed.view.files": "Files",
      "feed.filter.all": "all",
      "feed.filter.error": "errors",
      "feed.filter.bash": "commands",
      "feed.filter.edit": "edits",
      "feed.filter.agent": "agents",
      "feed.step.bash": "command",
      "feed.step.edit": "edit",
      "feed.step.read": "read",
      "feed.step.search": "search",
      "feed.step.agent": "agent",
      "feed.step.web": "web",
      "feed.step.skill": "skill",
      "feed.step.task": "tasks",
      "feed.step.text": "writing",
      "feed.step.other": "call",
      "feed.running": "running {time}",
      "feed.earlier": "… {n} more steps earlier",
      "feed.noSteps": "no steps",
      "feed.noMatchingSteps": "no such steps",
      "feed.replied": "{agent} replied · {time}",
      "feed.noMatchInTurns": "No such steps in the {n} loaded turns.",
      "feed.file.written": "written {n}",
      "feed.file.edits": "edits {n}",
      "feed.file.reads": "reads {n}",
      "feed.files.none": "The session hasn't read or edited any files yet.",
      "feed.files.changed": "Changed · {n}",
      "feed.files.changed.hint": "From Edit, Write, MultiEdit, NotebookEdit calls — for the whole session, including subagents. "
        + "Edits made with Bash commands (sed, scripts) are not included",
      "feed.files.noEdits": "no edits via tools",
      "feed.files.readOnly": "Read only · {n}",

      // --- Recently closed (active-closed.js) ---
      "closed.opening": "opening…",
      "closed.failed": "failed: {msg}",
      "closed.closedAgo": "closed {ago}",
      "closed.lastMessage": "last message {time}",
      "closed.folder": ", folder {cwd}",
      "closed.continue": "Continue",
      "closed.continue.hint": "Continue in a terminal tab — right where it left off",
      "closed.inSearch": "In search",
      "closed.inSearch.hint": "Session card: what was done, handoff, fork",
      "closed.title": "Recently closed",
      "closed.title.hint": "Sessions with work in the last 8 hours whose process has already exited",

      // --- Keys (active-keys.js) ---
      "keys.help.arrows": "↑ ↓ ← →  or  j k",
      "keys.help.select": "select a card",
      "keys.help.answer": "reply field",
      "keys.help.go": "“Go” to the tab",
      "keys.help.feed": "session feed on the right",
      "keys.help.pinHide": "pin / hide until a new message",
      "keys.help.esc": "clear selection / leave the field",
      "keys.help.jump": "go to a session by title (from the field and from other sections too)",
      "keys.title": "Keys",
      "keys.intro": "They work when the cursor isn't in an input field. Clicking a card also selects it; "
        + "in compact view Enter switches to the detailed one.",

      // --- New session (active-new.js) ---
      "newsess.button": "+ Session",
      "newsess.button.hint": "Start Claude Code or Codex in the chosen folder with a first prompt",
      "newsess.dirsFailed": "couldn't get folders: {msg}",
      "newsess.dirPlaceholder": "~/Code/project, a full path or a vault name — type to search",
      "newsess.quick": "Quick picks",
      "newsess.home": "Home ~",
      "newsess.vaultRoot": "Vault: {name}",
      "newsess.sessions": ["{n} session", "{n} sessions"],
      "newsess.noFolder": "Type a folder or pick one from the list.",
      "newsess.preparing": "preparing…",
      "newsess.notStarted": "not started: {msg}",
      "newsess.outside": "Outside Obsidian: run the command in a terminal.",

      // --- Commands (active-commands.js) ---
      "cmd.model.default": "default",
      "cmd.output": "{cmd} output · {ago}",
      "cmd.closePanel": "Close panel",
      "cmd.closePanel.hint": "Esc in the tab: the command's panel is open and waiting",
      "cmd.dismiss.hint": "Remove the output from the card",
      "cmd.noOutput": "command done, no output on screen",
      "cmd.effort": "effort:",
      "cmd.model": "model:",
      "cmd.choice.hint": "{cmd} {value} — Claude Code will remember this for new sessions too",

      // --- Jump ⌘K (jump.js) ---
      "jump.label": "Go to session",
      "jump.placeholder": "Go to session: title, topic, project…",
      "jump.hint": "↑ ↓ — select · Enter — go · Esc — close",
      "jump.empty": "nothing found",

      // --- Active logic (logic.js) ---
      "logic.period.hour": "in the last hour",
      "logic.period.today": "today, over an hour ago",
      "logic.period.yesterday": "yesterday",
      "logic.period.week": "2–7 days ago",
      "logic.period.older": "earlier",
      "logic.bg.shell": "background command",
      "logic.bg.shells": "background commands: {n}",
      "logic.bg.agents": ["{n} agent", "{n} agents"],
      "logic.bg.wake": "wakes at {time}",
      "logic.bg.cron": "scheduled",
      "logic.context": "context {pct}%",
      "logic.context.hint": "{used}k of {window}k tokens on the last request",
      "logic.context.soon": " — auto-compaction soon",
      "logic.limits": "limits: {parts}",
      "logic.limits.until": " until {when}",
      "logic.limits.reached": ", used up",
      "logic.cost.on": " as of {day}",
      "logic.turns": ["{n} turn", "{n} turns"],
      "logic.term.notObsidian": "the atlas isn't open in Obsidian",
      "logic.term.noReply": "the AI Session Atlas plugin isn't responding — turn it off and on in settings",
      "logic.term.checking": "checking",
      "logic.dur.sec": "{n} s",
      "logic.dur.min": "{n} min",
      "logic.dur.hm": "{h} h {m} min",
    },
    ru: {
      // --- Statistics: logic (stats-logic.js) ---
      "stats.period.today": "Сегодня",
      "stats.period.today.prev": "ко вчера на это время",
      "stats.period.7d": "7 дней",
      "stats.period.7d.prev": "к прошлым 7 дням",
      "stats.period.30d": "30 дней",
      "stats.period.30d.prev": "к прошлым 30 дням",
      "stats.period.90d": "90 дней",
      "stats.period.90d.prev": "к прошлым 90 дням",
      "stats.period.all": "Всё время",
      "stats.metric.cost": "Цена",
      "stats.metric.tokens": "Токены",
      "stats.metric.time": "Время",
      "stats.num.billion": "{n} млрд",
      "stats.num.million": "{n} млн",
      "stats.num.thousand": "{n} тыс",
      "stats.num.hours": "{h} ч",
      "stats.num.minutes": "{m} мин",
      "stats.num.hoursMinutes": "{h} ч {m} мин",
      // --- Statistics: view (stats.js) ---
      "stats.weekdays": "Пн Вт Ср Чт Пт Сб Вс",
      "stats.auto": "фоновые прогоны",
      "stats.auto.hint": "Сессии без человека: nightly, хуки, claude -p, codex exec. Тратят ту же подписку",
      "stats.updated": "обновлено {time}",
      "stats.loading": "считаю…",
      "stats.error": "ошибка: {msg}",
      "stats.tok.input": "вход",
      "stats.tok.cache": "из кэша",
      "stats.tok.output": "выход",
      "stats.unpriced": " · без цены: {list}",
      "stats.tile.sessions": "Сессии",
      "stats.tile.sessions.sub": "запросов {prompts} · ответов {answers}",
      "stats.tile.sessions.hint": "Сессии, в которых была работа за период — и начатые раньше",
      "stats.tile.tokens": "Токены",
      "stats.tile.tokens.hint": "Вход — новые токены и запись в кэш; из кэша — повторно прочитанный контекст",
      "stats.tile.time": "Время в работе",
      "stats.tile.time.sub": "сессии суммарно {time}",
      "stats.tile.time.hint": "Когда шла хотя бы одна сессия. Паузы длиннее 15 минут не считаются; "
        + "параллельные сессии в «суммарно» складываются",
      "stats.tile.cost": "Цена по API",
      "stats.tile.cost.sub": "оценка по ценам API, не подписка",
      "stats.tile.cost.hint": "Каждый ответ — по ценам API своей модели (Anthropic у Claude Code, OpenAI у Codex), "
        + "с записью и чтением кэша. Цены Codex правятся в config.json, openai_prices",
      "stats.tile.cache": "Попадание в кэш",
      "stats.tile.cache.sub": "доля входа, прочитанная из кэша",
      "stats.tile.cache.hint": "Из кэша ÷ (вход + запись в кэш + из кэша). Чем выше, тем дешевле длинные сессии",
      "stats.chart.hours": "По часам",
      "stats.chart.days": "По дням",
      "stats.chart.empty": "за период ничего нет",
      "stats.chart.pointHint": "{when}: {cost} · {tokens} токенов · {time} · сессий {sessions}",
      "stats.noData": "нет данных",
      "stats.row.hint": "{name}: {cost} · {tokens} токенов · {time}",
      "stats.row.prompts": " · запросов {n}",
      "stats.rhythm": "Ритм · время в работе по часам недели",
      "stats.panel.domains": "Домены",
      "stats.panel.models": "Модели",
      "stats.panel.topics": "Темы",
      "stats.panel.projects": "Проекты",
      "stats.panel.sessions": "Сессии",
      "stats.panel.tools": "Инструменты · вызовов",
      "stats.panel.skills": "Скиллы и команды · вызовов",
      "stats.panel.agents": "Сабагенты · запусков",
      "stats.panel.byAgent": "Агенты",
      // --- Agent filter and badge (agent-filter.js) ---
      "agent.filter": "Агент",
      "agent.claude": "Claude Code",
      "agent.codex": "Codex",
      "agent.claudeShort": "Claude",
      "agent.codexShort": "Codex",
      "agent.badgeHint": "Агент: {agent}",
      "agent.lastOne": "Хотя бы один агент остаётся выбранным",

      // --- Session feed (active-feed.js, active-feed-views.js) ---
      "feed.views.hint": "Ходы — запросы и ответы; шаги — каждый вызов по порядку; файлы — что сессия правила",
      "feed.button": "лента",
      "feed.button.hint": "Вся сессия: твои запросы, что делал агент, его ответы. Сначала конец, раньше — листая вверх",
      "feed.loadEarlier": "Ходы раньше",
      "feed.loadingEarlier": "загружаю ходы раньше…",
      "feed.start": "Начало сессии",
      "feed.button.label": "Лента сессии",
      "feed.loading": "загружаю…",
      "feed.error": "ошибка: {msg}",
      "feed.noPrompts": "В сессии ещё нет твоих запросов.",
      "feed.you": "Ты · {time}",
      "feed.images": ["+ {n} картинка", "+ {n} картинки", "+ {n} картинок"],
      "feed.interrupted": "прервано",
      "feed.replyCut": "… начало ответа выше",
      "feed.noReply": "Ответа ещё нет",
      "feed.view.turns": "Ходы",
      "feed.view.steps": "Шаги",
      "feed.view.files": "Файлы",
      "feed.filter.all": "все",
      "feed.filter.error": "ошибки",
      "feed.filter.bash": "команды",
      "feed.filter.edit": "правки",
      "feed.filter.agent": "агенты",
      "feed.step.bash": "команда",
      "feed.step.edit": "правка",
      "feed.step.read": "чтение",
      "feed.step.search": "поиск",
      "feed.step.agent": "агент",
      "feed.step.web": "веб",
      "feed.step.skill": "скилл",
      "feed.step.task": "задачи",
      "feed.step.text": "пишет",
      "feed.step.other": "вызов",
      "feed.running": "идёт {time}",
      "feed.earlier": "… ещё {n} шагов раньше",
      "feed.noSteps": "шагов не было",
      "feed.noMatchingSteps": "таких шагов нет",
      "feed.replied": "{agent} ответил · {time}",
      "feed.noMatchInTurns": "В загруженных ходах ({n}) таких шагов нет.",
      "feed.file.written": "записан {n}",
      "feed.file.edits": "правок {n}",
      "feed.file.reads": "чтений {n}",
      "feed.files.none": "Сессия ещё не читала и не правила файлы.",
      "feed.files.changed": "Изменены · {n}",
      "feed.files.changed.hint": "По вызовам Edit, Write, MultiEdit, NotebookEdit — за всю сессию, с сабагентами. "
        + "Правки командами Bash (sed, скрипты) сюда не попадают",
      "feed.files.noEdits": "правок инструментами не было",
      "feed.files.readOnly": "Только прочитаны · {n}",

      // --- Recently closed (active-closed.js) ---
      "closed.opening": "открываю…",
      "closed.failed": "не вышло: {msg}",
      "closed.closedAgo": "закрыта {ago}",
      "closed.lastMessage": "последнее сообщение {time}",
      "closed.folder": ", папка {cwd}",
      "closed.continue": "Продолжить",
      "closed.continue.hint": "Продолжить во вкладке терминала — с того же места",
      "closed.inSearch": "В поиске",
      "closed.inSearch.hint": "Карточка сессии: что сделано, хендофф, форк",
      "closed.title": "Недавно закрытые",
      "closed.title.hint": "Сессии с работой за последние 8 часов, чей процесс уже завершён",

      // --- Keys (active-keys.js) ---
      "keys.help.arrows": "↑ ↓ ← →  или  j k",
      "keys.help.select": "выбрать карточку",
      "keys.help.answer": "поле ответа",
      "keys.help.go": "«Перейти» во вкладку",
      "keys.help.feed": "лента сессии справа",
      "keys.help.pinHide": "закрепить / скрыть до нового сообщения",
      "keys.help.esc": "снять выбор / выйти из поля",
      "keys.help.jump": "перейти к сессии по названию (и из поля, и с других разделов)",
      "keys.title": "Клавиши",
      "keys.intro": "Работают, когда курсор не в поле ввода. Клик по карточке тоже выбирает её; "
        + "Enter в компактном виде переключает в подробный.",

      // --- New session (active-new.js) ---
      "newsess.button": "+ Сессия",
      "newsess.button.hint": "Запустить Claude Code или Codex в выбранной папке с первым запросом",
      "newsess.dirsFailed": "не удалось получить папки: {msg}",
      "newsess.dirPlaceholder": "~/Code/проект, полный путь или имя vault — печатай для поиска",
      "newsess.quick": "Быстрый выбор",
      "newsess.home": "Домашняя ~",
      "newsess.vaultRoot": "Vault: {name}",
      "newsess.sessions": ["{n} сессия", "{n} сессии", "{n} сессий"],
      "newsess.noFolder": "Впиши папку или выбери из списка.",
      "newsess.preparing": "готовлю…",
      "newsess.notStarted": "не запущено: {msg}",
      "newsess.outside": "Вне Obsidian: выполни команду в терминале.",

      // --- Commands (active-commands.js) ---
      "cmd.model.default": "по умолчанию",
      "cmd.output": "Ответ {cmd} · {ago}",
      "cmd.closePanel": "Закрыть панель",
      "cmd.closePanel.hint": "Esc во вкладке: панель команды открыта и ждёт",
      "cmd.dismiss.hint": "Убрать ответ из карточки",
      "cmd.noOutput": "команда выполнена, на экране ответа нет",
      "cmd.effort": "усилие:",
      "cmd.model": "модель:",
      "cmd.choice.hint": "{cmd} {value} — Claude Code запомнит это и для новых сессий",

      // --- Jump ⌘K (jump.js) ---
      "jump.label": "Перейти к сессии",
      "jump.placeholder": "Перейти к сессии: название, тема, проект…",
      "jump.hint": "↑ ↓ — выбрать · Enter — перейти · Esc — закрыть",
      "jump.empty": "ничего не нашлось",

      // --- Active logic (logic.js) ---
      "logic.period.hour": "за последний час",
      "logic.period.today": "сегодня, раньше часа",
      "logic.period.yesterday": "вчера",
      "logic.period.week": "2–7 дней назад",
      "logic.period.older": "раньше",
      "logic.bg.shell": "команда в фоне",
      "logic.bg.shells": "команд в фоне: {n}",
      "logic.bg.agents": ["{n} агент", "{n} агента", "{n} агентов"],
      "logic.bg.wake": "проснётся в {time}",
      "logic.bg.cron": "по расписанию",
      "logic.context": "контекст {pct}%",
      "logic.context.hint": "{used}k из {window}k токенов на последнем запросе",
      "logic.context.soon": " — скоро автоматическая компактация",
      "logic.limits": "лимиты: {parts}",
      "logic.limits.until": " до {when}",
      "logic.limits.reached": ", исчерпан",
      "logic.cost.on": " на {day}",
      "logic.turns": ["{n} ход", "{n} хода", "{n} ходов"],
      "logic.term.notObsidian": "каталог открыт не в Obsidian",
      "logic.term.noReply": "плагин AI Session Atlas не отвечает — выключи и включи его в настройках",
      "logic.term.checking": "проверяется",
      "logic.dur.sec": "{n} с",
      "logic.dur.min": "{n} мин",
      "logic.dur.hm": "{h} ч {m} мин",
    },
  });
})(window);
