// Строки страницы: вкладка «Активные»: карточки, диалоги, план, фильтры, восстановление. Ключи — с префиксом «active.»; en и ru — одинаковый набор ключей.
// Множественное число — массивом: ru [one, few, many], en [one, other]; {n} — само число.
(function (root) {
  const I = typeof module !== "undefined" && module.exports ? require("./i18n.js") : root.I18N;
  I.add({
    en: {
      // общее
      "active.sending": "sending…",
      "active.noHostReply": "Obsidian did not respond — check the tab",
      "active.error": "error: {msg}",
      "active.errorWord": "error",
      "active.notSent": "not sent: {reason}",
      "active.quoted": "“{text}”",
      "active.go": "Go",
      "active.close": "Close",
      // статусы
      "active.status.busy": "working",
      "active.status.busyHint": "The agent is working right now",
      "active.status.background": "working in background",
      "active.status.backgroundShort": "background",
      "active.status.backgroundHint": "The turn is over, but background work will wake the session, not you",
      "active.status.waiting": "needs your decision",
      "active.status.waitingHint": "A question or permission request is open — answer with a button in the card or in the tab",
      "active.status.idle": "waiting",
      "active.status.idleHint": "The agent is done and waiting for your message",
      // карточка
      "active.openInSearch": "Open the card in search",
      "active.notIndexed": "Session is not indexed yet",
      "active.noDescription": "The description appears after classification.",
      "active.tasksPill": "tasks {count}",
      "active.tasksNow": "Now: {task}",
      "active.goalHint": "Active /goal: {goal}",
      "active.sensitive": "sensitive",
      "active.when": "started {start} · message {ago}",
      "active.whenHint": "started {start}, last message {last}",
      "active.turnsNone": "turns —",
      "active.turns": ["{n} turn", "{n} turns"],
      "active.costRecorded": "Claude Code recorded ${cost}{at} — it writes the total only on exit. ",
      "active.costRecordedAt": " at {date}",
      "active.costNotRecorded": "Claude Code has not recorded a total yet — it writes one only on exit. ",
      "active.costNow": "Now ≈ ${cost}: estimated from reply tokens.",
      "active.costPartial": " Some replies come from models with unknown prices — the estimate is too low.",
      "active.goHint": "Go to this session's terminal tab",
      "active.closeHint": "Close the tab — the session ends (asks for confirmation)",
      "active.notInTab": "The session is not running in an Obsidian tab",
      "active.notInTabApp": "The session is not running in an Obsidian tab — it runs in {app}",
      "active.buttonsInObsidian": "Buttons work inside Obsidian",
      "active.tasksAllDone": "all tasks done",
      "active.tasksNotStarted": "not started yet",
      // доставка и ответ
      "active.delivery.sending": "sent, waiting for it in the session…",
      "active.delivery.queued": "queued — Claude will read it after the current step",
      "active.delivery.lost": "not visible in the session — check the tab",
      "active.you": "You, {ago} · {state}",
      "active.youWas": "You, {ago}",
      "active.promptCut": "… the prompt continues in the feed",
      "active.interrupted": "interrupted — Claude did not reply",
      "active.awaitingClaude": "waiting for Claude's reply",
      "active.lostHint": "Within 15 seconds the message appeared neither in the transcript nor in the queue. The tab may not have accepted the input, or a dialog intercepted it.",
      "active.images": ["+ {n} image", "+ {n} images"],
      "active.nowMd": "**now:** {text}",
      "active.lastNote": "Agent's latest note, {ago}",
      "active.collapse": "collapse",
      "active.showAll": "show all ({n} chars)",
      "active.queuedOne": "queued “{text}”",
      "active.queuedMany": "queued {n} msgs — “{text}”",
      "active.replyStartAbove": "… the start of the reply is above",
      "active.noTextReply": "No text reply yet.",
      // поле ответа и картинки
      "active.maxImages": "no more than {n} images",
      "active.imageFailed": "image not attached: {msg}",
      "active.imageAlt": "image {n}",
      "active.removeImage": "Remove image",
      "active.replyAria": "Reply to the session",
      "active.sendHint": "Send (Enter)",
      "active.send": "Send",
      "active.attachHint": "Attach an image (or paste with ⌘V / drop it into the field)",
      "active.attach": "Attach image",
      "active.blockedNoHost": "sending works when the catalog is open inside Obsidian",
      "active.blockedNoTab": "the session is not running in an Obsidian tab",
      "active.blockedDialog": "a dialog is open — answer with a button above (Enter there would pick an option)",
      "active.placeholderBusy": "The agent is working — the message will be queued…",
      "active.placeholderBackground": "The session is waiting on background work — write now, the agent reads it right away…",
      "active.placeholder": "Reply… Enter to send, Shift+Enter for a new line, ⌘V for an image",
      // сводка и секции
      "active.none": "none",
      "active.shown": "shown {n}",
      "active.shownHint": "{shown} of {total} match the filters",
      "active.hidden": "hidden {n}",
      "active.hiddenHint": "Hidden cards come back on their own with the next message. Click to show all now",
      "active.updated": "updated {time}",
      "active.limit.fiveHour": "5h",
      "active.limit.week": "wk",
      "active.limitsStale": " (stale)",
      "active.limitsNone": "limits —",
      "active.limitsHint": "Subscription limits: {limits} — from the Claude Code status line while any session is open",
      "active.limitsSetup": "Claude Code reports subscription limits only to the status line. Connect it: in ~/.claude/settings.json add {snippet}",
      "active.terminal": "terminal ",
      "active.terminalHint": "Terminal link: {state}{reason}. “Go”, “Close” and sending go through the Obsidian plugin to the terminal tab",
      "active.terminalChecking": "checking",
      "active.terminalYes": "yes",
      "active.terminalNo": "no",
      "active.keysHint": "Active tab shortcuts",
      "active.noSessions": "No Claude Code session is running right now.",
      "active.allHidden": "All matching sessions are hidden — “hidden” in the line above brings them back.",
      "active.noMatches": "No session matches the selected filters.",
      "active.sectionWaiting": "Waiting for you",
      "active.sectionWorking": "Working",
      // диалог и «Стоп»
      "active.answerSent": "answer sent",
      "active.permissionInTab": "Permission request — answer it in the terminal tab",
      "active.questionInTab": "Question — answer it in the terminal tab",
      "active.readingDialog": "reading the dialog…",
      "active.dialogNotRead": "dialog not read — answer in the tab",
      "active.panelOpen": "Panel open: {title}",
      "active.closePanel": "Close panel",
      "active.permission": "Permission: {title}",
      "active.dialogTabOnly": "this dialog can only be answered in the tab",
      "active.pressesKey": "presses {n} in the session tab",
      "active.stop": "Stop",
      "active.stopNeedsTab": "Works when the session is open in an Obsidian tab",
      "active.stopDialogHint": "Close the dialog without answering — like Esc in the tab",
      "active.stopStepHint": "Interrupt the current step — like Esc in the tab",
      "active.stopDialogTitle": "Close the dialog without answering?",
      "active.stopSessionTitle": "Interrupt the session?",
      "active.stopDialogBody": "“{title}”: the dialog closes as if Esc were pressed in the tab; the command will not run.",
      "active.stopSessionBody": "“{title}”: the agent stops the current step, as with Esc in the tab. The session stays open — you can write what to do next.",
      "active.nowText": "now: {text}",
      "active.closeDialog": "Close dialog",
      "active.interrupt": "Interrupt",
      "active.stopping": "stopping…",
      "active.stopped": "stopped",
      "active.notStopped": "not stopped: {reason}",
      // план
      "active.planAutoFull": "Run — edits without asking",
      "active.planAutoShort": "Run",
      "active.planManualFull": "Run — approve each edit",
      "active.planManualShort": "Run, confirm",
      "active.sendingFeedback": "sending feedback…",
      "active.planFeedbackPlaceholder": "What should change in the plan? Enter to send",
      "active.sendFeedback": "Send feedback",
      "active.sendFeedbackHint": "The agent gets the text and rewrites the plan — it will not start executing",
      "active.planReady": "Plan ready — execute?",
      "active.planNotRead": "plan not read: {error}",
      "active.readingPlan": "reading the plan…",
      "active.planOptionHint": "“{text}” — presses {n} in the session tab",
      "active.planOptionHintKnown": "{label}: “{text}” — presses {n} in the session tab",
      "active.revise": "Revise…",
      "active.reviseHint": "Write what to change: the plan goes back to the agent for revision",
      "active.plan": "Plan",
      "active.readPlanHint": "Read the full plan",
      // восстановление и перенос
      "active.restoreMore": " and {n} more",
      "active.restoreOne": "After Obsidian restarted, a session open in a tab was closed: {names}.",
      "active.restoreMany": ["After Obsidian restarted, {n} session open in tabs was closed: {names}.",
                             "After Obsidian restarted, {n} sessions open in tabs were closed: {names}."],
      "active.restore": "Restore",
      "active.restoreAll": "Restore all",
      "active.restoreHint": "Each one opens in its own terminal tab via claude --resume",
      "active.restoreSkip": "dismiss",
      "active.opening": "opening…",
      "active.restoreFailed": "failed: {names} — the session has no working folder, open it from search",
      "active.restoreDone": "tabs opened: {n}",
      "active.move": "Move",
      "active.otherTerminal": "another terminal",
      "active.moveHint": "The session runs in {app}: end it there and open it in a tab here",
      "active.moveTitle": "Move to Obsidian?",
      "active.moveBody": "“{title}” runs in {app}. Atlas will end it there (like Ctrl+C) and open it here in a tab via claude --resume. The terminal window there stays — you can close it.",
      "active.moveBodyBusy": "“{title}” runs in {app}. Atlas will end it there (like Ctrl+C; the current turn will be interrupted) and open it here in a tab via claude --resume. The terminal window there stays — you can close it.",
      "active.moveEnding": "ending the session there…",
      "active.moveFailed": "failed: {msg}",
      "active.moveNoFolder": "The session ended, but it has no working folder — open it from search.",
      // фильтры и сетка
      "active.filter.domain": "Domain",
      "active.filter.project": "Project",
      "active.filter.topic": "Topic",
      "active.filter.period": "Period",
      "active.filterAll": "{label}: all",
      "active.noValues": "no values",
      "active.auto": "auto",
      "active.layoutHint": "Cards per screen: columns × rows",
      "active.layoutAria": "Card layout",
      "active.cols": ["{n} column", "{n} columns"],
      "active.rows": ["{n} row", "{n} rows"],
      "active.hoverAndClick": "hover and click",
      "active.autoFullHint": "Fits the screen width, two rows",
      "active.autoCompactHint": "4 columns × 5 rows",
      "active.find": "find…",
      "active.allVisible": "all visible",
      "active.reset": "reset",
      "active.viewAria": "Card view",
      "active.modeCompact": "compact",
      "active.modeCompactHint": "Compact: many small cards",
      "active.modeFull": "detailed",
      "active.modeFullHint": "Detailed: Claude's reply and a reply field in the card",
      // закрепить и скрыть
      "active.unpin": "Unpin",
      "active.pinHint": "Pin to the top of the section",
      "active.hide": "hide",
      "active.hideHint": "Hide until the next message in this session",
      "active.hideAria": "Hide until the next message",
    },
    ru: {
      // общее
      "active.sending": "отправляю…",
      "active.noHostReply": "Obsidian не ответил — проверь вкладку",
      "active.error": "ошибка: {msg}",
      "active.errorWord": "ошибка",
      "active.notSent": "не отправлено: {reason}",
      "active.quoted": "«{text}»",
      "active.go": "Перейти",
      "active.close": "Закрыть",
      // статусы
      "active.status.busy": "работает",
      "active.status.busyHint": "Агент сейчас работает",
      "active.status.background": "работает в фоне",
      "active.status.backgroundShort": "в фоне",
      "active.status.backgroundHint": "Ход закончен, но сессию разбудит фон, а не ты",
      "active.status.waiting": "нужно твоё решение",
      "active.status.waitingHint": "Открыт вопрос или запрос разрешения — ответь кнопкой в карточке или во вкладке",
      "active.status.idle": "ждёт",
      "active.status.idleHint": "Агент закончил и ждёт твоего сообщения",
      // карточка
      "active.openInSearch": "Открыть карточку в поиске",
      "active.notIndexed": "Сессия ещё не в индексе",
      "active.noDescription": "Описание появится после классификации.",
      "active.tasksPill": "задачи {count}",
      "active.tasksNow": "Сейчас: {task}",
      "active.goalHint": "Активна цель /goal: {goal}",
      "active.sensitive": "чувствительная",
      "active.when": "начата {start} · сообщение {ago}",
      "active.whenHint": "начата {start}, последнее сообщение {last}",
      "active.turnsNone": "ходы —",
      "active.turns": ["{n} ход", "{n} хода", "{n} ходов"],
      "active.costRecorded": "Claude Code записал ${cost}{at} — он пишет сумму только при выходе. ",
      "active.costRecordedAt": " на {date}",
      "active.costNotRecorded": "Claude Code ещё не записывал сумму — он пишет её только при выходе. ",
      "active.costNow": "Сейчас ≈ ${cost}: досчитано по токенам ответов.",
      "active.costPartial": " Есть ответы моделей без известной цены — оценка занижена.",
      "active.goHint": "Перейти во вкладку терминала этой сессии",
      "active.closeHint": "Закрыть вкладку — сессия завершится (спросит подтверждение)",
      "active.notInTab": "Сессия запущена не во вкладке Obsidian",
      "active.notInTabApp": "Сессия запущена не во вкладке Obsidian — в {app}",
      "active.buttonsInObsidian": "Кнопки работают внутри Obsidian",
      "active.tasksAllDone": "все задачи сделаны",
      "active.tasksNotStarted": "ждут начала",
      // доставка и ответ
      "active.delivery.sending": "отправлено, жду его в сессии…",
      "active.delivery.queued": "в очереди — Claude прочтёт после текущего шага",
      "active.delivery.lost": "не видно в сессии — проверь вкладку",
      "active.you": "Ты, {ago} · {state}",
      "active.youWas": "Ты, {ago}",
      "active.promptCut": "… продолжение запроса — в ленте",
      "active.interrupted": "прервано — Claude не ответил",
      "active.awaitingClaude": "ждёт ответа Claude",
      "active.lostHint": "За 15 секунд сообщение не появилось ни в транскрипте, ни в очереди. Возможно, вкладка не приняла ввод или его перехватил диалог.",
      "active.images": ["+ {n} картинка", "+ {n} картинки", "+ {n} картинок"],
      "active.nowMd": "**сейчас:** {text}",
      "active.lastNote": "Последняя заметка агента, {ago}",
      "active.collapse": "свернуть",
      "active.showAll": "показать целиком ({n} симв.)",
      "active.queuedOne": "в очереди «{text}»",
      "active.queuedMany": "в очереди {n} сообщ. — «{text}»",
      "active.replyStartAbove": "… начало ответа выше",
      "active.noTextReply": "Текстового ответа пока нет.",
      // поле ответа и картинки
      "active.maxImages": "не больше {n} картинок",
      "active.imageFailed": "картинка не прикрепилась: {msg}",
      "active.imageAlt": "картинка {n}",
      "active.removeImage": "Убрать картинку",
      "active.replyAria": "Ответ в сессию",
      "active.sendHint": "Отправить (Enter)",
      "active.send": "Отправить",
      "active.attachHint": "Прикрепить картинку (или вставь ⌘V / перетащи в поле)",
      "active.attach": "Прикрепить картинку",
      "active.blockedNoHost": "отправка работает, когда каталог открыт внутри Obsidian",
      "active.blockedNoTab": "сессия запущена не во вкладке Obsidian",
      "active.blockedDialog": "открыт диалог — ответь кнопкой выше (Enter там выбрал бы вариант)",
      "active.placeholderBusy": "Агент работает — сообщение встанет в очередь…",
      "active.placeholderBackground": "Сессия ждёт фон — можно написать, агент прочтёт сразу…",
      "active.placeholder": "Ответить… Enter — отправить, Shift+Enter — перенос, ⌘V — картинка",
      // сводка и секции
      "active.none": "нет",
      "active.shown": "показано {n}",
      "active.shownHint": "Под фильтры подходит {shown} из {total}",
      "active.hidden": "скрыто {n}",
      "active.hiddenHint": "Скрытые вернутся сами со следующим сообщением. Нажми — показать все сейчас",
      "active.updated": "обновлено {time}",
      "active.limit.fiveHour": "5ч",
      "active.limit.week": "нед",
      "active.limitsStale": " (давно)",
      "active.limitsNone": "лимиты —",
      "active.limitsHint": "Лимиты подписки: {limits} — из строки состояния Claude Code, пока открыта любая сессия",
      "active.limitsSetup": "Лимиты подписки Claude Code отдаёт только строке состояния. Подключи её: в ~/.claude/settings.json добавь {snippet}",
      "active.terminal": "терминал ",
      "active.terminalHint": "Связь с терминалом: {state}{reason}. «Перейти», «Закрыть» и отправка идут через плагин Obsidian во вкладку терминала",
      "active.terminalChecking": "проверяется",
      "active.terminalYes": "есть",
      "active.terminalNo": "нет",
      "active.keysHint": "Клавиши вкладки «Активные»",
      "active.noSessions": "Сейчас ни одна сессия Claude Code не запущена.",
      "active.allHidden": "Все подходящие сессии скрыты — «скрыто» в строке сверху вернёт их.",
      "active.noMatches": "Под выбранные фильтры не подходит ни одна сессия.",
      "active.sectionWaiting": "Ждут тебя",
      "active.sectionWorking": "Работают",
      // диалог и «Стоп»
      "active.answerSent": "ответ отправлен",
      "active.permissionInTab": "Запрос разрешения — ответить можно во вкладке терминала",
      "active.questionInTab": "Вопрос — ответить можно во вкладке терминала",
      "active.readingDialog": "читаю диалог…",
      "active.dialogNotRead": "диалог не прочитан — ответь во вкладке",
      "active.panelOpen": "Открыта панель: {title}",
      "active.closePanel": "Закрыть панель",
      "active.permission": "Разрешение: {title}",
      "active.dialogTabOnly": "этот диалог — только во вкладке",
      "active.pressesKey": "нажмёт {n} во вкладке сессии",
      "active.stop": "Стоп",
      "active.stopNeedsTab": "Работает, когда сессия открыта во вкладке Obsidian",
      "active.stopDialogHint": "Закрыть диалог без ответа — как Esc во вкладке",
      "active.stopStepHint": "Прервать текущий шаг — как Esc во вкладке",
      "active.stopDialogTitle": "Закрыть диалог без ответа?",
      "active.stopSessionTitle": "Прервать сессию?",
      "active.stopDialogBody": "«{title}»: диалог закроется, как по Esc во вкладке; команда не выполнится.",
      "active.stopSessionBody": "«{title}»: агент остановит текущий шаг, как по Esc во вкладке. Сессия останется открытой — можно написать, что делать дальше.",
      "active.nowText": "сейчас: {text}",
      "active.closeDialog": "Закрыть диалог",
      "active.interrupt": "Прервать",
      "active.stopping": "останавливаю…",
      "active.stopped": "остановлено",
      "active.notStopped": "не остановлено: {reason}",
      // план
      "active.planAutoFull": "Выполнять — правки без спроса",
      "active.planAutoShort": "Выполнять",
      "active.planManualFull": "Выполнять — правки с подтверждением",
      "active.planManualShort": "С подтв.",
      "active.sendingFeedback": "отправляю замечания…",
      "active.planFeedbackPlaceholder": "Что изменить в плане? Enter — отправить",
      "active.sendFeedback": "Отправить замечания",
      "active.sendFeedbackHint": "Агент получит текст и перепишет план — выполнять он не начнёт",
      "active.planReady": "План готов — выполнять?",
      "active.planNotRead": "план не прочитан: {error}",
      "active.readingPlan": "читаю план…",
      "active.planOptionHint": "«{text}» — нажмёт {n} во вкладке сессии",
      "active.planOptionHintKnown": "{label}: «{text}» — нажмёт {n} во вкладке сессии",
      "active.revise": "Доработать…",
      "active.reviseHint": "Написать, что изменить: план вернётся агенту на доработку",
      "active.plan": "План",
      "active.readPlanHint": "Прочитать план целиком",
      // восстановление и перенос
      "active.restoreMore": " и ещё {n}",
      "active.restoreOne": "После перезапуска Obsidian закрылась сессия, открытая во вкладке: {names}.",
      "active.restoreMany": ["После перезапуска Obsidian закрылись {n} сессия, открытые во вкладках: {names}.",
                             "После перезапуска Obsidian закрылись {n} сессии, открытые во вкладках: {names}.",
                             "После перезапуска Obsidian закрылись {n} сессий, открытые во вкладках: {names}."],
      "active.restore": "Восстановить",
      "active.restoreAll": "Восстановить все",
      "active.restoreHint": "Каждая откроется своей вкладкой терминала через claude --resume",
      "active.restoreSkip": "не нужно",
      "active.opening": "открываю…",
      "active.restoreFailed": "не вышло: {names} — у сессии нет рабочей папки, открой из поиска",
      "active.restoreDone": "открыто вкладок: {n}",
      "active.move": "Перенести",
      "active.otherTerminal": "другом терминале",
      "active.moveHint": "Сессия идёт в {app}: завершить там и открыть вкладкой здесь",
      "active.moveTitle": "Перенести в Obsidian?",
      "active.moveBody": "«{title}» идёт в {app}. Atlas завершит её там (как Ctrl+C) и откроет здесь вкладкой через claude --resume. Окно терминала там останется — его можно закрыть.",
      "active.moveBodyBusy": "«{title}» идёт в {app}. Atlas завершит её там (как Ctrl+C; текущий ход прервётся) и откроет здесь вкладкой через claude --resume. Окно терминала там останется — его можно закрыть.",
      "active.moveEnding": "завершаю сессию там…",
      "active.moveFailed": "не вышло: {msg}",
      "active.moveNoFolder": "Сессия завершена, но рабочей папки нет — открой её из поиска.",
      // фильтры и сетка
      "active.filter.domain": "Домен",
      "active.filter.project": "Проект",
      "active.filter.topic": "Тема",
      "active.filter.period": "Период",
      "active.filterAll": "{label}: все",
      "active.noValues": "нет значений",
      "active.auto": "авто",
      "active.layoutHint": "Сколько карточек на экран: столбцы × ряды",
      "active.layoutAria": "Раскладка карточек",
      "active.cols": ["{n} столбец", "{n} столбца", "{n} столбцов"],
      "active.rows": ["{n} ряд", "{n} ряда", "{n} рядов"],
      "active.hoverAndClick": "наведи и кликни",
      "active.autoFullHint": "По ширине экрана, два ряда",
      "active.autoCompactHint": "4 столбца × 5 рядов",
      "active.find": "найти…",
      "active.allVisible": "все видимые",
      "active.reset": "сбросить",
      "active.viewAria": "Вид карточек",
      "active.modeCompact": "комп.",
      "active.modeCompactHint": "Компактно: много маленьких карточек",
      "active.modeFull": "подр.",
      "active.modeFullHint": "Подробно: ответ Claude и поле ответа в карточке",
      // закрепить и скрыть
      "active.unpin": "Открепить",
      "active.pinHint": "Закрепить сверху секции",
      "active.hide": "скрыть",
      "active.hideHint": "Убрать с экрана до следующего сообщения в этой сессии",
      "active.hideAria": "Скрыть до следующего сообщения",
    },
  });
})(typeof window !== "undefined" ? window : globalThis);
