// Page strings: the Active tab: cards, dialogs, plan, filters, restore. Keys start with "active."; en and ru have the same key set.
// Plurals are arrays: ru [one, few, many], en [one, other]; {n} is the number.
(function (root) {
  const I = root.I18N;
  I.add({
    en: {
      // common
      "active.sending": "sending…",
      "active.sendingWithNote": "sending the answer with the note…",
      "active.previewLoading": "showing that option's preview…",
      "active.previewOf": "Preview of option {n}",
      "active.previewShow": "Show option {n}'s preview (moves the highlight in the tab; nothing is answered)",
      "active.previewShown": "Its preview is shown below",
      "active.previewPickHint": "Answer with option {n}",
      "active.previewInFull": "The options have previews: open the detailed view to read them",
      "active.noteAdd": "+ Note",
      "active.noteClose": "Without a note",
      "active.noteAria": "A note for the answer",
      "active.notePlaceholder": "A note: it goes with the option you choose",
      "active.noteHint": "Write the note, then choose an option above: it is sent with the note",
      "active.noHostReply": "Obsidian did not respond — check the tab",
      "active.error": "error: {msg}",
      "active.errorWord": "error",
      "active.notSent": "not sent: {reason}",
      "active.quoted": "“{text}”",
      "active.go": "Go",
      "active.close": "Close",
      // statuses
      "active.status.busy": "working",
      "active.status.busyHint": "The agent is working right now",
      "active.status.background": "working in background",
      "active.status.backgroundShort": "background",
      "active.status.backgroundHint": "The turn is over, but background work will wake the session, not you",
      "active.status.waiting": "needs your decision",
      "active.status.waitingHint": "A question or permission request is open — answer with a button in the card or in the tab",
      "active.status.idle": "waiting",
      "active.status.idleHint": "The agent is done and waiting for your message",
      // card
      "active.openInSearch": "Open the card in search",
      "active.notIndexed": "Session is not indexed yet",
      "active.noDescription": "The description appears after classification.",
      "active.tasksPill": "tasks {count}",
      "active.tasksNow": "Now: {task}",
      "active.goalHint": "Active /goal: {goal}",
      "active.sensitive": "sensitive",
      "active.when": "started {start} · message {ago}",
      "active.whenHint": "started {start}, last message {last}",
      "active.turnsNone": "turns —",
      "active.turns": ["{n} turn", "{n} turns"],
      "active.costRecorded": "Claude Code recorded ${cost}{at} — it writes the total only on exit. ",
      "active.costRecordedAt": " at {date}",
      "active.costNotRecorded": "Claude Code has not recorded a total yet — it writes one only on exit. ",
      "active.costNow": "Now ≈ ${cost}: estimated from reply tokens.",
      "active.costPartial": " Some replies come from models with unknown prices — the estimate is too low.",
      "active.goHint": "Go to this session's terminal tab",
      "active.closeHint": "Close the tab — the session ends (asks for confirmation)",
      "active.notInTab": "The session is not running in an Obsidian tab",
      "active.notInTabApp": "The session is not running in an Obsidian tab — it runs in {app}",
      "active.buttonsInObsidian": "Buttons work inside Obsidian",
      "active.tasksAllDone": "all tasks done",
      "active.tasksNotStarted": "not started yet",
      // delivery and reply
      "active.delivery.sending": "sent, waiting for it in the session…",
      "active.delivery.queued": "queued — the agent will read it after the current step",
      "active.delivery.lost": "not visible in the session — check the tab",
      "active.you": "You, {ago} · {state}",
      "active.youWas": "You, {ago}",
      "active.toNewest": "↓ Newest",
      "active.toNewest.hint": "Scroll to the newest message; the chat then follows new ones again",
      "active.promptCut": "… the prompt continues in the feed",
      "active.interrupted": "interrupted — no reply",
      "active.awaitingReply": "waiting for a reply",
      "active.lostHint": "Within 15 seconds the message appeared neither in the transcript nor in the queue. The tab may not have accepted the input, or a dialog intercepted it.",
      "active.images": ["+ {n} image", "+ {n} images"],
      "active.nowMd": "**now:** {text}",
      "active.lastNote": "Agent's latest note, {ago}",
      "active.collapse": "collapse",
      "active.showAll": "show all ({n} chars)",
      "active.queuedOne": "queued “{text}”",
      "active.queuedMany": "queued {n} msgs — “{text}”",
      "active.replyStartAbove": "… the start of the reply is above",
      "active.noTextReply": "No text reply yet.",
      // reply field and images
      "active.maxImages": "no more than {n} images",
      "active.imageFailed": "image not attached: {msg}",
      "active.imageAlt": "image {n}",
      "active.removeImage": "Remove image",
      "active.replyAria": "Reply to the session",
      "active.sendHint": "Send (Enter)",
      "active.send": "Send",
      "active.attachHint": "Attach an image (or paste with ⌘V / drop it into the field)",
      "active.attach": "Attach image",
      "active.blockedNoHost": "sending works when the catalog is open inside Obsidian",
      "active.blockedNoTab": "the session is not running in an Obsidian tab",
      "active.blockedDialog": "a dialog is open — answer with a button above (Enter there would pick an option)",
      "active.placeholderBusy": "The agent is working — the message will be queued…",
      "active.placeholderBackground": "The session is waiting on background work — write now, the agent reads it right away…",
      "active.placeholder": "Reply… Enter to send, Shift+Enter for a new line, ⌘V for an image",
      // summary and sections
      "active.none": "none",
      "active.shown": "shown {n}",
      "active.shownHint": "{shown} of {total} match the filters",
      "active.hidden": "hidden {n}",
      "active.hiddenHint": "Hidden cards come back on their own with the next message. Click to show all now",
      "active.updated": "updated {time}",
      "active.limit.fiveHour": "5h",
      "active.limit.week": "wk",
      "active.limitsAge": " · {age}",
      "active.limitsAsOf": " (numbers as of {time})",
      "active.limitReached": "{label} 100%, used up{until}",
      "active.limitsNone": "limits —",
      "active.limitsHint": "Subscription limits: {limits} — from the Claude Code status line while any session is open",
      "active.limitsSetup": "Claude Code reports subscription limits only to the status line. Connect it: in ~/.claude/settings.json add {snippet}",
      "active.limitsClaude": "Claude {limits}",
      "active.limitsCodex": "Codex {limits}",
      "active.limitsCodexLive": "Codex limits: {limits} — live from Codex itself, as its /status shows them (read at {time})",
      "active.limitsCodexRun": "Codex limits: {limits} — from the last Codex run at {time}; Codex itself has not answered",
      "active.costCodex": "Codex records no total. ≈ ${cost}: estimated from the thread's tokens.",
      "active.costCodexNone": "Codex records no total, and the price of this model is unknown.",
      "active.terminal": "terminal ",
      "active.terminalHint": "Terminal link: {state}{reason}. “Go”, “Close” and sending go through the Obsidian plugin to the terminal tab",
      "active.terminalChecking": "checking",
      "active.terminalYes": "yes",
      "active.terminalNo": "no",
      "active.keysHint": "Active tab shortcuts",
      "active.noSessions": "No Claude Code or Codex session is running right now.",
      "active.allHidden": "All matching sessions are hidden — “hidden” in the line above brings them back.",
      "active.noMatches": "No session matches the selected filters.",
      "active.sectionWaiting": "Waiting for you",
      "active.sectionDecision": "Needs your decision",
      "active.decisionStrip": "Needs your decision",
      "active.sectionWorking": "Working",
      // dialog and Stop
      "active.answerSent": "answer sent",
      "active.permissionInTab": "Permission request — answer it in the terminal tab",
      "active.questionInTab": "Question — answer it in the terminal tab",
      "active.readingDialog": "reading the dialog…",
      "active.dialogNotRead": "dialog not read — answer in the tab",
      "active.panelOpen": "Panel open: {title}",
      "active.closePanel": "Close panel",
      "active.permission": "Permission: {title}",
      "active.dialogTabOnly": "this dialog can only be answered in the tab",
      "active.pressesKey": "presses {n} in the session tab",
      "active.stop": "Stop",
      "active.stopNeedsTab": "Works when the session is open in an Obsidian tab",
      "active.stopDialogHint": "Close the dialog without answering — like Esc in the tab",
      "active.stopStepHint": "Interrupt the current step — like Esc in the tab",
      "active.stopDialogTitle": "Close the dialog without answering?",
      "active.stopSessionTitle": "Interrupt the session?",
      "active.stopDialogBody": "“{title}”: the dialog closes as if Esc were pressed in the tab; the command will not run.",
      "active.stopSessionBody": "“{title}”: the agent stops the current step, as with Esc in the tab. The session stays open — you can write what to do next.",
      "active.nowText": "now: {text}",
      "active.closeDialog": "Close dialog",
      "active.interrupt": "Interrupt",
      "active.stopping": "stopping…",
      "active.stopped": "stopped",
      "active.notStopped": "not stopped: {reason}",
      // own answer to a dialog question
      "active.freeOption": "Your own answer…",
      "active.freeOptionHint": "Type the answer in the field below — like “Type something” in the terminal",
      "active.freeOptionHintCompact": "Type the answer right here — like “Type something” in the terminal",
      "active.freePlaceholder": "Your answer — Enter to send, Esc to cancel",
      "active.freeAria": "Your answer for option {n}",
      "active.answering": "Answering: {question}",
      "active.answeringCodex": "What Codex should do instead — it declines and gets your text",
      "active.cancelAnswer": "Cancel",
      "active.cancelAnswerHint": "Back to the usual reply field (Esc)",
      "active.sendAnswer": "Send answer",
      "active.sendAnswerHint": "Presses {n}, types the text, checks it on the tab's screen, then Enter",
      "active.sendingAnswer": "sending the answer…",
      "active.chatOption": "Chat about this",
      "active.chatOptionHint": "Declines the question; the agent asks what to clarify and you reply in the field",
      // plan
      "active.planAutoFull": "Run — edits without asking",
      "active.planAutoShort": "Run",
      "active.planManualFull": "Run — approve each edit",
      "active.planManualShort": "Run, confirm",
      "active.sendingFeedback": "sending feedback…",
      "active.planFeedbackPlaceholder": "What should change in the plan? Enter to send",
      "active.sendFeedback": "Send feedback",
      "active.sendFeedbackHint": "The agent gets the text and rewrites the plan — it will not start executing",
      "active.planReady": "Plan ready — execute?",
      "active.planNotRead": "plan not read: {error}",
      "active.readingPlan": "reading the plan…",
      "active.planOptionHint": "“{text}” — presses {n} in the session tab",
      "active.planOptionHintKnown": "{label}: “{text}” — presses {n} in the session tab",
      "active.revise": "Revise…",
      "active.reviseHint": "Write what to change: the plan goes back to the agent for revision",
      "active.plan": "Plan",
      "active.readPlanHint": "Read the full plan",
      // restore and move
      "active.restoreMore": " and {n} more",
      "active.restoreOne": "After Obsidian restarted, a session open in a tab was closed: {names}.",
      "active.restoreMany": ["After Obsidian restarted, {n} session open in tabs was closed: {names}.",
                             "After Obsidian restarted, {n} sessions open in tabs were closed: {names}."],
      "active.restore": "Restore",
      "active.restoreAll": "Restore all",
      "active.restoreHint": "Each one opens in its own terminal tab, right where it left off",
      "active.restoreSkip": "dismiss",
      "active.opening": "opening…",
      "active.restoreFailed": "failed: {names} — the session has no working folder, open it from search",
      "active.restoreDone": "tabs opened: {n}",
      "active.restoreElsewhere": "already running outside Obsidian, not opened twice: {names} — use Move on its card",
      "active.heldMany": ["{n} tab closed with the plugin, but its agent keeps running: {names}. Without an answer it ends in 30 min.",
                          "{n} tabs closed with the plugin, but their agents keep running: {names}. Without an answer they end in 30 min."],
      "active.heldBack": "Bring the tab back",
      "active.heldBackAll": "Bring the tabs back",
      "active.heldBackHint": "Tabs open on the same processes: the agents are not restarted",
      "active.heldEnd": "End",
      "active.heldEndHint": "End the agents; any session can be continued later from Recently closed",
      "active.heldEndTitle": "End the agents?",
      "active.heldEndBody": ["{n} agent without a tab will end: {names}. The session can be continued later from Recently closed.",
                             "{n} agents without tabs will end: {names}. Each session can be continued later from Recently closed."],
      "active.heldGoHint": "The tab closed with the plugin, the agent keeps running: open a tab on the same process",
      "active.move": "Move",
      "active.otherTerminal": "another terminal",
      "active.moveHint": "The session runs in {app}: end it there and open it in a tab here",
      "active.moveTitle": "Move to Obsidian?",
      "active.moveBody": "“{title}” runs in {app}. Atlas will end it there (like Ctrl+C) and continue it here in a terminal tab. The terminal window there stays — you can close it.",
      "active.moveBodyBusy": "“{title}” runs in {app}. Atlas will end it there (like Ctrl+C; the current turn will be interrupted) and continue it here in a terminal tab. The terminal window there stays — you can close it.",
      "active.moveEnding": "ending the session there…",
      "active.moveFailed": "failed: {msg}",
      "active.moveNoFolder": "The session ended, but it has no working folder — open it from search.",
      // filters and grid
      "active.filter.domain": "Domain",
      "active.filter.project": "Project",
      "active.filter.topic": "Topic",
      "active.filter.period": "Period",
      "active.filterAll": "{label}: all",
      "active.noValues": "no values",
      "active.auto": "auto",
      "active.layoutHint": "Cards per screen: columns × rows",
      "active.layoutAria": "Card layout",
      "active.cols": ["{n} column", "{n} columns"],
      "active.rows": ["{n} row", "{n} rows"],
      "active.hoverAndClick": "hover and click",
      "active.autoFullHint": "Fits the screen width, two rows",
      "active.autoCompactHint": "4 columns × 5 rows",
      "active.find": "find…",
      "active.allVisible": "all visible",
      "active.reset": "reset",
      "active.viewAria": "Card view",
      "active.modeCompact": "compact",
      "active.modeCompactHint": "Compact: many small cards",
      "active.modeFull": "detailed",
      "active.modeFullHint": "Detailed: the agent's reply and a reply field in the card",
      // pin and hide
      "active.unpin": "Unpin",
      "active.pinHint": "Pin to the top of the section",
      "active.hide": "hide",
      "active.hideHint": "Hide until the next message in this session",
      "active.hideAria": "Hide until the next message",
    },
    ru: {
      // common
      "active.sending": "отправляю…",
      "active.sendingWithNote": "отправляю ответ с заметкой…",
      "active.previewLoading": "показываю превью варианта…",
      "active.previewOf": "Превью варианта {n}",
      "active.previewShow": "Показать превью варианта {n} (подсветка во вкладке сдвинется, ответ не уйдёт)",
      "active.previewShown": "Его превью — ниже",
      "active.previewPickHint": "Ответить вариантом {n}",
      "active.previewInFull": "У вариантов есть превью: открой подробный вид, чтобы их прочитать",
      "active.noteAdd": "+ Заметка",
      "active.noteClose": "Без заметки",
      "active.noteAria": "Заметка к ответу",
      "active.notePlaceholder": "Заметка: уйдёт вместе с выбранным вариантом",
      "active.noteHint": "Напиши заметку и выбери вариант выше — он уйдёт вместе с ней",
      "active.noHostReply": "Obsidian не ответил — проверь вкладку",
      "active.error": "ошибка: {msg}",
      "active.errorWord": "ошибка",
      "active.notSent": "не отправлено: {reason}",
      "active.quoted": "«{text}»",
      "active.go": "Перейти",
      "active.close": "Закрыть",
      // statuses
      "active.status.busy": "работает",
      "active.status.busyHint": "Агент сейчас работает",
      "active.status.background": "работает в фоне",
      "active.status.backgroundShort": "в фоне",
      "active.status.backgroundHint": "Ход закончен, но сессию разбудит фон, а не ты",
      "active.status.waiting": "нужно твоё решение",
      "active.status.waitingHint": "Открыт вопрос или запрос разрешения — ответь кнопкой в карточке или во вкладке",
      "active.status.idle": "ждёт",
      "active.status.idleHint": "Агент закончил и ждёт твоего сообщения",
      // card
      "active.openInSearch": "Открыть карточку в поиске",
      "active.notIndexed": "Сессия ещё не в индексе",
      "active.noDescription": "Описание появится после классификации.",
      "active.tasksPill": "задачи {count}",
      "active.tasksNow": "Сейчас: {task}",
      "active.goalHint": "Активна цель /goal: {goal}",
      "active.sensitive": "чувствительная",
      "active.when": "начата {start} · сообщение {ago}",
      "active.whenHint": "начата {start}, последнее сообщение {last}",
      "active.turnsNone": "ходы —",
      "active.turns": ["{n} ход", "{n} хода", "{n} ходов"],
      "active.costRecorded": "Claude Code записал ${cost}{at} — он пишет сумму только при выходе. ",
      "active.costRecordedAt": " на {date}",
      "active.costNotRecorded": "Claude Code ещё не записывал сумму — он пишет её только при выходе. ",
      "active.costNow": "Сейчас ≈ ${cost}: досчитано по токенам ответов.",
      "active.costPartial": " Есть ответы моделей без известной цены — оценка занижена.",
      "active.goHint": "Перейти во вкладку терминала этой сессии",
      "active.closeHint": "Закрыть вкладку — сессия завершится (спросит подтверждение)",
      "active.notInTab": "Сессия запущена не во вкладке Obsidian",
      "active.notInTabApp": "Сессия запущена не во вкладке Obsidian — в {app}",
      "active.buttonsInObsidian": "Кнопки работают внутри Obsidian",
      "active.tasksAllDone": "все задачи сделаны",
      "active.tasksNotStarted": "ждут начала",
      // delivery and reply
      "active.delivery.sending": "отправлено, жду его в сессии…",
      "active.delivery.queued": "в очереди — агент прочтёт после текущего шага",
      "active.delivery.lost": "не видно в сессии — проверь вкладку",
      "active.you": "Ты, {ago} · {state}",
      "active.youWas": "Ты, {ago}",
      "active.toNewest": "↓ К новым",
      "active.toNewest.hint": "К последнему сообщению; дальше чат снова сам следит за новыми",
      "active.promptCut": "… продолжение запроса — в ленте",
      "active.interrupted": "прервано — ответа не было",
      "active.awaitingReply": "ждёт ответа",
      "active.lostHint": "За 15 секунд сообщение не появилось ни в транскрипте, ни в очереди. Возможно, вкладка не приняла ввод или его перехватил диалог.",
      "active.images": ["+ {n} картинка", "+ {n} картинки", "+ {n} картинок"],
      "active.nowMd": "**сейчас:** {text}",
      "active.lastNote": "Последняя заметка агента, {ago}",
      "active.collapse": "свернуть",
      "active.showAll": "показать целиком ({n} симв.)",
      "active.queuedOne": "в очереди «{text}»",
      "active.queuedMany": "в очереди {n} сообщ. — «{text}»",
      "active.replyStartAbove": "… начало ответа выше",
      "active.noTextReply": "Текстового ответа пока нет.",
      // reply field and images
      "active.maxImages": "не больше {n} картинок",
      "active.imageFailed": "картинка не прикрепилась: {msg}",
      "active.imageAlt": "картинка {n}",
      "active.removeImage": "Убрать картинку",
      "active.replyAria": "Ответ в сессию",
      "active.sendHint": "Отправить (Enter)",
      "active.send": "Отправить",
      "active.attachHint": "Прикрепить картинку (или вставь ⌘V / перетащи в поле)",
      "active.attach": "Прикрепить картинку",
      "active.blockedNoHost": "отправка работает, когда каталог открыт внутри Obsidian",
      "active.blockedNoTab": "сессия запущена не во вкладке Obsidian",
      "active.blockedDialog": "открыт диалог — ответь кнопкой выше (Enter там выбрал бы вариант)",
      "active.placeholderBusy": "Агент работает — сообщение встанет в очередь…",
      "active.placeholderBackground": "Сессия ждёт фон — можно написать, агент прочтёт сразу…",
      "active.placeholder": "Ответить… Enter — отправить, Shift+Enter — перенос, ⌘V — картинка",
      // summary and sections
      "active.none": "нет",
      "active.shown": "показано {n}",
      "active.shownHint": "Под фильтры подходит {shown} из {total}",
      "active.hidden": "скрыто {n}",
      "active.hiddenHint": "Скрытые вернутся сами со следующим сообщением. Нажми — показать все сейчас",
      "active.updated": "обновлено {time}",
      "active.limit.fiveHour": "5ч",
      "active.limit.week": "нед",
      "active.limitsAge": " · {age}",
      "active.limitsAsOf": " (цифры на {time})",
      "active.limitReached": "{label} 100%, исчерпан{until}",
      "active.limitsNone": "лимиты —",
      "active.limitsHint": "Лимиты подписки: {limits} — из строки состояния Claude Code, пока открыта любая сессия",
      "active.limitsSetup": "Лимиты подписки Claude Code отдаёт только строке состояния. Подключи её: в ~/.claude/settings.json добавь {snippet}",
      "active.limitsClaude": "Claude {limits}",
      "active.limitsCodex": "Codex {limits}",
      "active.limitsCodexLive": "Лимиты Codex: {limits} — прямо из Codex, как их показывает /status (получены в {time})",
      "active.limitsCodexRun": "Лимиты Codex: {limits} — из последнего запуска Codex в {time}; сам Codex не ответил",
      "active.costCodex": "Codex не пишет сумму. ≈ ${cost}: досчитано по токенам треда.",
      "active.costCodexNone": "Codex не пишет сумму, а цена этой модели неизвестна.",
      "active.terminal": "терминал ",
      "active.terminalHint": "Связь с терминалом: {state}{reason}. «Перейти», «Закрыть» и отправка идут через плагин Obsidian во вкладку терминала",
      "active.terminalChecking": "проверяется",
      "active.terminalYes": "есть",
      "active.terminalNo": "нет",
      "active.keysHint": "Клавиши вкладки «Активные»",
      "active.noSessions": "Сейчас ни одна сессия Claude Code или Codex не запущена.",
      "active.allHidden": "Все подходящие сессии скрыты — «скрыто» в строке сверху вернёт их.",
      "active.noMatches": "Под выбранные фильтры не подходит ни одна сессия.",
      "active.sectionWaiting": "Ждут тебя",
      "active.sectionDecision": "Нужно решение",
      "active.decisionStrip": "Нужно твоё решение",
      "active.sectionWorking": "Работают",
      // dialog and Stop
      "active.answerSent": "ответ отправлен",
      "active.permissionInTab": "Запрос разрешения — ответить можно во вкладке терминала",
      "active.questionInTab": "Вопрос — ответить можно во вкладке терминала",
      "active.readingDialog": "читаю диалог…",
      "active.dialogNotRead": "диалог не прочитан — ответь во вкладке",
      "active.panelOpen": "Открыта панель: {title}",
      "active.closePanel": "Закрыть панель",
      "active.permission": "Разрешение: {title}",
      "active.dialogTabOnly": "этот диалог — только во вкладке",
      "active.pressesKey": "нажмёт {n} во вкладке сессии",
      "active.stop": "Стоп",
      "active.stopNeedsTab": "Работает, когда сессия открыта во вкладке Obsidian",
      "active.stopDialogHint": "Закрыть диалог без ответа — как Esc во вкладке",
      "active.stopStepHint": "Прервать текущий шаг — как Esc во вкладке",
      "active.stopDialogTitle": "Закрыть диалог без ответа?",
      "active.stopSessionTitle": "Прервать сессию?",
      "active.stopDialogBody": "«{title}»: диалог закроется, как по Esc во вкладке; команда не выполнится.",
      "active.stopSessionBody": "«{title}»: агент остановит текущий шаг, как по Esc во вкладке. Сессия останется открытой — можно написать, что делать дальше.",
      "active.nowText": "сейчас: {text}",
      "active.closeDialog": "Закрыть диалог",
      "active.interrupt": "Прервать",
      "active.stopping": "останавливаю…",
      "active.stopped": "остановлено",
      "active.notStopped": "не остановлено: {reason}",
      // own answer to a dialog question
      "active.freeOption": "Свой ответ…",
      "active.freeOptionHint": "Напиши ответ в поле ниже — как «Type something» в терминале",
      "active.freeOptionHintCompact": "Напиши ответ прямо здесь — как «Type something» в терминале",
      "active.freePlaceholder": "Твой ответ — Enter отправить, Esc отменить",
      "active.freeAria": "Твой ответ для варианта {n}",
      "active.answering": "Ответ на вопрос: {question}",
      "active.answeringCodex": "Что Codex сделать вместо этого — он откажется и получит твой текст",
      "active.cancelAnswer": "Отмена",
      "active.cancelAnswerHint": "Вернуть обычное поле ответа (Esc)",
      "active.sendAnswer": "Отправить ответ",
      "active.sendAnswerHint": "Нажмёт {n}, напечатает текст, сверит его на экране вкладки, потом Enter",
      "active.sendingAnswer": "отправляю ответ…",
      "active.chatOption": "Обсудить вопрос",
      "active.chatOptionHint": "Отклонит вопрос; агент спросит, что уточнить, а ответишь в поле",
      // plan
      "active.planAutoFull": "Выполнять — правки без спроса",
      "active.planAutoShort": "Выполнять",
      "active.planManualFull": "Выполнять — правки с подтверждением",
      "active.planManualShort": "С подтв.",
      "active.sendingFeedback": "отправляю замечания…",
      "active.planFeedbackPlaceholder": "Что изменить в плане? Enter — отправить",
      "active.sendFeedback": "Отправить замечания",
      "active.sendFeedbackHint": "Агент получит текст и перепишет план — выполнять он не начнёт",
      "active.planReady": "План готов — выполнять?",
      "active.planNotRead": "план не прочитан: {error}",
      "active.readingPlan": "читаю план…",
      "active.planOptionHint": "«{text}» — нажмёт {n} во вкладке сессии",
      "active.planOptionHintKnown": "{label}: «{text}» — нажмёт {n} во вкладке сессии",
      "active.revise": "Доработать…",
      "active.reviseHint": "Написать, что изменить: план вернётся агенту на доработку",
      "active.plan": "План",
      "active.readPlanHint": "Прочитать план целиком",
      // restore and move
      "active.restoreMore": " и ещё {n}",
      "active.restoreOne": "После перезапуска Obsidian закрылась сессия, открытая во вкладке: {names}.",
      "active.restoreMany": ["После перезапуска Obsidian закрылись {n} сессия, открытые во вкладках: {names}.",
                             "После перезапуска Obsidian закрылись {n} сессии, открытые во вкладках: {names}.",
                             "После перезапуска Obsidian закрылись {n} сессий, открытые во вкладках: {names}."],
      "active.restore": "Восстановить",
      "active.restoreAll": "Восстановить все",
      "active.restoreHint": "Каждая откроется своей вкладкой терминала — с того же места",
      "active.restoreSkip": "не нужно",
      "active.opening": "открываю…",
      "active.restoreFailed": "не вышло: {names} — у сессии нет рабочей папки, открой из поиска",
      "active.restoreDone": "открыто вкладок: {n}",
      "active.restoreElsewhere": "уже работают вне Obsidian, второй раз не открываю: {names} — на карточке есть «Перенести»",
      "active.heldMany": ["{n} вкладка закрылась вместе с плагином, а агент в ней работает: {names}. Без ответа он завершится через 30 мин.",
                          "{n} вкладки закрылись вместе с плагином, а агенты в них работают: {names}. Без ответа они завершатся через 30 мин.",
                          "{n} вкладок закрылись вместе с плагином, а агенты в них работают: {names}. Без ответа они завершатся через 30 мин."],
      "active.heldBack": "Вернуть вкладку",
      "active.heldBackAll": "Вернуть вкладки",
      "active.heldBackHint": "Вкладки откроются на тех же процессах — агенты не перезапускаются",
      "active.heldEnd": "Завершить",
      "active.heldEndHint": "Завершить агентов; любую сессию можно продолжить потом из «Недавно закрытых»",
      "active.heldEndTitle": "Завершить агентов?",
      "active.heldEndBody": ["Завершится {n} агент без вкладки: {names}. Сессию можно продолжить потом из «Недавно закрытых».",
                             "Завершатся {n} агента без вкладок: {names}. Каждую сессию можно продолжить потом из «Недавно закрытых».",
                             "Завершатся {n} агентов без вкладок: {names}. Каждую сессию можно продолжить потом из «Недавно закрытых»."],
      "active.heldGoHint": "Вкладка закрылась вместе с плагином, агент работает: открыть вкладку на том же процессе",
      "active.move": "Перенести",
      "active.otherTerminal": "другом терминале",
      "active.moveHint": "Сессия идёт в {app}: завершить там и открыть вкладкой здесь",
      "active.moveTitle": "Перенести в Obsidian?",
      "active.moveBody": "«{title}» идёт в {app}. Atlas завершит её там (как Ctrl+C) и продолжит здесь во вкладке терминала. Окно терминала там останется — его можно закрыть.",
      "active.moveBodyBusy": "«{title}» идёт в {app}. Atlas завершит её там (как Ctrl+C; текущий ход прервётся) и продолжит здесь во вкладке терминала. Окно терминала там останется — его можно закрыть.",
      "active.moveEnding": "завершаю сессию там…",
      "active.moveFailed": "не вышло: {msg}",
      "active.moveNoFolder": "Сессия завершена, но рабочей папки нет — открой её из поиска.",
      // filters and grid
      "active.filter.domain": "Домен",
      "active.filter.project": "Проект",
      "active.filter.topic": "Тема",
      "active.filter.period": "Период",
      "active.filterAll": "{label}: все",
      "active.noValues": "нет значений",
      "active.auto": "авто",
      "active.layoutHint": "Сколько карточек на экран: столбцы × ряды",
      "active.layoutAria": "Раскладка карточек",
      "active.cols": ["{n} столбец", "{n} столбца", "{n} столбцов"],
      "active.rows": ["{n} ряд", "{n} ряда", "{n} рядов"],
      "active.hoverAndClick": "наведи и кликни",
      "active.autoFullHint": "По ширине экрана, два ряда",
      "active.autoCompactHint": "4 столбца × 5 рядов",
      "active.find": "найти…",
      "active.allVisible": "все видимые",
      "active.reset": "сбросить",
      "active.viewAria": "Вид карточек",
      "active.modeCompact": "комп.",
      "active.modeCompactHint": "Компактно: много маленьких карточек",
      "active.modeFull": "подр.",
      "active.modeFullHint": "Подробно: ответ агента и поле ответа в карточке",
      // pin and hide
      "active.unpin": "Открепить",
      "active.pinHint": "Закрепить сверху секции",
      "active.hide": "скрыть",
      "active.hideHint": "Убрать с экрана до следующего сообщения в этой сессии",
      "active.hideAria": "Скрыть до следующего сообщения",
    },
  });
})(window);
