// Строки страницы: разметка, общее, поиск, карточка сессии, действия. Ключи — с префиксом «common / search / card / actions.»; en и ru — одинаковый набор ключей.
// Множественное число — массивом: ru [one, few, many], en [one, other]; {n} — само число.
(function (root) {
  const I = typeof module !== "undefined" && module.exports ? require("./i18n.js") : root.I18N;
  I.add({
    en: {
      // --- разметка: вкладки и подписи ---
      "nav.sections": "Sections",
      "nav.search": "Search",
      "nav.active": "Active",
      "nav.stats": "Statistics",
      "nav.helpTitle": "How to use this",
      "nav.help": "Help",
      "common.activeFilters": "Active session filters",
      "common.feed": "Session feed",
      "common.closeFeed": "Close feed",
      "common.statsPeriod": "Statistics period",

      // --- общее ---
      "common.loading": "loading…",
      "common.save": "Save",
      "common.saved": "saved",
      "common.cancel": "Cancel",
      "common.copy": "Copy",
      "common.close": "Close",
      "common.ok": "OK",
      "common.error": "error: {msg}",
      "common.errorTitle": "Error",
      "common.errorWord": "error",
      "common.failed": "failed: {msg}",
      "common.saveFailed": "Could not save: {msg}",
      "common.serverNoAnswer": "Session Atlas server is not responding",
      "common.badResponse": "could not parse the response",
      "common.timeUnknown": "time unknown",
      "common.justNow": "just now",
      "common.minAgo": "{n} min ago",
      "common.hoursAgo": "{n} h ago",
      "common.daysAgo": "{n} d ago",
      "common.serverDown": "Session Atlas server is not responding — showing the last loaded data.",
      "common.raise": "Start",
      "common.raising": "starting…",
      "common.obsidianNoAnswer": "Obsidian did not respond — turn the Session Atlas plugin off and on",
      "common.raiseFailed": "did not start: {reason} — in a terminal: atlas ensure",

      // --- поиск ---
      "search.placeholder": "search prompts…",
      "search.hint": "\"phrase\" — words in a row · -word — exclude · OR — either of two. ⌘K — focus, Esc — clear",
      "search.orderLabel": "Result order",
      "search.orderDate": "newest first",
      "search.orderRelevance": "exact matches first",
      "search.scope": "search everything, not only prompts",
      "search.domain": "Domain",
      "search.project": "Project",
      "search.topic": "Topic",
      "search.period": "Period",
      "search.other": "Other",
      "search.all": "all",
      "search.sinceAll": "all time",
      "search.sinceWeek": "week",
      "search.sinceMonth": "month",
      "search.since3m": "three months",
      "search.automation": "show background runs",
      "search.reindex": "update index",
      "search.reindexing": "updating…",
      "search.classify": "classify",
      "search.autoClassifyLabel": "hourly: new and changed",
      "search.fieldTitle": "title",
      "search.fieldPrompts": "prompts",
      "search.fieldReplies": "replies",
      "search.fieldCommands": "commands",
      "search.fieldFiles": "files",
      "search.fieldTickets": "tickets",
      "search.fieldSummaries": "summaries",
      "search.fieldSubagents": "subagents",
      "search.planLead": "looking for: ",
      "search.planOr": " or ",
      "search.planAnd": " and ",
      "search.planWithout": " · without: ",
      "search.chipSearch": "search",
      "search.chipDomain": "domain",
      "search.chipProject": "project",
      "search.chipTopic": "topic",
      "search.chipPeriod": "period",
      "search.chipView": "view",
      "search.chipWithBackground": "with background runs",
      "search.chipScope": "scope",
      "search.chipWholeIndex": "whole index",
      "search.resetAll": "clear all",
      "search.sessions": ["{n} session", "{n} sessions"],
      "search.shownOf": "showing {shown} of {count}",
      "search.indexing": "index is catching up with new sessions…",
      "search.indexedAt": "index updated {when}",
      "search.elsewhere": ["{n} more session — the word is only in replies, commands or files.",
                           "{n} more sessions — the word is only in replies, commands or files."],
      "search.searchEverywhere": "search everywhere",
      "search.nothingFiltered": "Nothing found — remove some of the filters above the list.",
      "search.nothing": "Nothing found.",
      "search.hits": "matches: {list}",
      "search.sensitive": "sensitive",
      "search.turns": ["{n} turn", "{n} turns"],
      "search.filterReset": "{label} “{value}” is not in the selected domain — filter cleared",
      "search.classifyN": "classify ({n})",
      "search.classifyUpToDate": "classification is up to date",
      "search.classifying": "classifying…",
      "search.classifyingLeft": "classifying… {n} left",
      "search.classifyFailedBtn": "classification failed",
      "search.classifyFailed": "Classification failed",
      "search.classifyTitle": "Classification",
      "search.nothingToClassify": "Nothing to classify.",
      "search.classifySessions": "Classify sessions",
      "search.classifyNote": ["{n} session without a topic. About {chars} characters will be sent to {model}. {note}",
                              "{n} sessions without a topic. About {chars} characters will be sent to {model}. {note}"],
      "search.confirmRun": "Confirm and run",
      "search.autoClassify": "Auto-classification",
      "search.autoNever": "not yet",
      "search.autoOnTitle": "Topic, description line and “What was done” — for new sessions (older than half an hour) "
        + "and for those with new messages since the last pass; up to {max} per pass. Each one is a Claude call "
        + "and uses your subscription quota. Last pass: {last}, next: {next}.",
      "search.autoOffTitle": "Off. When on, every {interval} min the server updates the topic, description line "
        + "and “What was done” for new and changed sessions (up to {max} per pass) — these are Claude calls "
        + "that use your subscription quota.",

      // --- карточка сессии ---
      "card.pick": "Pick a session on the left",
      "delete.menu": "Delete session…",
      "delete.title": "Delete “{title}”?",
      "delete.note": "Deletes the session from this computer for good ({size}): not to the Trash, it cannot be undone. Claude Code will no longer be able to resume it.",
      "delete.confirm": "Delete permanently",
      "delete.running": "This session is running. Stop it or close its tab, then delete.",
      "delete.done": "Session deleted.",
      "delete.kind.transcript": "Transcript",
      "delete.kind.subagents": "Subagents and tool output",
      "delete.kind.file_history": "File edit history",
      "delete.kind.session_env": "Session environment",
      "delete.kind.tasks": "Tasks",
      "delete.kind.todos": "To-do lists",
      "delete.kind.handoff": "Handoffs",
      "delete.files": ["{n} file", "{n} files"],
      "delete.history": ["{n} prompt from the input history (↑)", "{n} prompts from the input history (↑)"],
      "delete.catalog": "Catalog data: search index, topic, summaries, your edits",
      "delete.bytes": "{n} B",
      "delete.kb": "{n} KB",
      "delete.mb": "{n} MB",
      "card.renameTitle": "Rename session",
      "card.renameNote": "The name is also saved in Claude Code itself — in the `claude --resume` list.",
      "card.whereStopped": "Where you left off",
      "card.stateUnreadable": "could not read the state",
      "card.lastPrompt": "last prompt",
      "card.lastAnswer": "last reply",
      "card.compactionSummary": "compaction summary ({n} in total)",
      "card.folder": "Folder",
      "card.branch": "Branch",
      "card.filesEdited": "Files edited",
      "card.commandsRun": "Commands run",
      "card.done": "What was done",
      "card.doneHead": "What was done · {state} · {model}",
      "card.fresh": "up to date",
      "card.stale": "outdated",
      "card.shortByClassifier": "Short description from the classifier. The detailed one is in the “…” menu.",
      "card.shortByClassifierConf": "Short description from the classifier, confidence {c}. The detailed one is in the “…” menu.",
      "card.noSummary": "No description yet — a model builds it from the “…” menu.",
      "card.did": "Worked on",
      "card.result": "Result",
      "card.open": "Left to do",
      "card.outcome": "Outcome",
      "card.classification": "Classification",
      "card.topicNone": "not determined",
      "card.topicStaleSuffix": " · outdated",
      "card.domainNone": "not determined",
      "card.confidence": "Confidence",
      "card.sensitivity": "Sensitivity",
      "card.lowConfidence": "Low confidence — worth checking and fixing by hand.",
      "card.domainKeep": "keep domain",
      "card.topicPlaceholder": "topic",
      "card.sensKeep": "keep sensitivity",
      "card.manualNote": "Manual changes are never overwritten by a rule or the model.",
      "card.resume": "Resume",
      "card.newFromThis": "New from this one",
      "card.moreActions": "more actions",
      "card.handoffOnly": "Handoff without launching",
      "card.detailedSummary": "Detailed description",
      "card.exactFork": "Exact context fork",
      "card.dblclickRename": "double-click to rename",
      "card.subUpdated": "{kind} · updated {when}",
      "card.manualName": " · name set manually",
      "card.rename": "rename",
      "card.editedFiles": "Edited files ({n})",
      "card.links": "Links",
      "card.userPrompts": "User prompts",
      "card.metadata": "Metadata",
      "card.id": "ID",
      "card.projects": "Projects",
      "card.turns": "Turns human/machine/subagents",
      "card.apiCost": "Estimated API cost",
      "card.costNone": "not recorded",
      "card.tickets": "Tickets",
      "card.renamedInCatalog": "Renamed in the catalog",

      // --- действия ---
      "actions.noCwd": "The session's working folder no longer exists — there is nothing to build the command from.",
      "actions.forkNote": "An exact fork carries the whole context without compression. ",
      "actions.openingTab": "opening a terminal tab in Obsidian…",
      "actions.resumeSession": "Resume session",
      "actions.openInObsidian": "Open as a tab in Obsidian",
      "actions.openInTerminal": "Open in terminal",
      "actions.localModel": "a local model",
      "actions.externalModel": "the external model {model}",
      "actions.previewNote": "{chars} characters (~{mb} MB, about {k}k tokens) will be sent to {where}. "
        + "Contents — {parts}. Sensitivity: {sensitivity}.",
      "actions.truncated": " Part of the material did not fit the budget — the end of the session was taken.",
      "actions.fullPath": " Full text for checking: {path}",
      "actions.handoffPreview": "Handoff — what will be sent",
      "actions.summaryPreview": "Description — what will be sent",
      "actions.confirmSend": "Confirm and send",
      "actions.modelWorking": "the model is working…",
      "actions.handoffReady": "Handoff is ready",
      "actions.summaryReady": "Description is ready",
      "actions.file": "File: {path}",
      "actions.cancelled": "cancelled",
      "actions.tooLong": "taking too long — check the card later",
      "actions.readable": "Worked on: {did}\n\nResult: {result}\n\nLeft to do: {open}\n\nOutcome: {outcome}",
      "actions.noCwdLaunch": "(no working folder — start it manually)\n{path}",
      "actions.newFromThisTitle": "New session from this one",
      "actions.compressed": "Compression is done.",
      "actions.compressedCopy": "Compression is done. Copy the command — the new session will read the handoff first.",
      "actions.newTabTitle": "new from {id}",
      "actions.nsTitle": "New session",
      "actions.nsDir": "Folder",
      "actions.nsPrompt": "First prompt",
      "actions.nsPlaceholder": "What should it do? Can be left empty. ⌘Enter — start",
      "actions.nsGo": "Start",
      "actions.nsCopy": "Copy command",

      // --- справка ---
      "help.gotIt": "Got it",
      "help.whatH": "What this is",
      "help.whatP": "A list of all your conversations with Claude Code. It reads the files Claude Code itself "
        + "writes to disk and changes nothing in them. Use it to find an old conversation and continue "
        + "it without retelling everything.",
      "help.findH": "Finding what you need",
      "help.find1": "Search looks through your messages. ⌘K — cursor to search, Esc — clear.",
      "help.find2": "Under the search box you see how the query was understood. Numbers and tickets are "
        + "matched exactly: “1359” will not find “13”. Ordinary words match in any form.",
      "help.find3": "Words in quotes match in a row, as written. A minus before a word excludes it: "
        + "“figma -mercedes”. “OR” between words matches either of them.",
      "help.find4": "Newest are on top by default. “Exact matches first” lifts sessions where the word is in "
        + "the title or the words stand close together.",
      "help.find5": "If the word was found only in Claude's replies or in commands, “search everywhere” "
        + "appears above the list.",
      "help.find6": "A domain checkbox narrows the list: work, personal, own projects. Projects and topics adjust.",
      "help.find7": "Above the list you see which filters are on. The cross removes one, “clear all” removes all at once.",
      "help.find8": "Background runs (hooks, the nightly agent) are hidden — there are hundreds of them, and "
        + "they are not your conversations.",
      "help.activeH": "The “Active” tab",
      "help.active1": "All Claude Code sessions running right now, except background runs. The one with the "
        + "freshest message is on top; updates every 5 seconds.",
      "help.active2": "On top — “Waiting for you”, below — “Working”. “● working” — the agent is doing "
        + "something; “working in background” (dashed border) — the turn is over, but a background command, "
        + "subagent or /loop will wake the session; “needs your decision” — a question or a permission "
        + "request is open; “○ waiting” — done and waiting for you. The goal label means a /goal "
        + "is active.",
      "help.active3": "“detailed” — each card shows the end of Claude's last reply (1000 characters, “show "
        + "all” expands it) and a reply box. Enter — send, Shift+Enter — new line. The text is typed into "
        + "the terminal tab as if you typed it; while the agent is working it gets queued.",
      "help.active4": "The grid button next to the filters sets how many cards fit on screen: move the mouse "
        + "over the cells and click: up to 5 × 5 in compact view, up to 4 × 4 in detailed view. Each view "
        + "has its own layout; “auto” is the default.",
      "help.active5": "Claude's reply is shown with Markdown formatting: headings, lists, tables, code, links.",
      "help.active6": "After sending, the card shows your message until Claude answers it.",
      "help.active7": "An image can be pasted into the reply box (⌘V), dropped onto it or picked with the "
        + "paperclip — it reaches the session as an [Image #N] attachment, just like from the terminal.",
      "help.active8": "If a dialog is open (a question with options, a permission for a command), sending is "
        + "blocked: Enter there would pick an option. Answer in the tab — the “Go” button.",
      "help.active9": "The filters on top are checkbox lists: you can tick several domains, projects, topics "
        + "and periods at once. The number on the right is how many sessions a value gives with the other filters.",
      "help.active10": "“message N min ago” is your last message or Claude's last text reply. Tool calls and "
        + "subagent notifications do not count.",
      "help.active11": "“Go” opens the Obsidian terminal tab where the session runs. “Close” closes it "
        + "after confirmation — the session in it will end.",
      "help.active12": "Buttons are inactive if the catalog is open in a browser or the session was not "
        + "started in an Obsidian tab.",
      "help.active13": "Budget is the amount Claude Code recorded at the last exit from the session, with its "
        + "date. Spending after that is not included.",
      "help.active14": "Clicking the title opens the session card in the “Search” tab.",
      "help.cardH": "Session card",
      "help.card1": "“Where you left off” — the last thing you asked and what Claude answered. Ready at once, "
        + "without a model.",
      "help.card2": "Below — edited files, MR links, topic and domain. Topic and domain can be fixed by hand, "
        + "and nothing will overwrite that fix.",
      "help.card3": "Double-click the title to rename. The name changes in Claude Code itself too.",
      "help.whichH": "Which button to press",
      "help.whichResume": "Continue exactly the same conversation with its whole history. Good when it is "
        + "short and fresh.",
      "help.whichNew": "The conversation is long and tangled. Claude compresses it into a note and starts "
        + "from a clean slate, but remembers everything important.",
      "help.whichHandoffBtn": "… → Handoff",
      "help.whichHandoff": "The same note, but without launching. To read yourself or pass on.",
      "help.whichSummaryBtn": "… → Description",
      "help.whichSummary": "In detail, how the conversation ended. When you don't remember the outcome.",
      "help.whichForkBtn": "… → Exact fork",
      "help.whichFork": "A full copy of the conversation, without compression. Rarely: you need the same "
        + "history but don't want to touch the original.",
      "help.bottomH": "Buttons at the bottom left",
      "help.bottom1": "“update index” — if you just closed a session and it is not in the list yet.",
      "help.bottom2": "“classify” — set topic and domain for new sessions.",
      "help.outH": "What gets sent out",
      "help.outP": "Nothing until you press a button that calls a model. Before each such send you see the "
        + "size and the text itself. Sessions marked as sensitive are never sent out.",
    },
    ru: {
      // --- разметка: вкладки и подписи ---
      "nav.sections": "Разделы",
      "nav.search": "Поиск",
      "nav.active": "Активные",
      "nav.stats": "Статистика",
      "nav.helpTitle": "Как этим пользоваться",
      "nav.help": "Справка",
      "common.activeFilters": "Фильтры активных сессий",
      "common.feed": "Лента сессии",
      "common.closeFeed": "Закрыть ленту",
      "common.statsPeriod": "Период статистики",

      // --- общее ---
      "common.loading": "загрузка…",
      "common.save": "Сохранить",
      "common.saved": "сохранено",
      "common.cancel": "Отмена",
      "common.copy": "Копировать",
      "common.close": "Закрыть",
      "common.ok": "Ок",
      "common.error": "ошибка: {msg}",
      "common.errorTitle": "Ошибка",
      "common.errorWord": "ошибка",
      "common.failed": "не вышло: {msg}",
      "common.saveFailed": "Не удалось сохранить: {msg}",
      "common.serverNoAnswer": "сервер Session Atlas не отвечает",
      "common.badResponse": "ответ не разобрался",
      "common.timeUnknown": "время неизвестно",
      "common.justNow": "только что",
      "common.minAgo": "{n} мин назад",
      "common.hoursAgo": "{n} ч назад",
      "common.daysAgo": "{n} дн назад",
      "common.serverDown": "Сервер Session Atlas не отвечает — на экране последние данные.",
      "common.raise": "Поднять",
      "common.raising": "поднимаю…",
      "common.obsidianNoAnswer": "Obsidian не ответил — выключи и включи плагин Session Atlas",
      "common.raiseFailed": "не поднялся: {reason} — в терминале: atlas ensure",

      // --- поиск ---
      "search.placeholder": "поиск по запросам…",
      "search.hint": "\"фраза\" — слова подряд · -слово — исключить · ИЛИ — любое из двух. ⌘K — фокус, Esc — очистить",
      "search.orderLabel": "Порядок выдачи",
      "search.orderDate": "сначала свежие",
      "search.orderRelevance": "сначала точные совпадения",
      "search.scope": "искать по всему, не только по запросам",
      "search.domain": "Домен",
      "search.project": "Проект",
      "search.topic": "Тема",
      "search.period": "Период",
      "search.other": "Прочее",
      "search.all": "все",
      "search.sinceAll": "всё время",
      "search.sinceWeek": "неделя",
      "search.sinceMonth": "месяц",
      "search.since3m": "три месяца",
      "search.automation": "показывать фоновые прогоны",
      "search.reindex": "обновить индекс",
      "search.reindexing": "обновляю…",
      "search.classify": "классифицировать",
      "search.autoClassifyLabel": "раз в час: новые и изменённые",
      "search.fieldTitle": "заголовок",
      "search.fieldPrompts": "запросы",
      "search.fieldReplies": "ответы",
      "search.fieldCommands": "команды",
      "search.fieldFiles": "файлы",
      "search.fieldTickets": "тикеты",
      "search.fieldSummaries": "сводки",
      "search.fieldSubagents": "сабагенты",
      "search.planLead": "ищу: ",
      "search.planOr": " или ",
      "search.planAnd": " и ",
      "search.planWithout": " · без: ",
      "search.chipSearch": "поиск",
      "search.chipDomain": "домен",
      "search.chipProject": "проект",
      "search.chipTopic": "тема",
      "search.chipPeriod": "период",
      "search.chipView": "вид",
      "search.chipWithBackground": "с фоновыми",
      "search.chipScope": "область",
      "search.chipWholeIndex": "весь индекс",
      "search.resetAll": "сбросить всё",
      "search.sessions": ["{n} сессия", "{n} сессии", "{n} сессий"],
      "search.shownOf": "показаны {shown} из {count}",
      "search.indexing": "индекс догоняет новые сессии…",
      "search.indexedAt": "индекс от {when}",
      "search.elsewhere": ["Ещё {n} сессия — слово есть только в ответах, командах или файлах.",
                           "Ещё {n} сессии — слово есть только в ответах, командах или файлах.",
                           "Ещё {n} сессий — слово есть только в ответах, командах или файлах."],
      "search.searchEverywhere": "искать везде",
      "search.nothingFiltered": "Ничего не нашлось — сними часть фильтров наверху списка.",
      "search.nothing": "Ничего не нашлось.",
      "search.hits": "совпадений: {list}",
      "search.sensitive": "чувствительная",
      "search.turns": ["{n} ход", "{n} хода", "{n} ходов"],
      "search.filterReset": "{label} «{value}» не входит в выбранный домен — фильтр снят",
      "search.classifyN": "классифицировать ({n})",
      "search.classifyUpToDate": "классификация актуальна",
      "search.classifying": "классифицирую…",
      "search.classifyingLeft": "классифицирую… осталось {n}",
      "search.classifyFailedBtn": "классификация не вышла",
      "search.classifyFailed": "Классификация не вышла",
      "search.classifyTitle": "Классификация",
      "search.nothingToClassify": "Нечего классифицировать.",
      "search.classifySessions": "Классифицировать сессии",
      "search.classifyNote": ["{n} сессия без темы. Наружу уйдёт примерно {chars} символов в {model}. {note}",
                              "{n} сессии без темы. Наружу уйдёт примерно {chars} символов в {model}. {note}",
                              "{n} сессий без темы. Наружу уйдёт примерно {chars} символов в {model}. {note}"],
      "search.confirmRun": "Подтвердить и запустить",
      "search.autoClassify": "Автоклассификация",
      "search.autoNever": "ещё не было",
      "search.autoOnTitle": "Тема, строка описания и «Что сделано» — у новых сессий (старше получаса) и у тех, где с "
        + "прошлого прохода были новые реплики; до {max} за раз. Каждая — вызов Claude, "
        + "расходует квоту подписки. Прошлый проход: {last}, следующий: {next}.",
      "search.autoOffTitle": "Выключено. Если включить, раз в {interval} мин сервер обновит тему, строку "
        + "описания и «Что сделано» у новых и изменившихся сессий (до {max} за раз) — "
        + "это вызовы Claude за счёт квоты подписки.",

      // --- карточка сессии ---
      "card.pick": "Выбери сессию слева",
      "delete.menu": "Удалить сессию…",
      "delete.title": "Удалить «{title}»?",
      "delete.note": "Сессия удаляется с компьютера насовсем ({size}): не в Корзину, отменить нельзя. Claude Code больше не сможет её восстановить.",
      "delete.confirm": "Удалить навсегда",
      "delete.running": "Сессия запущена. Останови её или закрой вкладку, потом удаляй.",
      "delete.done": "Сессия удалена.",
      "delete.kind.transcript": "Транскрипт",
      "delete.kind.subagents": "Субагенты и вывод инструментов",
      "delete.kind.file_history": "История правок файлов",
      "delete.kind.session_env": "Окружение сессии",
      "delete.kind.tasks": "Задачи",
      "delete.kind.todos": "Списки дел",
      "delete.kind.handoff": "Хендоффы",
      "delete.files": ["{n} файл", "{n} файла", "{n} файлов"],
      "delete.history": ["{n} запрос из истории ввода (↑)", "{n} запроса из истории ввода (↑)", "{n} запросов из истории ввода (↑)"],
      "delete.catalog": "Данные каталога: поисковый индекс, тема, описания, твои правки",
      "delete.bytes": "{n} Б",
      "delete.kb": "{n} КБ",
      "delete.mb": "{n} МБ",
      "card.renameTitle": "Переименовать сессию",
      "card.renameNote": "Имя сохранится и в самом Claude Code — в списке `claude --resume`.",
      "card.whereStopped": "Где остановились",
      "card.stateUnreadable": "состояние не прочиталось",
      "card.lastPrompt": "последний запрос",
      "card.lastAnswer": "последний ответ",
      "card.compactionSummary": "сводка компактации (всего {n})",
      "card.folder": "Папка",
      "card.branch": "Ветка",
      "card.filesEdited": "Правлено файлов",
      "card.commandsRun": "Команд выполнено",
      "card.done": "Что сделано",
      "card.doneHead": "Что сделано · {state} · {model}",
      "card.fresh": "актуально",
      "card.stale": "устарело",
      "card.shortByClassifier": "Короткое описание от классификатора. Развёрнутое — в меню «…».",
      "card.shortByClassifierConf": "Короткое описание от классификатора, уверенность {c}. Развёрнутое — в меню «…».",
      "card.noSummary": "Описания ещё нет — оно строится моделью из меню «…».",
      "card.did": "Делалось",
      "card.result": "Результат",
      "card.open": "Осталось",
      "card.outcome": "Исход",
      "card.classification": "Классификация",
      "card.topicNone": "не определена",
      "card.topicStaleSuffix": " · устарела",
      "card.domainNone": "не определён",
      "card.confidence": "Уверенность",
      "card.sensitivity": "Чувствительность",
      "card.lowConfidence": "Низкая уверенность — стоит проверить и поправить руками.",
      "card.domainKeep": "домен как есть",
      "card.topicPlaceholder": "тема",
      "card.sensKeep": "чувствительность как есть",
      "card.manualNote": "Сохранённое вручную не перезапишет ни правило, ни модель.",
      "card.resume": "Восстановить",
      "card.newFromThis": "Новая на основе этой",
      "card.moreActions": "ещё действия",
      "card.handoffOnly": "Хендофф без запуска",
      "card.detailedSummary": "Развёрнутое описание",
      "card.exactFork": "Точный форк контекста",
      "card.dblclickRename": "двойной клик — переименовать",
      "card.subUpdated": "{kind} · обновлена {when}",
      "card.manualName": " · имя задано вручную",
      "card.rename": "переименовать",
      "card.editedFiles": "Правленые файлы ({n})",
      "card.links": "Ссылки",
      "card.userPrompts": "Запросы пользователя",
      "card.metadata": "Метаданные",
      "card.id": "Идентификатор",
      "card.projects": "Проекты",
      "card.turns": "Ходов человек/машина/сабагенты",
      "card.apiCost": "Оценка стоимости API",
      "card.costNone": "не записана",
      "card.tickets": "Тикеты",
      "card.renamedInCatalog": "Переименовано в каталоге",

      // --- действия ---
      "actions.noCwd": "Рабочая папка сессии не существует — команду собрать не из чего.",
      "actions.forkNote": "Точный форк тащит весь контекст без сжатия. ",
      "actions.openingTab": "открываю вкладку терминала в Obsidian…",
      "actions.resumeSession": "Восстановить сессию",
      "actions.openInObsidian": "Открыть вкладкой в Obsidian",
      "actions.openInTerminal": "Открыть в терминале",
      "actions.localModel": "локальную модель",
      "actions.externalModel": "внешнюю модель {model}",
      "actions.previewNote": "Наружу уйдёт {chars} символов (~{mb} МБ, примерно {k}k токенов) в {where}. "
        + "Состав — {parts}. Чувствительность: {sensitivity}.",
      "actions.truncated": " Часть материала не влезла в бюджет — взят хвост сессии.",
      "actions.fullPath": " Полный текст для сверки: {path}",
      "actions.handoffPreview": "Хендофф — что уйдёт наружу",
      "actions.summaryPreview": "Описание — что уйдёт наружу",
      "actions.confirmSend": "Подтвердить и отправить",
      "actions.modelWorking": "модель работает…",
      "actions.handoffReady": "Хендофф готов",
      "actions.summaryReady": "Описание готово",
      "actions.file": "Файл: {path}",
      "actions.cancelled": "отменено",
      "actions.tooLong": "слишком долго — загляни в карточку позже",
      "actions.readable": "Делалось: {did}\n\nРезультат: {result}\n\nОсталось: {open}\n\nИсход: {outcome}",
      "actions.noCwdLaunch": "(нет рабочей папки — запусти вручную)\n{path}",
      "actions.newFromThisTitle": "Новая сессия на основе этой",
      "actions.compressed": "Сжатие готово.",
      "actions.compressedCopy": "Сжатие готово. Скопируй команду — новая сессия первым делом прочитает хендофф.",
      "actions.newTabTitle": "новая на основе {id}",
      "actions.nsTitle": "Новая сессия",
      "actions.nsDir": "Папка",
      "actions.nsPrompt": "Первый запрос",
      "actions.nsPlaceholder": "Что сделать? Можно оставить пустым. ⌘Enter — запустить",
      "actions.nsGo": "Запустить",
      "actions.nsCopy": "Копировать команду",

      // --- справка ---
      "help.gotIt": "Понятно",
      "help.whatH": "Что это",
      "help.whatP": "Список всех твоих разговоров с Claude Code. Он читает файлы, которые Claude Code сам "
        + "пишет на диск, и ничего в них не меняет. Нужен, чтобы найти старый разговор и "
        + "продолжить его — не пересказывая всё заново.",
      "help.findH": "Как найти нужное",
      "help.find1": "Поиск ищет по твоим сообщениям. ⌘K — курсор в поиск, Esc — очистить.",
      "help.find2": "Под строкой поиска написано, как понят запрос. Числа и тикеты ищутся точно: «1359» не "
        + "найдёт «13». Обычные слова — в любой форме: «модели» найдёт «моделей».",
      "help.find3": "Слова в кавычках — подряд, как написано. Минус перед словом — исключить: «figma -mercedes». "
        + "«ИЛИ» между словами — любое из них.",
      "help.find4": "По умолчанию сверху свежие. «Сначала точные совпадения» поднимет сессии, где слово в "
        + "заголовке или слова стоят рядом.",
      "help.find5": "Если слово нашлось только в ответах Claude или командах, над списком появится «искать везде».",
      "help.find6": "Галочка домена сужает список: работа, личное, свои проекты. Проекты и темы подстраиваются.",
      "help.find7": "Над списком видно, какие фильтры стоят сейчас. Крестик снимает один, «сбросить всё» — сразу все.",
      "help.find8": "Фоновые прогоны (хуки, ночной агент) спрятаны — их сотни, и это не твои разговоры.",
      "help.activeH": "Вкладка «Активные»",
      "help.active1": "Все запущенные сейчас сессии Claude Code, кроме фоновых прогонов. Сверху — с самым свежим "
        + "сообщением, обновляется каждые 5 секунд.",
      "help.active2": "Сверху — «Ждут тебя», снизу — «Работают». «● работает» — агент что-то делает; "
        + "«работает в фоне» (пунктирная рамка) — ход закончен, но сессию разбудит фоновая команда, "
        + "сабагент или /loop; «нужно твоё решение» — открыт вопрос или запрос разрешения; "
        + "«○ ждёт ответа» — закончил и ждёт тебя. Метка goal — активна цель /goal.",
      "help.active3": "«Подробно» — в каждой карточке конец последнего ответа Claude (1000 символов, «показать "
        + "целиком» раскрывает весь) и поле ответа. Enter — отправить, Shift+Enter — перенос строки. "
        + "Текст печатается во вкладку терминала, как будто набран тобой; пока агент работает — "
        + "встанет в очередь.",
      "help.active4": "Кнопка с сеткой рядом с фильтрами — сколько карточек на экран: веди мышью по клеткам "
        + "и кликни: в компактном виде до 5 × 5, в подробном до 4 × 4. У каждого вида своя "
        + "раскладка; «авто» — как по умолчанию.",
      "help.active5": "Ответ Claude показан с разметкой Markdown: заголовки, списки, таблицы, код, ссылки.",
      "help.active6": "После отправки в карточке видно твоё сообщение — пока Claude на него не ответит.",
      "help.active7": "Картинку можно вставить в поле ответа (⌘V), перетащить в него или выбрать скрепкой — "
        + "в сессию она придёт вложением [Image #N], как из терминала.",
      "help.active8": "Если открыт диалог (вопрос с вариантами, разрешение на команду), отправка заблокирована: "
        + "Enter там выбрал бы вариант. Ответь во вкладке — кнопка «Перейти».",
      "help.active9": "Фильтры сверху — списки с галочками: можно отметить несколько доменов, проектов, тем и "
        + "периодов сразу. Число справа — сколько сессий даст значение при остальных фильтрах.",
      "help.active10": "«Сообщение N мин назад» — твоя последняя реплика или последний текстовый ответ Claude. "
        + "Вызовы инструментов и уведомления сабагентов не считаются.",
      "help.active11": "«Перейти» открывает вкладку терминала в Obsidian, где идёт сессия. «Закрыть» закрывает её "
        + "после подтверждения — сессия в ней завершится.",
      "help.active12": "Кнопки неактивны, если каталог открыт в браузере или сессия запущена не во вкладке Obsidian.",
      "help.active13": "Бюджет — сумма, которую Claude Code записал при последнем выходе из сессии, с датой. "
        + "Траты после этого в неё не входят.",
      "help.active14": "Клик по заголовку открывает карточку сессии во вкладке «Поиск».",
      "help.cardH": "Карточка сессии",
      "help.card1": "«Где остановились» — последнее, что ты просил, и что Claude ответил. Готово сразу, без модели.",
      "help.card2": "Ниже — правленые файлы, ссылки на MR, тема и домен. Тему и домен можно поправить руками, "
        + "и правка больше ничем не перезапишется.",
      "help.card3": "Двойной клик по заголовку — переименовать. Имя поменяется и в самом Claude Code.",
      "help.whichH": "Какую кнопку нажимать",
      "help.whichResume": "Продолжить ровно тот же разговор со всей историей. Годится, когда он "
        + "короткий и свежий.",
      "help.whichNew": "Разговор длинный и запутанный. Claude сожмёт его в записку и "
        + "начнёт с чистого листа, но помня всё важное.",
      "help.whichHandoffBtn": "… → Хендофф",
      "help.whichHandoff": "Та же записка, но без запуска. Чтобы прочитать самому или передать.",
      "help.whichSummaryBtn": "… → Описание",
      "help.whichSummary": "Подробно, чем кончился разговор. Когда не помнишь итога.",
      "help.whichForkBtn": "… → Точный форк",
      "help.whichFork": "Копия разговора целиком, без сжатия. Редко: нужна та же история, "
        + "но не хочется трогать оригинал.",
      "help.bottomH": "Кнопки внизу слева",
      "help.bottom1": "«обновить индекс» — если только что закрыл сессию, а её ещё нет в списке.",
      "help.bottom2": "«классифицировать» — проставить тему и домен новым сессиям.",
      "help.outH": "Что уходит наружу",
      "help.outP": "Ничего, пока не нажмёшь кнопку, которая зовёт модель. Перед каждой такой отправкой "
        + "показывают объём и сам текст. Сессии, помеченные чувствительными, наружу не идут вовсе.",
    },
  });
})(typeof window !== "undefined" ? window : globalThis);
