"""Мутационная проверка тестов: ломаем поведение и убеждаемся, что тест краснеет.

    python3.11 tools/mutations.py
"""
import subprocess, shutil, sys, os, time
MUT = [
 ("delete: запущенная сессия удаляется", "atlas/delete.py",
  '    if plan["running"]:\n        raise DeleteError(msg("delete.running"))\n', ""),
 ("delete: из истории ввода уходят чужие строки", "atlas/delete.py",
  "not (session_id in line and _line_sid(line) == session_id)", "not (session_id in line)"),
 ("delete: удаление за пределами папки Claude Code", "atlas/delete.py",
  '            raise DeleteError(msg("delete.outside", path=item["path"]))', "            pass"),
 ("llm: модель зовётся при выключенных ИИ-функциях", "atlas/runner.py",
  "    require_llm()                  # последний рубеж", "    pass                           # последний рубеж"),
 ("llm: маршруты модели открыты при выключенных", "atlas/server.py",
  "                runner.require_llm()\n", "                pass\n"),
 ("llm: расписание работает при выключенных", "atlas/autoclassify.py",
  "or not runner.llm_enabled() ", ""),
 ("llm: выключить автоклассификацию нельзя", "atlas/server.py",
  'and body.get("enabled") is False', "and False"),
 ("config: вложенные ключи пользователя теряются", "atlas/config.py",
  "out[key] = dict(base[key], **value)", "out[key] = {k: v for k, v in value.items() if k in base[key]}"),
 ("config: смена настроек не пересобирает индекс", "atlas/index.py",
  'if db.get_meta(conn, "config_fingerprint") != fingerprint:', "if False:"),
 ("config: без префиксов тикеты ищутся всё равно", "atlas/config.py",
  "    if not valid:\n        return None", "    if not valid:\n        return re.compile(r\"\\b[A-Z]+-\\d{2,}\\b\")"),
 ("prompts: домены не из настроек", "atlas/prompts.py",
  '.replace("{domain_ids}", safe(ids))', '.replace("{domain_ids}", "work")'),
 ("runner: 1M без настройки", "atlas/runner.py",
  'if config.get("force_1m") and not has_1m_window(model):', "if not has_1m_window(model):"),
 ("resolve: vault из кода, не из настроек", "atlas/resolve.py",
  "    for vault, vault_id in config.vaults():\n        if _under(p, vault):", "    for vault, vault_id in [(os.path.join(HOME, \"Notes\"), \"vault\")]:\n        if _under(p, vault):"),
 ("script: старт важнее реестра", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'elif [[ -z "$session_id" && "$SEED_MODE" == resume* ]]', 'elif [[ "$SEED_MODE" == resume* ]]'),
 ("script: форк без --fork-session", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'claude "${flags[@]}" --resume "$SEED_ID" --fork-session', 'claude "${flags[@]}" --resume "$SEED_ID"'),
 ("script: хук не передаётся", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  '--settings "$(hook_settings)")', ')'),
 ("script: новая сессия не записана в реестр", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'upsert_resume_id claude "$instance" "$SEED_ID"\n    print "Starting', 'print "Starting'),
 ("script: транскрипт ищется только в папке vault", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'local -a found=("$CLAUDE_PROJECTS_DIR"/*/"$session_id".jsonl(N))',
  'local -a found=("$CLAUDE_PROJECTS_DIR/$(claude_project_slug)/$session_id".jsonl(N))'),
 ("install: скрипты не ставятся", "tools/install_plugin.py",
  '        shutil.copy(os.path.join(PLUGIN_DIR, "scripts", name), dest)\n', '        pass\n'),
 ("steps: ошибка вызова не видна", "atlas/steps.py",
  'if block.get("is_error"):', 'if False:'),
 ("steps: чтения не сливаются", "atlas/steps.py",
  'and ev["status"] == "ok" and prev["status"] == "ok"):', 'and False):'),
 ("steps: ответ повторяется шагом", "atlas/steps.py",
  'if reply and events and events[-1]["kind"] == "text":', 'if False:'),
 ("steps: в длинном ходе — первые шаги", "atlas/steps.py",
  'return {"events": merged[hidden:], "earlier": hidden,', 'return {"events": merged[:MAX_EVENTS], "earlier": hidden,'),
 ("steps: результат не привязан к вызову", "atlas/feed.py",
  '            turn["collector"].result(rec, content)\n', ''),
 ("touched: сабагенты не считаются", "atlas/touched.py",
  'sources = [main] + [_scan(p)[0] for p in', 'sources = [main] + [] and [_scan(p)[0] for p in'),
 ("touched: строки правки — весь текст", "atlas/touched.py",
  'if len(a) + len(b) > MAX_DIFF_LINES:', 'if True:'),
 ("touched: хвост читается заново целиком", "atlas/touched.py",
  'if cached and cached[0] == st.st_ino and cached[1] <= st.st_size:', 'if False:'),
 ("touched: переписанный файл дочитывается", "atlas/touched.py",
  'and cached[1] <= st.st_size:', ':'),
 ("closed: живые тоже в закрытых", "atlas/active.py",
  'if r["session_id"] not in live_ids][:limit]', '][:limit]'),
 ("closed: фоновые прогоны в закрытых", "atlas/active.py",
  "WHERE s.session_kind = 'interactive' AND s.last_activity_at >= ?", "WHERE s.last_activity_at >= ?"),
 ("closed: без окна по времени", "atlas/active.py",
  "AND s.last_activity_at >= ?\n            ORDER BY", "AND ? IS NOT NULL\n            ORDER BY"),
 ("tasks: удалённые считать", "atlas/tasks.py",
  'if not isinstance(task, dict) or task.get("status") == "deleted":', 'if not isinstance(task, dict):'),
 ("tasks: порядок по имени файла, а не номеру", "atlas/tasks.py",
  '"*.json")), key=_number):', '"*.json"))):'),
 ("tasks: без activeForm — пусто", "atlas/tasks.py",
  't["active_form"] or t["subject"] for t in items', 't["active_form"] for t in items'),
 ("stats: не схлопывать копии ответа", "atlas/stats.py",
  "   GROUP BY a.key)", "   GROUP BY a.key, a.session_id, a.ts)"),
 ("stats: паузы тоже работа", "atlas/activity.py",
  "return gap if gap <= IDLE_SECONDS else 0.0", "return gap"),
 ("stats: время сабагентов в работе", "atlas/activity.py",
  "0.0 if sub else r[\"active_s\"]", "r[\"active_s\"]"),
 ("stats: промежуток не отдаётся ответу", "atlas/activity.py",
  "    row[\"active_s\"] += facts.pending_active\n", ""),
 ("stats: дочитанный ответ перезаписывает время", "atlas/activity.py",
  "active_s = active_s + excluded.active_s", "active_s = excluded.active_s"),
 ("stats: параллельные сессии не сливать", "atlas/stats.py",
  "if cur_end is None or start > cur_end:", "if True:"),
 ("stats: MCP по вызову", "atlas/stats.py",
  "return \"tools\", \"MCP \" + name.split(\"__\")[1]", "return \"tools\", name"),
 ("stats: скилл без имени", "atlas/activity.py",
  "name = \"Skill:\" + str(args[\"skill\"])", "pass"),
 ("stats: слэш-команда не видна", "atlas/activity.py",
  "\"tools\": _command(rec)}", "\"tools\": []}"),
 ("stats: период без начала", "atlas/stats.py",
  "WHERE a.ts >= :since AND", "WHERE 1 AND"),
 ("parse: индексировать tool_result", "atlas/parse.py",
  'if block.get("type") != _TEXT_BLOCK:\n            continue  # tool_result / image / document — никогда не в индекс',
  'if False:\n            continue'),
 ("parse: сводку компактации считать промптом", "atlas/parse.py",
  'if text.startswith(COMPACT_PREFIX):', 'if False:'),
 ("parse: читать и недописанную строку", "atlas/parse.py",
  'if not raw.endswith(b"\\n"):\n            break', 'if False:\n            break'),
 ("index: считать файл неизменившимся всегда", "atlas/index.py",
  'return row is None or row["sig"] != sig', 'return row is None'),
 ("index: игнорировать сабагентов в подписи", "atlas/index.py",
  'for path in [session_path] + subagents:', 'for path in [session_path]:'),
 ("query: стеммить идентификаторы и числа", "atlas/query.py",
  'if IDENTIFIER_RE.search(word):\n        return "exact"', 'if False:\n        return "exact"'),
 ("resolve: файл в корне ~/Code снова проект", "atlas/resolve.py",
  'if rel_to_prefix == name and (name.startswith(".") or os.path.splitext(name)[1]):',
  'if False:'),
 ("resolve: claude-desktop в automation", "atlas/resolve.py",
  'if entrypoint in HEADLESS_ENTRYPOINTS:', 'if entrypoint and entrypoint != "cli":'),
 ("search: показывать automation по умолчанию", "atlas/search.py",
  'if not include_automation and not kinds:\n        where.append("s.session_kind = \'interactive\'")',
  'if False:\n        where.append("s.session_kind = \'interactive\'")'),
 ("index: не чистить старые строки перед записью", "atlas/store.py",
  '    purge(conn, session_id)\n    title = _write_meta(', '    title = _write_meta('),
 ("index: дочитывание без чистки метаданных", "atlas/store.py",
  '    purge(conn, session_id, keep_text=True)\n', ''),
 ("index: дочитывание не переписывает последний ход", "atlas/store.py",
  'conn.execute("DELETE FROM fts WHERE session_id=? AND turn>=?", (session_id, first))', 'pass'),
 ("index: дочитывать после переписанного файла", "atlas/store.py",
  'or row["sub_sig"] != sub_sig or tail_sig(path, row["offset"]) != row["tail_sig"]:',
  'or row["sub_sig"] != sub_sig:'),
 ("index: не удалять исчезнувшие источники", "atlas/index.py",
  'if path not in present:', 'if False:'),
 ("db: rebuild сносит и ручные правки", "atlas/db.py",
  'DERIVED = (', 'DERIVED = ("user_overrides",\n'),
 ("resolve: скретчпад становится проектом", "atlas/resolve.py",
  'if SCRATCHPAD_RE.match(p):', 'if False:'),
 ("resolve: чувствительность по умолчанию normal", "atlas/resolve.py",
  'return UNCLASSIFIED', 'return "normal"'),
 ("resolve: сравнение путей через startswith", "atlas/resolve.py",
  'return os.path.commonpath([os.path.normpath(path), root]) == root',
  'return os.path.normpath(path).startswith(root)'),
 ("query: без усечения до основы", "atlas/query.py",
  'return token[: max(STEM_FLOOR, n - cut)]', 'return token'),
 ("query: резать согласную на конце («заме*»)", "atlas/query.py",
  'if not cut and low[-1] in _SOFT_TAIL:', 'if not cut:'),
 ("query: короткие русские слова без форм", "atlas/query.py",
  'if SHORT_CYR_RE.match(word):\n        return "forms"', 'if False:\n        return "forms"'),
 ("query: ИЛИ работает как И", "atlas/query.py",
  'parsed.groups[-1].append(term)', 'parsed.groups.append([term])'),
 ("query: минус не исключает", "atlas/query.py",
  'parsed.excluded.append(term)', 'parsed.groups.append([term])'),
 ("query: совпадение не помечается", "atlas/query.py",
  'add(text[a:b], True)', 'add(text[a:b], False)'),
 ("query: окно фрагмента без учёта разных слов", "atlas/query.py",
  'key = (len(set(inside)), len(inside))', 'key = (0, 0)'),
 ("search: не сообщать поле совпадения", "atlas/search.py",
  'if not hits:\n                continue\n            distinct', 'if True:\n                continue\n            distinct'),
 ("search: выдержка из первого хода, а не из лучшего", "atlas/search.py",
  'if (distinct, hits) > slot["_best"]:', 'if slot["_best"] == (-1, -1):'),
 ("search: заголовок в общем счёте совпадений", "atlas/search.py",
  'body = [m for m in matches if m["field"] != "title"] or matches', 'body = matches'),
 ("search: итог только по странице", "atlas/search.py",
  'out["total"] = len(rows)', 'out["total"] = len(rows[:limit])'),
 ("search: молчать о совпадениях вне запросов", "atlas/search.py",
  'if scope == "prompts":\n        wide', 'if False:\n        wide'),
 ("search: релевантность — голый bm25", "atlas/search.py",
  'return sorted(cands, key=lambda c: (c[0] not in in_title, -pairs[c[0]], position[c[0]]))',
  'return cands'),
 ("db: писать схему на каждом подключении", "atlas/db.py",
  'if _schema_is_current(conn):\n        return conn', 'if False:\n        return conn'),
 ("server: не догонять индекс для списка", "atlas/server.py",
  'indexing = catch_up()', 'indexing = False'),
 ("server: догонять на каждое нажатие", "atlas/server.py",
  'if time.monotonic() - _catchup_at < CATCHUP_EVERY:\n            return False', 'if False:\n            return False'),
 ("server: ждать и чужой идущий проход", "atlas/server.py",
  'return True     # чужой проход не ждём', 'current = _catchup_proc  # чужой проход не ждём'),
 ("server: ждать долгий проход до конца", "atlas/server.py",
  'current.join(CATCHUP_WAIT)', 'current.join()'),
 ("actions: не экранировать аргументы команды", "atlas/actions.py",
  'return f"cd {shlex.quote(cwd)} && " + " ".join(shlex.quote(p) for p in parts)\n\n\ndef new_session_command',
  'return f"cd {cwd} && " + " ".join(parts)\n\n\ndef new_session_command'),
 ("actions+db: снят и ранний возврат, и UNIQUE-индекс", "atlas/db.py",
  "CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_active", "CREATE INDEX IF NOT EXISTS ux_jobs_active"),
 ("runner: отдавать наружу без разрешения", "atlas/runner.py",
  'raise EgressDenied(', 'return None or EgressDenied('),
 ("runner: считать litellm локальным", "atlas/runner.py",
  'LOCAL_BACKENDS = {"ollama", "lmstudio", "llamacpp"}',
  'LOCAL_BACKENDS = {"ollama", "lmstudio", "llamacpp", "claude-cli"}'),
 ("enrich: чинить битый JSON эвристикой", "atlas/enrich.py",
  'raise ValueError("модель не вернула JSON")', 'return {"did": text}'),
 ("enrich: не требовать разделов хендоффа", "atlas/enrich.py",
  'if missing:', 'if False:'),
 ("server: пускать чужой Origin", "atlas/server.py",
  'if origin and origin not in ALLOWED_ORIGINS:', 'if False:'),
 ("server: не проверять CSRF-токен", "atlas/server.py",
  'if self.headers.get("X-Atlas-Token") != csrf_token():', 'if False:'),
 ("server: принимать любую цель экспорта", "atlas/server.py",
  'if label not in destinations:', 'if False:'),
 ("search: правило домена выше вердикта модели", "atlas/search.py",
  'elif verdict and verdict["domain"]:\n        final_domains, domain_source = [verdict["domain"]], "llm"\n    elif domains:\n        final_domains, domain_source = domains, "rule"',
  'elif domains:\n        final_domains, domain_source = domains, "rule"\n    elif verdict and verdict["domain"]:\n        final_domains, domain_source = [verdict["domain"]], "llm"'),
 ("search: ручная тема не перебивает модель", "atlas/search.py",
  '"topic": ((override["topic"] if override and override["topic"] else None)\n                  or (verdict["topic"] if verdict else None)),',
  '"topic": (verdict["topic"] if verdict else None),'),
 ("db: классификация снова в дешёвом производном", "atlas/db.py",
  'DERIVED = (\n    "sources", "sessions"', 'DERIVED = (\n    "classification", "enrichment",\n    "sources", "sessions"'),
 ("db: апгрейд схемы не просит пересборку", "atlas/db.py",
  "conn.execute(\"INSERT INTO meta(key, value) VALUES('needs_reindex', '1') \"\n                 \"ON CONFLICT(key) DO UPDATE SET value='1'\")",
  "pass"),
 ("index: ensure_indexed ничего не делает", "atlas/index.py",
  'if db.get_meta(conn, "needs_reindex") != "1":\n        return None',
  'if True:\n        return None'),
 ("classify: чувствительные сессии уходят наружу", "atlas/classify.py",
  "AND COALESCE((SELECT sensitivity FROM user_overrides u WHERE u.session_id = s.session_id),\n                       s.sensitivity_rule) != 'sensitive'", "AND 1=1"),
 ("classify: «разное» с высокой уверенностью проходит", "atlas/classify.py",
  'if topic.lower() == "разное" and confidence >= 0.5:', 'if False:'),
 ("classify: домен вне канона принимается", "atlas/classify.py",
  'if domain not in DOMAINS:', 'if False:'),
 ("parse: не разворачивать слэш-команду", "atlas/parse.py",
  'prompt = readable_prompt(text)', 'prompt = text'),
 ("search: не срезать преамбулу сводки", "atlas/search.py",
  'if marker in summary[:400]:', 'if False:'),
 ("classify: не отдавать однострочное описание", "atlas/classify.py",
  'summary = " ".join((data.get("summary") or "").split())[:200]', 'summary = None'),
 ("runner: сводки и запросы режутся первыми", "atlas/runner.py",
  'take("Сводки компактации", facts.summaries)\n    take("Запросы пользователя", facts.user_text)\n    take("Ответы ассистента (хвост сессии)", facts.assistant_text)',
  'take("Ответы ассистента (хвост сессии)", facts.assistant_text)\n    take("Сводки компактации", facts.summaries)\n    take("Запросы пользователя", facts.user_text)'),
 ("runner: брать ответы с начала, а не с конца", "atlas/runner.py",
  'for text in reversed(items):', 'for text in items:'),
 ("runner: символ на токен как для английского", "atlas/runner.py",
  'CHARS_PER_TOKEN = 2.1', 'CHARS_PER_TOKEN = 4.0'),
 ("runner: не предпроверять большой вызов", "atlas/runner.py",
  'if len(prompt) > PREFLIGHT_ABOVE:\n        preflight(effort=effort)', 'pass'),
 ("search: не ограничивать длину запроса в карточке", "atlas/search.py",
  '    if len(out) <= limit:\n        return out', '    return out'),
 ("web: длинный путь в выдержке распирает карточку", "web/js/atlas.css",
  'white-space:pre-wrap;overflow-wrap:anywhere}', 'white-space:pre-wrap}'),
 ("runner: искать claude только в PATH", "atlas/runner.py",
  '''    for candidate in CLAUDE_CANDIDATES:
        path = os.path.expanduser(candidate)
        if os.access(path, os.X_OK):
            return path
''', ''),
 ("actions: переименование перезаписывает транскрипт", "atlas/actions.py",
  'with open(row["source_path"], "a", encoding="utf-8") as fh:',
  'with open(row["source_path"], "w", encoding="utf-8") as fh:'),
 ("search: ручной заголовок не перебивает записанный", "atlas/search.py",
  '"title": (override["title"] if override and override["title"] else row["title"]),',
  '"title": row["title"],'),
 ("db: не мигрировать старую схему", "atlas/db.py",
  'if int(row["value"]) >= SCHEMA_VERSION:\n        return', 'if True:\n        return'),
 ("active: принимать чужой процесс с тем же PID", "atlas/active.py",
  'return proc_start is None or table[pid][1] == " ".join(proc_start.split())', 'return True'),
 ("active: показывать фоновые прогоны", "atlas/active.py",
  'return data.get("kind") == "interactive" and data.get("entrypoint") not in HEADLESS_ENTRYPOINTS',
  'return True'),
 ("active: не сортировать по последнему сообщению", "atlas/active.py",
  'out.sort(key=lambda s: _as_datetime(s["last_message_at"]), reverse=True)', 'pass'),
 ("active: свежесть только из индекса", "atlas/active.py",
  'tail = found["last_at"]', 'tail = None'),
 ("active: уведомления и сводки считаются сообщением", "atlas/active.py",
  'return kind == "assistant" or not text.startswith(NOT_A_MESSAGE)', 'return True'),
 ("active: не смотреть глубже хвоста из тулов", "atlas/active.py",
  'window *= 4           # хвост', 'return None           # хвост'),
 ("runner: хендофф без окна 1M", "atlas/runner.py",
  'NATIVE_1M = {"claude-opus-5-5"}', 'NATIVE_1M = set()'),
 ("active: хвост ответа — начало, а не конец", "atlas/active.py",
  '    tail = text[cut:]\n', '    tail = text[:limit]\n'),
 ("active: waiting_for и у спокойной сессии", "atlas/active.py",
  '"waiting_for": data.get("waitingFor") if data.get("status") == "waiting" else None,',
  '"waiting_for": data.get("waitingFor"),'),
 ("uploads: принимать любые байты как картинку", "atlas/uploads.py",
  'if ext is None:\n        raise UploadError', 'if False:\n        raise UploadError'),
 ("uploads: файл читается всеми", "atlas/uploads.py",
  'os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600', 'os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644'),
 ("uploads: не чистить старые", "atlas/uploads.py",
  'if now - os.stat(path).st_mtime > KEEP_SECONDS:', 'if False:'),
 ("active: шелл-статус не считать работой", "atlas/active.py",
  'if status in ("busy", "shell"):', 'if status == "busy":'),
 ("active: одна цель /goal уже «в фоне»", "atlas/active.py",
  'if background["shells"] or background["agents"] or background["wake_at"] \\',
  'if background["goal"] or background["shells"] or background["agents"] or background["wake_at"] \\'),
 ("active: MCP-серверы считать фоновыми командами", "atlas/active.py",
  'if row[0] == pid and len(row) > 2 and SHELL_TASK_MARK in row[2])',
  'if row[0] == pid and len(row) > 2)'),
 ("active: прошедший будильник всё ещё ждёт", "atlas/active.py",
  'if wake and wake > now:', 'if wake:'),
 ("active: не открывать заново блок кода в хвосте", "atlas/active.py",
  'return (FENCE + "\\n" + tail) if fences % 2 else tail', 'return tail'),
 ("active: резать хвост посреди строки", "atlas/active.py",
  'if 0 <= line < len(text) - 1:\n        cut = line + 1', 'if False:\n        cut = line + 1'),
 ("active: вывод команды считать твоим сообщением", "atlas/active.py",
  '"<local-command-stdout>", ', ''),
 ("active: команда с тегами, а не как набрана", "atlas/active.py",
  '    m = _COMMAND_RE.search(text)\n    if m:', '    m = None\n    if m:'),
 ("costs: один ответ считать по каждой строке", "atlas/costs.py",
  'if key in seen or msg.get("model") == SYNTHETIC:', 'if msg.get("model") == SYNTHETIC:'),
 ("costs: запись в кэш на час как на 5 минут", "atlas/costs.py",
  'WRITE_5M, WRITE_1H = 1.25, 2.0', 'WRITE_5M, WRITE_1H = 1.25, 1.25'),
 ("costs: досчёт не сбрасывать на записи", "atlas/costs.py",
  'recorded, stamp, after = float(rec["totalCostUSD"]), last_ts, 0.0',
  'recorded, stamp = float(rec["totalCostUSD"]), last_ts'),
 ("costs: сабагентов считать и до записи", "atlas/costs.py",
  'if stamp and ts > stamp)', ')'),
 ("costs: служебные ответы — модель без цены", "atlas/costs.py",
  'if key in seen or msg.get("model") == SYNTHETIC:', 'if key in seen:'),
]
MUT += [
 ("автоклассификация: включена по умолчанию", "atlas/autoclassify.py",
  'return _meta(conn, KEY_ENABLED) == "1"', 'return _meta(conn, KEY_ENABLED) != "0"'),
 ("автоклассификация: без паузы в час", "atlas/autoclassify.py",
  'if last and now - float(last) < INTERVAL_SECONDS:', 'if False:'),
 ("автоклассификация: размеченные без отметки — пересчитать все", "atlas/autoclassify.py",
  'if r["done"] and r["seen"] is None:', 'if False:'),
 ("автоклассификация: изменения не замечаются", "atlas/autoclassify.py",
  'elif not r["done"] or r["seen"] != r["sig"]:', 'elif not r["done"]:'),
 ("автоклассификация: без предела за проход", "atlas/autoclassify.py", 'return out[:MAX_PER_RUN]', 'return out'),
 ("автоклассификация: поверх идущей классификации", "atlas/autoclassify.py",
  'if not enabled(conn) or _job_running(conn):', 'if not enabled(conn):'),
 ("автоклассификация: свежие сессии тоже", "atlas/autoclassify.py",
  "WHERE s.session_kind = 'interactive' AND s.started_at <= ?",
  "WHERE s.session_kind = 'interactive' AND ? IS NOT NULL"),
 ("автоклассификация: чувствительные наружу", "atlas/autoclassify.py",
  "'unclassified') != 'sensitive'", "'unclassified') != 'никогда'"),
 ("автоклассификация: без «Что сделано»", "atlas/autoclassify.py", '            summary(conn, sid, job_id)\n', ''),
 ("автоклассификация: без отметки после прохода", "atlas/autoclassify.py",
  '        _mark(conn, sid, sig)                  # не вышло', '        pass                  # не вышло'),
 ("автоклассификация: «Что сделано» без разрешения", "atlas/autoclassify.py",
  '    runner.grant_egress(conn, session_id, payload["content_hash"], SUMMARY_KIND,\n'
  '                        runner.EXTERNAL_BACKEND, model)\n', ''),
]
MUT += [
 ("сервер: каждый опрос активных считает заново", "atlas/server.py",
  'time.monotonic() - _active_cached["at"] < ACTIVE_REUSE_SECONDS:', 'False:'),
]
MUT += [
 ("активные: прерывание считается репликой", "atlas/active.py",
  '"A session-scoped Stop hook is now active", "Caveat: The messages below",\n                 "[Request interrupted by user")',
  '"A session-scoped Stop hook is now active", "Caveat: The messages below")'),
 ("активные: прерывание не отмечается", "atlas/active.py",
  'out["interrupted_at"] = rec.get("timestamp")', 'pass'),
]
MUT += [
 ("запуск: папка не из списка", "atlas/launch.py",
  'if not isinstance(cwd, str) or cwd not in {w["path"] for w in workdirs(conn)}:',
  'if not isinstance(cwd, str):'),
 ("запуск: запрос-флаг идёт флагом", "atlas/launch.py",
  'parts.append(" " + prompt if prompt.startswith("-") else prompt)', 'parts.append(prompt)'),
 ("запуск: запрос без экранирования", "atlas/launch.py",
  '" ".join(shlex.quote(p) for p in parts)', '" ".join(parts)'),
 ("запуск: скретчпад сессии в списке", "atlas/launch.py",
  'and "/scratchpad" not in path', 'and True'),
 ("запуск: скрытые папки в списке", "atlas/launch.py",
  'and not any(part.startswith(".") for part in path.split(os.sep))', ''),
]
MUT += [
 ("очередь: dequeue не снимает", "atlas/prompt_queue.py",
  'elif op == "dequeue":\n            if queue:\n                queue.pop(0)', 'elif op == "dequeue":\n            pass'),
 ("очередь: dequeue снимает с конца", "atlas/prompt_queue.py",
  'if queue:\n                queue.pop(0)', 'if queue:\n                queue.pop()'),
 ("очередь: popAll не чистит", "atlas/prompt_queue.py", 'queue.clear()', 'pass'),
 ("очередь: уведомления наружу", "atlas/prompt_queue.py",
  'if q["text"].strip() and not q["text"].startswith(SYSTEM_PREFIXES)]', 'if q["text"].strip()]'),
 ("очередь: remove по порядку, а не по тексту", "atlas/prompt_queue.py",
  'same = [i for i, q in enumerate(queue) if content and q["text"] == content]', 'same = [0] if queue else []'),
]
MUT += [
 ("лента: окно не растёт", "atlas/feed.py", 'window *= 4', 'return built[-turns:]'),
 ("лента: уведомления — новый ход", "atlas/feed.py",
  'if kind == "user" and active.is_message(rec):', 'if kind == "user":'),
 ("лента: файл правок считается по вызовам", "atlas/feed.py",
  'files = len(g["detail"]) or n\n            text = f"правил', 'files = n\n            text = f"правил'),
 ("лента: ответ — первый текст хода", "atlas/feed.py",
  'turn["reply"] = block["text"].strip()', 'turn["reply"] = turn["reply"] or block["text"].strip()'),
 ("лента: прерывание не отмечается", "atlas/feed.py", 'turn["interrupted"] = True', 'pass'),
 ("лента: хвост чужого хода в ленте", "atlas/feed.py",
  '        if not turns:\n            continue', '        if not turns:\n            turns.append(_new_turn(rec))'),
]
MUT += [
 ("команды: скилл по полю name", "atlas/commands.py",
  'out.append({"name": prefix + name, "kind": kind,',
  'out.append({"name": prefix + (_frontmatter(md).get("name") or name), "kind": kind,'),
 ("команды: встроенная дублируется", "atlas/commands.py",
  '        if c["name"] not in seen:', '        if True:'),
 ("команды: служебные скиллы в списке", "atlas/commands.py",
  'if name.startswith(("_", ".")) or not os.path.isfile(md):', 'if not os.path.isfile(md):'),
]
MUT += [
 ("контекст: окно всегда 200k", "atlas/costs.py",
  'if tokens and tokens > WINDOW_DEFAULT:\n        return WINDOW_1M', 'if False:\n        return WINDOW_1M'),
 ("контекст: сабагент меняет контекст сессии", "atlas/costs.py",
  'if not rec.get("isSidechain"):\n            ctx, model', 'if True:\n            ctx, model'),
 ("контекст: без записи в кэш", "atlas/costs.py",
  '("input_tokens", "cache_read_input_tokens", "cache_creation_input_tokens"))', '("input_tokens", "cache_read_input_tokens"))'),
 ("лимиты: сброс строкой не читается", "atlas/limits.py",
  'if value.replace(".", "").isdigit():\n            return _iso(float(value))', 'if False:\n            return None'),
 ("строка состояния: мусор затирает файл", "tools/statusline.py",
  'if isinstance(data, dict) and _has_window(data.get("rate_limits")):',
  'if isinstance(data, dict) and isinstance(data.get("rate_limits"), dict):'),
 ("строка состояния: падает на мусоре", "tools/statusline.py",
  'limits = limits if isinstance(limits, dict) else {}', 'limits = limits or {}'),
]
MUT += [
 ("перенос: Obsidian тоже завершается", "atlas/relocate.py",
  'if app == "Obsidian":\n        raise RelocateError("сессия уже во вкладке Obsidian")', 'if False:\n        pass'),
 ("перенос: чужая сессия по PID", "atlas/relocate.py",
  'if not data or data.get("sessionId") != session_id or not active.is_interactive(data):',
  'if not data or not active.is_interactive(data):'),
 ("перенос: переиспользованный PID", "atlas/relocate.py",
  'if not active._alive(pid, data.get("procStart"), table):\n        raise',
  'if pid not in table:\n        raise'),
 ("перенос: зомби считается живым", "atlas/relocate.py",
  '\n        or _command(table, pid).strip() == "<defunct>"', ''),
 ("перенос: приложение — ближайшее .app", "atlas/relocate.py",
  '        if m:\n            found = m.group(1)\n    return found', '        if m:\n            return m.group(1)\n    return found'),
]
MUT += [
 ("модели: без обязательного 1M", "atlas/runner.py",
  'return (model if has_1m_window(model) else model + "[1m]"), effort', 'return model, effort'),
 ("модели: «Что сделано» на medium", "atlas/runner.py",
  '"catalog_summary": ("claude-opus-5-5", "low"),', '"catalog_summary": ("claude-opus-5-5", "medium"),'),
]
MUT += [
 ("«Что сделано»: шаблон через format", "atlas/enrich.py",
  'return template.replace("{payload}", text)', 'return template.format(payload=text)'),
]
MUT += [
 ("команды: частые не первыми", "atlas/commands.py",
  'return first + rest', 'return sorted(pool, key=lambda c: c["name"].lower())'),
 ("команды: выключенный плагин в списке", "atlas/commands.py",
  '(entry.get("scope") != "user" or enabled.get(full))', 'True'),
 ("команды: без плагинов организации", "atlas/commands.py",
  '    for manifest in glob.glob(', '    for manifest in []:  # glob.glob('),
]
JS_MUT = [
 ("plugin: перезагрузка как «выключено пользователем» (закрывает вкладки)", "obsidian-plugin/src/reload.js",
  "await plugins.disablePlugin(id);", "await plugins.disablePlugin(id, true);"),
 ("plugin: сервер старой версии не заменяется", "obsidian-plugin/src/runtime.js",
  "if (!stale) return { ok: true, reason: null };", "if (true) return { ok: true, reason: null };"),
 ("plugin: новая сборка на диске не подхватывается", "obsidian-plugin/src/reload.js",
  "if (this.reloadInPlace()) new Notice", "if (false) new Notice"),
 ("plugin: первый запуск затирает аргументы агентов", "obsidian-plugin/src/main.js",
  "if (!saved.agentArgs && this.adoptAgentArgs()) await this.saveData(this.settings);", ""),
 ("runtime: python без CLT берётся всё равно", "obsidian-plugin/src/runtime.js",
  '.filter((p) => p !== "/usr/bin/python3" || clt);', ";"),
 ("runtime: старые файлы не удаляются", "obsidian-plugin/src/runtime.js",
  "if (!keep.has(path.join(sub, rel))) fsSync.rmSync(path.join(root, rel), { force: true });", ""),
 ("runtime: чужой сервер на порту принят за свой", "obsidian-plugin/src/runtime.js",
  'if (health && health.app === "session-atlas") return { ok: true, reason: null };\n    if (health) return',
  'if (health) return { ok: true, reason: null };\n    if (health) return'),
 ("pty: размер не выставляется до старта", "obsidian-plugin/src/pty.js",
  """const INNER = 'stty rows "$1" cols "$2" 2>/dev/null; shift 2; exec "$@"';""",
  """const INNER = 'shift 2; exec "$@"';"""),
 ("pty: закрытие не гасит группу", "obsidian-plugin/src/pty.js",
  "try { process.kill(-child.pid, signal); }", "try { process.kill(child.pid, signal); }"),
 ("config-form: дубли доменов", "obsidian-plugin/src/config-form.js",
  " || out.some((d) => d.id === id)) continue;", ") continue;"),
 ("plugin: разбор пускает ; и $", "obsidian-plugin/src/agents.js",
  "    } else {\n      return null;\n    }\n  }\n  if (cur !== null) out.push(cur);",
  "    } else {\n      cur = (cur || \"\") + c; i++;\n    }\n  }\n  if (cur !== null) out.push(cur);"),
 ("plugin: лишние флаги claude принимаются", "obsidian-plugin/src/agents.js",
  'if (flag === "--resume" && rest.length === 0)', 'if (flag === "--resume")'),
 ("plugin: запрос без кавычек в аргументах вкладки", "obsidian-plugin/src/agents.js",
  "if (seed.prompt) parts.push(shellQuote(seed.prompt));", "if (seed.prompt) parts.push(seed.prompt);"),
 ("plugin: каталог мимо скрипта", "obsidian-plugin/src/terminal.js",
  'if (launch && (await this.openAgent("claude", { cwd: launch.cwd, seed: launch, label }))) return;', ''),
 ("plugin: pointerdown по крестику не гасится", "obsidian-plugin/src/guard.js",
  "    if (!this.guardKind(leaf)) return;\n    event.preventDefault();\n    event.stopPropagation();\n    event.stopImmediatePropagation();\n    if (ask)",
  "    if (!this.guardKind(leaf) || !ask) return;\n    event.preventDefault();\n    event.stopPropagation();\n    event.stopImmediatePropagation();\n    if (ask)"),
 ("plugin: ⌘W без подтверждения", "obsidian-plugin/src/guard.js",
  "if (!checking && self.guardKind(leaf) && original.call(this, true)) {", "if (false) {"),
 ("plugin: двойной вопрос со старым плагином", "obsidian-plugin/src/guard.js",
  '&& !this.legacyEnabled("agent-terminal-ribbons")) return "terminal";', ') return "terminal";'),
 ("plugin: проводник дублирует открытый файл", "obsidian-plugin/src/explorer.js",
  "    if (open) {", "    if (false) {"),
 ("plugin: проводник съедает клик по папке", "obsidian-plugin/src/explorer.js",
  "if (!(file instanceof TFile)) return;", "if (!file) return;"),
 ("plugin: вторая пара кнопок со старым плагином", "obsidian-plugin/src/main.js",
  'if (!this.legacyEnabled("agent-terminal-ribbons")) this.addAgentButtons();', 'this.addAgentButtons();'),
 ("plugin: восстановление без задержки", "obsidian-plugin/src/restore.js",
  "&& Date.now() - (this.loadedAt || 0) >= RESTORE_GRACE_MS", ""),
 ("plugin: язык Obsidian игнорируется", "obsidian-plugin/src/i18n.js",
  'return String(obsidianLanguage || "").toLowerCase().startsWith("ru") ? "ru" : "en";', 'return "en";'),
 ("logic: переход — хватает одного слова", "web/js/logic.js",
  "if (!words.every(w => hay.includes(w))) return;", "if (!words.some(w => hay.includes(w))) return;"),
 ("logic: переход — закрытые наравне с живыми", "web/js/logic.js",
  'scored.push([it.kind === "live" ? 0 : 1, head, i, it]);', "scored.push([0, head, i, it]);"),
 ("logic: переход — начало названия не важно", "web/js/logic.js",
  "const head = words.length && title.startsWith(words[0]) ? 0 : 1;", "const head = 0;"),
 ("plugin: план — текст без проверки поля", "obsidian-plugin/src/input.js",
  "if (!(await seen((f) => f.n === field.n && f.selected))) {", "if (false) {"),
 ("plugin: план — Enter без сверки текста", "obsidian-plugin/src/input.js",
  "if (!(await seen((f) => squash(f.typed) === squash(text)))) {", "if (false) {"),
 ("plugin: план — замечания в чужой вариант", "obsidian-plugin/src/input.js",
  "if (!field || field.n !== data.option ||", "if (!field ||"),
 ("plugin: план — переносы строк не убраны", "obsidian-plugin/src/input.js",
  '.replace(/\\s+/g, " ").trim();\n    if (!text', '.trim();\n    if (!text'),
 ("plugin: план не распознан как план", "obsidian-plugin/src/dialog.js",
  "  const plan = parsePlanDialog(rows);\n  if (plan) return plan;\n", ""),
 ("plugin: поле замечаний среди кнопок", "obsidian-plugin/src/dialog.js",
  "feedback = options.pop();", "feedback = options[options.length - 1];"),
 ("page: верхний уровень зовёт функцию из позднего файла", "web/js/active-feed.js",
  'let feedView = loadStored(FEED_VIEW_KEY, "turns");', 'let feedView = closedSection(FEED_VIEW_KEY);'),
 ("logic: фильтр ошибок пропускает всё", "web/js/logic.js",
  'error: ev => ev.status === "error"', 'error: ev => true'),
 ("logic: путь соседней папки как свой", "web/js/logic.js",
  'path.startsWith(cwd.replace(/\\/$/, "") + "/")', 'path.startsWith(cwd)'),
 ("page: одноимённая функция в двух файлах", "web/js/stats.js",
  "function saveStatsPrefs() {", "function segmented() {}\nfunction saveStatsPrefs() {"),
 ("logic: задачи без отметок статуса", "web/js/logic.js",
  "`${TASK_MARK[i.status] || \"○\"} ${i.subject}`", "i.subject"),
 ("logic: пустой список задач показывать", "web/js/logic.js",
  "if (!t || !t.total) return null;", "if (!t) return null;"),
 ("stats-logic: миллиарды как миллионы", "web/js/stats-logic.js",
  "if (a >= 1e9)", "if (a >= 1e19)"),
 ("stats-logic: рост со знаком минус", "web/js/stats-logic.js",
  '(pct > 0 ? "+" : "−")', '"−"'),
 ("stats-logic: деление на ноль в сравнении", "web/js/stats-logic.js",
  "|| prev <= 0) return null", ") return null"),
 ("stats-logic: сортировка не по мере", "web/js/stats-logic.js",
  ".sort((a, b) => b[metric] - a[metric])", ".sort(() => 0)"),
 ("stats-logic: пустое не отброшено", "web/js/stats-logic.js",
  ".filter(i => i[metric] > 0)", ".filter(() => true)"),
 ("плагин: не проверять origin сообщения", "obsidian-plugin/src/main.js",
  'if (event.origin !== ATLAS_ORIGIN) return;', 'if (false) return;'),
 ("плагин: не проверять source сообщения", "obsidian-plugin/src/main.js",
  'if (!data || data.source !== "session-atlas") return;', 'if (!data) return;'),
 ("плагин: принимать любой тип действия", "obsidian-plugin/src/main.js",
  'if (data.type === "resume" || data.type === "new-session") {', 'if (true) {'),
 ("плагин: строчный iframe с лишней полосой", "obsidian-plugin/src/view.js",
  'this.frame.style.display = "block";', ''),
 ("плагин: печатать в сессию с открытым диалогом", "obsidian-plugin/src/input.js",
  'if (state.status === "waiting") {', 'if (false) {'),
 ("плагин: не проверять, что процесс из этой вкладки", "obsidian-plugin/src/input.js",
  'if (!this.isDescendant(data.claudePid, data.ptyPid)) {', 'if (false) {'),
 ("плагин: не сверять id сессии", "obsidian-plugin/src/input.js",
  'if (!state || state.sessionId !== data.sessionId) return { error: "сессия не найдена" };',
  'if (!state) return { error: "сессия не найдена" };'),
 ("плагин: пропускать управляющие символы", "obsidian-plugin/src/terminal.js",
  '.replace(/[\\x00-\\x08\\x0b-\\x1f\\x7f]/g, "")', ''),
 ("плагин: многострочный без вставки", "obsidian-plugin/src/input.js",
  'stdin.write(text.includes("\\n") ? PASTE_START + text + PASTE_END : text);', 'stdin.write(text);'),
 ("плагин: без Enter после текста", "obsidian-plugin/src/input.js",
  'window.setTimeout(() => stdin.write("\\r"),', 'window.setTimeout(() => null,'),
 ("плагин: картинки из любой папки", "obsidian-plugin/src/terminal.js",
  'if (!full.startsWith(root) || !IMAGE_EXT.test(full)', 'if (!IMAGE_EXT.test(full)'),
 ("плагин: путь картинки без отдельной вставки", "obsidian-plugin/src/input.js",
  'for (const image of images) stdin.write(PASTE_START + image + PASTE_END + " ");',
  'for (const image of images) stdin.write(image + " ");'),
 ("плагин: закрывать вкладку без подтверждения", "obsidian-plugin/src/main.js",
  'this.confirmCloseTerminal(tab.leaf, title || tab.title);', 'tab.leaf.detach();'),
 ("плагин: отвечать списком вкладок любому origin", "obsidian-plugin/src/main.js",
  '}, ATLAS_ORIGIN);\n  }\n\n  async actOnTab', '}, "*");\n  }\n\n  async actOnTab'),
 ("плагин: ждать зависший терминал без таймаута", "obsidian-plugin/src/terminal.js",
  'new Promise((resolve) => window.setTimeout(() => resolve(null), PTY_WAIT_MS)),',
  'new Promise(() => {}),'),
 ("плагин: не проверять, что команда строка", "obsidian-plugin/src/main.js",
  'if (typeof data.command !== "string" || !data.command) return;', ''),
 ("страница: javascript:-ссылка кликабельна", "web/js/markdown.js",
  'const SAFE_URL = /^(https?:\/\/|mailto:)/i;', 'const SAFE_URL = /./;'),
 ("страница: snake_case становится курсивом", "web/js/markdown.js",
  "{ re: /(^|[^\\w*])\\*([^*\\s][^*\\n]*?)\\*(?!\\w)/,", "{ re: /(^|[^*])\\*([^*\\n]*?)\\*/,"),
 ("страница: точка в конце URL уходит в ссылку", "web/js/markdown.js",
  """[^\\s<>()\\].,;:!?'"»]/,""", """/,"""),
 ("страница: блок кода разбирает разметку", "web/js/markdown.js",
  'blocks.push({ t: "pre", text: body.join("\\n") });', 'blocks.push({ t: "p", lines: body.map(parseInline) });'),
 ("страница: смена - на 1. без нового списка", "web/js/markdown.js",
  '&& stack[stack.length - 1].list.ordered !== ordered) stack.pop();', '&& false) stack.pop();'),
 ("страница: фильтры списка — И вместо ИЛИ", "web/js/logic.js",
  'valuesOf(s, key, now).some(v => want.has(v))', '[...want].every(v => valuesOf(s, key, now).includes(v))'),
 ("страница: счётчик учитывает свой же фильтр", "web/js/logic.js",
  'sessions.filter(s => passes(s, filters, key, now))', 'sessions.filter(s => passes(s, filters, null, now))'),
 ("страница: раскладка без предела", "web/js/logic.js",
  'return m && +m[1] <= max && +m[2] <= max ?', 'return m ?'),
 ("страница: вчера считается неделей", "web/js/logic.js",
  'if (days === 1) return "yesterday";', ''),
 ("страница: отправленное не снимается, когда транскрипт догнал", "web/js/logic.js",
  '|| t(s.prompt_at) >= t(sent.at) - 2000)', ')'),
 ("страница: вниз — на одну карточку, не на ряд", "web/js/logic.js",
  'ArrowDown: cols, ArrowUp: -cols', 'ArrowDown: 1, ArrowUp: -1'),
 ("страница: навигация выходит за край", "web/js/logic.js",
  'return ids[Math.max(0, Math.min(ids.length - 1, i + step))];', 'return ids[i + step];'),
 ("страница: оценка сейчас без прироста", "web/js/logic.js",
  's.cost_now - s.cost_usd >= 0.005', 'true'),
 ("страница: молчащий плагин вечно «проверяется»", "web/js/logic.js",
  'if (askedAt && now - askedAt > HOST_REPLY_MS) {', 'if (false) {'),
 ("плагин: связь «есть» при выключенном Terminal", "obsidian-plugin/src/terminal.js",
  'if (!plugins || !plugins.has("terminal")) {', 'if (false) {'),
 ("плагин: вкладки без процесса — связь «есть»", "obsidian-plugin/src/terminal.js",
  'if (leaves.length && !tabs.length) {', 'if (false) {'),
 ("плагин: уведомлять о новой сессии", "obsidian-plugin/src/notify.js",
  'if (was === undefined || was === now) continue;', 'if (was === now) continue;'),
 ("плагин: уведомлять при выключенной настройке", "obsidian-plugin/src/notify.js",
  'if (this.settings && this.settings.notify) {', 'if (this.settings) {'),
 ("плагин: уведомлять, когда смотришь на вкладку", "obsidian-plugin/src/notify.js",
  'if (focused && tab && this.app.workspace.activeLeaf === tab.leaf) return;', ''),
 ("плагин: сервер молчит — счётчик в ноль", "obsidian-plugin/src/notify.js",
  'if (!data || !Array.isArray(data.sessions)) return;', 'if (!data) data = { sessions: [] };'),
 ("плагин: заголовок без счётчика", "obsidian-plugin/src/notify.js",
  'return count ? `Session Atlas (${count})` : "Session Atlas";', 'return "Session Atlas";'),
 ("диалог: варианты с вводом текста — кнопками", "obsidian-plugin/src/dialog.js",
  'const choices = options.filter((o) => !NEEDS_TEXT.test(o.text));', 'const choices = options;'),
 ("диалог: несколько вопросов отвечаются цифрой", "obsidian-plugin/src/dialog.js",
  'answerable: !multi && choices.length > 0,', 'answerable: choices.length > 0,'),
 ("диалог: перенос подписи разрешения не склеивается", "obsidian-plugin/src/dialog.js",
  'if (kind === "permission") {\n    options.forEach', 'if (false) {\n    options.forEach'),
 ("диалог: подвал не обязателен", "obsidian-plugin/src/dialog.js",
  'if (footer < 0) return null;', 'if (footer < 0) footer = rows.length;'),
 ("плагин: ответ без сверки подписи с экраном", "obsidian-plugin/src/input.js",
  'if (!sameOption(dialog, data.option, data.text)) {', 'if (!dialog) {'),
 ("плагин: ответ на диалог с Enter", "obsidian-plugin/src/input.js",
  'stdin.write(String(data.option));', 'stdin.write(String(data.option) + "\\r");'),
 ("плагин: ответ, когда диалог уже закрыт", "obsidian-plugin/src/input.js",
  'if (state.status !== "waiting") return reply(false, "диалог уже закрыт");', ''),
 ("плагин: «Стоп» в покое", "obsidian-plugin/src/input.js",
  'if (!STOPPABLE.has(state.status)) return reply(false, "сессия не работает — прерывать нечего");', ''),
 ("плагин: «Стоп» двумя Esc", "obsidian-plugin/src/input.js",
  'stdin.write(ESC);', 'stdin.write(ESC + ESC);'),
 ("плагин: «Стоп» без сверки сессии", "obsidian-plugin/src/input.js",
  'const { error, tab, state } = await this.checkTarget(data);\n    if (error) return reply(false, error);\n    if (!STOPPABLE',
  'const { error, tab, state } = await this.checkTarget(Object.assign({}, data, { sessionId: '
  '(this.readSessionState(data.claudePid) || {}).sessionId }));\n    if (error) return reply(false, error);\n    if (!STOPPABLE'),
 ("страница: прерванный запрос «ждёт ответа»", "web/js/logic.js",
  'interrupted: t(s.interrupted_at) >= t(s.prompt_at) }', 'interrupted: false }'),
 ("страница: доставка без очереди", "web/js/logic.js",
  'if (head && (s.queued || []).some(q => (q.text || "").trim().startsWith(head))) return "queued";', ''),
 ("страница: доставка не пропадает", "web/js/logic.js",
  'if (head && now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS) return "lost";', ''),
 ("страница: картинка без текста — «пропало»", "web/js/logic.js",
  'if (head && now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS)', 'if (now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS)'),
 ("плагин: macOS-уведомление и при окне впереди", "obsidian-plugin/src/notify.js",
  'if (!focused && this.settings && this.settings.systemNotify) this.systemNotify(s, go);',
  'if (this.settings && this.settings.systemNotify) this.systemNotify(s, go);'),
 ("плагин: macOS-уведомление без настройки", "obsidian-plugin/src/notify.js",
  'if (!focused && this.settings && this.settings.systemNotify)', 'if (!focused)'),
 ("плагин: молчит, если вкладка активна в свёрнутом окне", "obsidian-plugin/src/notify.js",
  'if (focused && tab && this.app.workspace.activeLeaf === tab.leaf) return;',
  'if (tab && this.app.workspace.activeLeaf === tab.leaf) return;'),
 ("плагин: клик по macOS-уведомлению не ведёт во вкладку", "obsidian-plugin/src/notify.js",
  '      raiseWindow();\n      go();', '      raiseWindow();'),
 ("страница: подсказки и после пробела", "web/js/logic.js",
  'const m = /^\\/([^\\s]*)$/.exec(text || "");', 'const m = /^\\/(\\S*)/.exec(text || "");'),
 ("страница: подсказки без начинающихся первыми", "web/js/logic.js",
  'return starts.concat(inside);', 'return inside.concat(starts);'),
 ("страница: история не возвращает черновик", "web/js/logic.js",
  'const next = Math.max(-1,', 'const next = Math.max(0,'),
 ("страница: контекст 80% не тревожит", "web/js/logic.js", 'tone: pct >= 80 ? "warn"', 'tone: pct >= 95 ? "warn"'),
 ("страница: устаревшие лимиты не помечены", "web/js/logic.js",
  'const stale = l.age_seconds != null && l.age_seconds > 6 * 3600;', 'const stale = false;'),
 ("страница: порядок по свежести сообщения", "web/js/logic.js",
  'const started = s => new Date(s.process_started_at || s.started_at || 0).getTime();',
  'const started = s => new Date(s.last_message_at || 0).getTime();'),
 ("страница: закреплённые не первыми", "web/js/logic.js",
  'if (pa !== pb) return (pa < 0 ? 1e9 : pa) - (pb < 0 ? 1e9 : pb);', ''),
 ("страница: скрытая не возвращается с новым сообщением", "web/js/logic.js",
  '&& hid[s.session_id] === (s.last_message_at || "");', ';'),
 ("страница: записи скрытых копятся", "web/js/logic.js",
  'return !s || hid[id] !== (s.last_message_at || "");', 'return false;'),
 ("плагин: живые тоже к восстановлению", "obsidian-plugin/src/restore.js",
  '.filter((x) => !alive.has(x.session_id) && fresh(x));', '.filter((x) => fresh(x));'),
 ("плагин: давние тоже к восстановлению", "obsidian-plugin/src/restore.js",
  'now - (x.at || 0) < RESTORE_MAX_AGE_MS : true;', 'true : true;'),
 ("плагин: запоминать и сессии не из вкладок", "obsidian-plugin/src/restore.js",
  'if (await this.tabForSession(s)) {', 'if (true) {'),
 ("плагин: список восстановления любому origin", "obsidian-plugin/src/restore.js",
  '    }, ATLAS_ORIGIN);', '    }, "*");'),
 ("плагин: «не нужно» не забывает", "obsidian-plugin/src/restore.js",
  'this.restorable = drop ? (this.restorable || []).filter((x) => !drop.has(x.session_id)) : [];',
  'this.restorable = this.restorable || [];'),
 ("плагин: «Поднять» дважды — два запуска", "obsidian-plugin/src/main.js",
  'if (this.raisingServer) return;', ''),
 ("плагин: «Поднять» отвечает любому origin", "obsidian-plugin/src/main.js",
  'type: "server-ensured", ok, reason }, ATLAS_ORIGIN);', 'type: "server-ensured", ok, reason }, "*");'),
 ("страница: оценка без ≈", "web/js/logic.js", 'return (estimate ? "≈" : "") + "$"', 'return "$"'),
 ("страница: окно 1M как 1000k", "web/js/logic.js",
  'return n >= 1e6 ? (n / 1e6)', 'return n >= 1e9 ? (n / 1e6)'),
 ("плагин: ответ команды не читается", "obsidian-plugin/src/input.js",
  'if (command && SCREEN_COMMANDS.has(command[1]) && !images.length) {', 'if (false) {'),
 ("плагин: экран читается после любого сообщения", "obsidian-plugin/src/input.js",
  'if (command && SCREEN_COMMANDS.has(command[1]) && !images.length) {', 'if (!images.length) {'),
 ("диалог: панель не распознаётся", "obsidian-plugin/src/dialog.js",
  'if (PANEL_RULE.test(rows[i])) { panel = i; break; }', ''),
 ("диалог: эхо команды остаётся в ответе", "obsidian-plugin/src/dialog.js",
  '        body = body.slice(i + 1);\n        break;', '        break;'),
 ("диалог: значок ⎿ в ответе", "obsidian-plugin/src/dialog.js",
  'body.map((l) => l.replace(/^(\\s*)⎿ {1,2}/, "$1"))', 'body'),
 ("плагин: панель вместо «не разобран» не показывается", "obsidian-plugin/src/input.js",
  '    if (panel && panel.panel) {', '    if (false) {'),
 ("страница: склонение 11 как 1", "web/js/logic.js",
  'if (m10 === 1 && m100 !== 11) return one;', 'if (m10 === 1) return one;'),
]


def _drop_pycache():
    for folder in ("atlas/__pycache__", "tests/__pycache__"):
        shutil.rmtree(folder, ignore_errors=True)


caught = 0
for name, path, old, new in MUT:
    src = open(path, encoding='utf-8').read()
    if old not in src:
        print(f"  ?? НЕ ПРИМЕНИЛАСЬ  {name}"); continue
    shutil.copy(path, path + ".bak")
    open(path, 'w', encoding='utf-8').write(src.replace(old, new, 1))
    _drop_pycache()
    # Мост плагина и страница проверяются в node ниже, их мутации — отдельным списком.
    r = subprocess.run([sys.executable, "-m", "pytest", "-q", "-x", "--no-header", "-p", "no:cacheprovider",
                        "--ignore=tests/test_plugin_bridge.py"],
                       capture_output=True, text=True)
    shutil.move(path + ".bak", path)
    # shutil.move возвращает файл со СТАРЫМ mtime. Если он совпал с тем, что записан в .pyc,
    # Python считает кэш валидным и продолжает исполнять мутированный байткод уже после отката.
    os.utime(path, None)
    _drop_pycache()
    ok = r.returncode != 0
    caught += ok
    print(f"  {'поймана' if ok else 'ПРОПУЩЕНА':10} {name}")
for name, path, old, new in JS_MUT:
    src = open(path, encoding='utf-8').read()
    if old not in src:
        print(f"  ?? НЕ ПРИМЕНИЛАСЬ  {name}"); continue
    shutil.copy(path, path + ".bak")
    open(path, 'w', encoding='utf-8').write(src.replace(old, new, 1))
    test = "tools/test_page.js" if path.startswith("web/") else "tools/test_plugin.js"
    r = subprocess.run(["node", test], capture_output=True, text=True)
    shutil.move(path + ".bak", path)
    os.utime(path, None)
    ok = r.returncode != 0
    caught += ok
    print(f"  {'поймана' if ok else 'ПРОПУЩЕНА':10} {name}")

total = len(MUT) + len(JS_MUT)
print(f"\n{caught}/{total} мутаций поймано")
