"""Mutation testing: break a behaviour and make sure a test turns red.

    python3.11 tools/mutations.py              # every mutation (Python ones via pytest, JS ones via node --test)
    python3.11 tools/mutations.py --check      # only verify that every snippet still applies
    python3.11 tools/mutations.py --only steps # mutations whose name contains "steps"

Each entry is (name, path, old, new): the first occurrence of `old` in `path` becomes `new`. A snippet
that is no longer in the file is a failure, like a mutation the tests miss.

TODO: the full run has not been done since the snippets were re-synced; run it and triage every MISSED.
"""
import argparse
import functools
import os
import shutil
import signal
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MUT = [
 ("server: a due full pass blocks the request", "atlas/server.py",
  "                if index.reindex_due(conn):\n                    catch_up(now=True)",
  "                index.ensure_indexed(conn)"),
 ("index: the background pass skips a due full pass", "atlas/cli.py",
  "    stats = index.ensure_indexed(conn) or index.index_all(conn, full=args.full)",
  "    stats = index.index_all(conn, full=args.full)"),
 ("installer: a staged install keeps the self-reload marker", "tools/install_plugin.py",
  "        elif os.path.exists(path):\n            os.remove(path)\n", ""),
 ("delete: a running session gets deleted", "atlas/delete.py",
  '    if plan["running"]:\n        raise DeleteError(msg("delete.running"))\n', ""),
 ("delete: other sessions' lines leave the input history", "atlas/delete.py",
  "not (session_id in line and _line_sid(line) == session_id)", "not (session_id in line)"),
 ("delete: deletion outside the Claude Code folder", "atlas/delete.py",
  '            raise DeleteError(msg("delete.outside_codex" if codex else "delete.outside", path=item["path"]))',
  "            pass"),
 ("llm: the model is called with AI features off", "atlas/runner.py",
  "    require_llm()                  # last line of defense", "    pass                           # last line of defense"),
 ("llm: model routes stay open with AI features off", "atlas/server.py",
  "                runner.require_llm()\n", "                pass\n"),
 ("llm: the schedule runs with AI features off", "atlas/autoclassify.py",
  "or not runner.llm_enabled() ", ""),
 ("llm: auto-classification cannot be turned off", "atlas/server.py",
  'and body.get("enabled") is False', "and False"),
 ("config: nested user keys get lost", "atlas/config.py",
  "out[key] = dict(base[key], **value)", "out[key] = {k: v for k, v in value.items() if k in base[key]}"),
 ("config: changing settings does not rebuild the index", "atlas/index.py",
  'if db.get_meta(conn, "config_fingerprint") != fingerprint:', "if False:"),
 ("config: tickets are matched even without prefixes", "atlas/config.py",
  "    if not valid:\n        return None", "    if not valid:\n        return re.compile(r\"\\b[A-Z]+-\\d{2,}\\b\")"),
 ("prompts: domains not taken from settings", "atlas/prompts.py",
  '.replace("{domain_ids}", safe(ids))', '.replace("{domain_ids}", "work")'),
 ("runner: 1M without the setting", "atlas/runner.py",
  'if config.get("force_1m") and not has_1m_window(model):', "if not has_1m_window(model):"),
 ("resolve: vault from code, not from settings", "atlas/resolve.py",
  "    for vault, vault_id in config.vaults():\n        if _under(p, vault):", "    for vault, vault_id in [(os.path.join(HOME, \"Notes\"), \"vault\")]:\n        if _under(p, vault):"),
 ("script: start takes priority over the registry", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'elif [[ -z "$session_id" && "$SEED_MODE" == resume* ]]', 'elif [[ "$SEED_MODE" == resume* ]]'),
 ("script: fork without --fork-session", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'claude "${flags[@]}" --resume "$SEED_ID" --fork-session', 'claude "${flags[@]}" --resume "$SEED_ID"'),
 ("script: the hook is not passed", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  '--settings "$(hook_settings)")', ')'),
 ("script: a new session is not written to the registry", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'upsert_resume_id claude "$instance" "$SEED_ID"\n    print "Starting', 'print "Starting'),
 ("script: the transcript is searched only in the vault's folder", "obsidian-plugin/scripts/agent-sessions-lib.zsh",
  'local -a found=("$CLAUDE_PROJECTS_DIR"/*/"$1".jsonl(N))',
  'local -a found=("$CLAUDE_PROJECTS_DIR/${PWD//[^A-Za-z0-9]/-}/$1".jsonl(N))'),
 ("install: scripts are not installed", "tools/install_plugin.py",
  '        shutil.copy(os.path.join(PLUGIN_DIR, "scripts", name), dest)\n', '        pass\n'),
 ("steps: a call error is not shown", "atlas/steps.py",
  'if block.get("is_error"):', 'if False:'),
 ("steps: reads are not merged", "atlas/steps.py",
  'and ev["status"] == "ok" and prev["status"] == "ok"):', 'and False):'),
 ("steps: the reply is repeated as a step", "atlas/steps.py",
  'if reply and events and events[-1]["kind"] == "text":', 'if False:'),
 ("steps: a long turn shows the first steps", "atlas/steps.py",
  'return {"events": merged[hidden:], "earlier": hidden,', 'return {"events": merged[:MAX_EVENTS], "earlier": hidden,'),
 ("steps: the result is not tied to its call", "atlas/feed.py",
  '            turn["collector"].result(rec, content)\n', ''),
 ("touched: subagents are not counted", "atlas/touched.py",
  'sources = [main] + [_scan(p)[0] for p in', 'sources = [main] + [] and [_scan(p)[0] for p in'),
 ("touched: edit lines count the whole text", "atlas/touched.py",
  'if len(a) + len(b) > MAX_DIFF_LINES:', 'if True:'),
 ("touched: the tail is re-read in full", "atlas/touched.py",
  'if cached and cached[0] == st.st_ino and cached[1] <= st.st_size:', 'if False:'),
 ("touched: a rewritten file is read incrementally", "atlas/touched.py",
  'and cached[1] <= st.st_size:', ':'),
 ("closed: live sessions also listed as closed", "atlas/active.py",
  'if r["session_id"] not in live_ids and ', 'if '),
 ("closed: background runs listed as closed", "atlas/active.py",
  "WHERE s.session_kind = 'interactive' AND s.last_activity_at >= ?", "WHERE s.last_activity_at >= ?"),
 ("closed: no time window", "atlas/active.py",
  "AND s.last_activity_at >= ?{picked}\n", "AND ? IS NOT NULL{picked}\n"),
 ("closed: a parked conversation's job listed while its tab is live", "atlas/active.py",
  ' and r["continued_from"] not in live_ids]', ']'),
 ("closed: the parent listed beside the job it went on in", "atlas/active.py",
  "AND NOT EXISTS (SELECT 1 FROM sessions j WHERE j.session_id = s.continued_in)", "AND 1"),
 ("closed: a job running after its tab closed is not offered", "atlas/server.py",
  'conn, {s["session_id"] for s in sessions},',
  'conn, {s["session_id"] for s in sessions} | {str(r["sessionId"]) for r in active._read_files('
  'active.SESSIONS_DIR) if r.get("jobId")},'),
 ("parked: the job is ignored", "atlas/active.py",
  "    job = parked_job(data, jobs)\n", "    job = None\n"),
 ("parked: a dead job still drives the card", "atlas/active.py",
  'if d.get("jobId") and _alive(d["pid"], d.get("procStart"), table)}', 'if d.get("jobId")}'),
 ("parked: a dialog in the job does not make the card wait", "atlas/active.py",
  '    for data in (job, own):\n        if data.get("status") == "waiting":',
  '    for data in (own,):\n        if data.get("status") == "waiting":'),
 ("parked: the card reads the parent's stale transcript", "atlas/active.py",
  "            found, live_sid, live_path = job_found, job_sid, job_path", "            pass"),
 ("parked: the feed reads the parent's stale transcript", "atlas/active.py",
  "    if job_path and _newer(last_messages(job_path), last_messages(path)):", "    if False:"),
 ("parked: the job's subagents are not background work", "atlas/active.py",
  '"agents": live_subagents(path, job_path),', '"agents": live_subagents(path),'),
 ("parked: a subagent linked into the job counted twice", "atlas/active.py",
  "fresh.add(os.path.realpath(path))", "fresh.add(path)"),
 ("parked: card cost without the job's replies", "atlas/active.py",
  "cost = costs.parked_cost(path, job_path) if job_path else costs.session_cost(path)",
  "cost = costs.session_cost(path)"),
 ("parked: the job's copies of the parent's replies are priced again", "atlas/costs.py",
  "if ts > handed_over)", ")"),
 ("parked: a job scanned without rows adds nothing", "atlas/costs.py",
  "        _cache.pop(job)  ", "        pass  "),
 ("parked: the job's copied records are indexed again", "atlas/parse.py",
  "    return isinstance(ts, str) and ts <= facts.copied_until", "    return False"),
 ("parked: a parent that went on still counts as handed over", "atlas/parse.py",
  "                facts.continued_in = None     # the conversation went on here after all", "                pass"),
 ("parked: the hand-over is not looked up for the job", "atlas/store.py",
  "    parent, handed_over = continuation_of(conn, session_id)", "    parent, handed_over = None, None"),
 ("parked: a job indexed before its parent keeps the copies", "atlas/index.py",
  "        _relink_continuations(conn, stats)\n", ""),
 ("parked: a subagent linked into the job is indexed twice", "atlas/index.py",
  "if not foreign_link(p, folder))", "if True)"),
 ("parked: a job without a prompt of its own becomes automation", "atlas/resolve.py",
  "if human_turns == 0 and not continued:", "if human_turns == 0:"),
 ("tasks: count deleted ones", "atlas/tasks.py",
  'if not isinstance(task, dict) or task.get("status") == "deleted":', 'if not isinstance(task, dict):'),
 ("tasks: order by file name, not by number", "atlas/tasks.py",
  '"*.json")), key=_number):', '"*.json"))):'),
 ("tasks: empty without activeForm", "atlas/tasks.py",
  't["active_form"] or t["subject"] for t in items', 't["active_form"] for t in items'),
 ("stats: do not collapse reply copies", "atlas/stats.py",
  "   GROUP BY a.key)", "   GROUP BY a.key, a.session_id, a.ts)"),
 ("stats: pauses count as work", "atlas/activity.py",
  "return gap if gap <= IDLE_SECONDS else 0.0", "return gap"),
 ("stats: subagent time counts as work", "atlas/activity.py",
  "0.0 if sub else r[\"active_s\"]", "r[\"active_s\"]"),
 ("stats: the gap is not credited to the reply", "atlas/activity.py",
  "    row[\"active_s\"] += facts.pending_active\n", ""),
 ("stats: an incrementally read reply overwrites the time", "atlas/activity.py",
  "active_s = active_s + excluded.active_s", "active_s = excluded.active_s"),
 ("stats: do not merge parallel sessions", "atlas/stats.py",
  "if cur_end is None or start > cur_end:", "if True:"),
 ("stats: MCP per call", "atlas/stats.py",
  "return \"tools\", \"MCP \" + name.split(\"__\")[1]", "return \"tools\", name"),
 ("stats: skill without a name", "atlas/activity.py",
  "name = \"Skill:\" + str(args[\"skill\"])", "pass"),
 ("stats: slash command not shown", "atlas/activity.py",
  "\"tools\": _command(rec)}", "\"tools\": []}"),
 ("stats: period without a start", "atlas/stats.py",
  "WHERE a.ts >= :since AND", "WHERE 1 AND"),
 ("parse: index tool_result", "atlas/parse.py",
  'if block.get("type") != _TEXT_BLOCK:\n            continue  # tool_result / image / document: never indexed',
  'if False:\n            continue'),
 ("parse: treat the compaction summary as a prompt", "atlas/parse.py",
  'if text.startswith(COMPACT_PREFIX):', 'if False:'),
 ("parse: read an unfinished line too", "atlas/parse.py",
  'if not raw.endswith(b"\\n"):\n            break', 'if False:\n            break'),
 ("index: always treat the file as unchanged", "atlas/index.py",
  'return row is None or row["sig"] != sig', 'return row is None'),
 ("index: ignore subagents in the signature", "atlas/index.py",
  'for path in [session_path, *subagents]:', 'for path in [session_path]:'),
 ("query: stem identifiers and numbers", "atlas/query.py",
  'if IDENTIFIER_RE.search(word):\n        return "exact"', 'if False:\n        return "exact"'),
 ("resolve: a file in the ~/Code root becomes a project", "atlas/resolve.py",
  'if rel_to_prefix == name and (name.startswith(".") or os.path.splitext(name)[1]):',
  'if False:'),
 ("resolve: claude-desktop goes to automation", "atlas/resolve.py",
  'if entrypoint in HEADLESS_ENTRYPOINTS or spawned:', 'if (entrypoint and entrypoint != "cli") or spawned:'),
 ("search: show automation by default", "atlas/search.py",
  'if not include_automation and not kinds:\n        where.append("s.session_kind = \'interactive\'")',
  'if False:\n        where.append("s.session_kind = \'interactive\'")'),
 ("index: do not clear old rows before writing", "atlas/store.py",
  '    purge(conn, session_id)\n    activity.store(', '    activity.store('),
 ("index: incremental read without clearing metadata", "atlas/store.py",
  '    purge(conn, session_id, keep_text=True)\n', ''),
 ("index: incremental read does not rewrite the last turn", "atlas/store.py",
  'conn.execute("DELETE FROM fts WHERE session_id=? AND turn>=?", (session_id, first))', 'pass'),
 ("index: read incrementally after a rewritten file", "atlas/store.py",
  'or row["sub_sig"] != sub_sig or tail_sig(path, row["offset"]) != row["tail_sig"]:',
  'or row["sub_sig"] != sub_sig:'),
 ("index: do not remove vanished sources", "atlas/index.py",
  'if path not in present:', 'if False:'),
 ("db: rebuild also wipes manual edits", "atlas/db.py",
  'DERIVED = (', 'DERIVED = ("user_overrides",\n'),
 ("resolve: a scratchpad becomes a project", "atlas/resolve.py",
  'if SCRATCHPAD_RE.match(p):', 'if False:'),
 ("resolve: sensitivity defaults to normal", "atlas/resolve.py",
  'return UNCLASSIFIED', 'return "normal"'),
 ("resolve: path comparison via startswith", "atlas/resolve.py",
  'return os.path.commonpath([os.path.normpath(path), root]) == root',
  'return os.path.normpath(path).startswith(root)'),
 ("query: no truncation to the stem", "atlas/query.py",
  'return token[: max(STEM_FLOOR, n - cut)]', 'return token'),
 ("query: always cut the trailing consonant of a stem", "atlas/query.py",
  'if not cut and low[-1] in _SOFT_TAIL:', 'if not cut:'),
 ("query: short Russian words without word forms", "atlas/query.py",
  'if SHORT_CYR_RE.match(word):\n        return "forms"', 'if False:\n        return "forms"'),
 ("query: OR works as AND", "atlas/query.py",
  'parsed.groups[-1].append(term)', 'parsed.groups.append([term])'),
 ("query: minus does not exclude", "atlas/query.py",
  'parsed.excluded.append(term)', 'parsed.groups.append([term])'),
 ("query: the match is not highlighted", "atlas/query.py",
  'add(text[a:b], True)', 'add(text[a:b], False)'),
 ("query: snippet window ignores distinct words", "atlas/query.py",
  'key = (len(set(inside)), len(inside))', 'key = (0, 0)'),
 ("search: do not report the matched field", "atlas/search.py",
  'if not hits:\n                continue\n            distinct', 'if True:\n                continue\n            distinct'),
 ("search: snippet from the first turn, not the best one", "atlas/search.py",
  'if (distinct, hits) > slot["_best"]:', 'if slot["_best"] == (-1, -1):'),
 ("search: the title counts in the total match count", "atlas/search.py",
  'body = [m for m in matches if m["field"] != "title"] or matches', 'body = matches'),
 ("search: total covers only the page", "atlas/search.py",
  'out["total"] = len(rows)', 'out["total"] = len(rows[:limit])'),
 ("search: stay silent about matches outside prompts", "atlas/search.py",
  'if scope == "prompts":\n        wide', 'if False:\n        wide'),
 ("search: relevance is plain bm25", "atlas/search.py",
  'return sorted(cands, key=lambda c: (c[0] not in in_title, -pairs[c[0]], position[c[0]]))',
  'return cands'),
 ("db: write the schema on every connection", "atlas/db.py",
  'if _schema_is_current(conn):\n        return conn', 'if False:\n        return conn'),
 ("server: do not catch up the index for the list", "atlas/server.py",
  'indexing = catch_up()', 'indexing = False'),
 ("server: catch up on every keystroke", "atlas/server.py",
  'if time.monotonic() - _catchup_at < (DUE_RETRY if now else CATCHUP_EVERY):\n            return False',
  'if False:\n            return False'),
 ("server: wait for another process's running pass too", "atlas/server.py",
  'return True     # do not wait for another pass', 'current = _catchup_proc  # do not wait for another pass'),
 ("server: wait for a long pass to finish", "atlas/server.py",
  'current.join(CATCHUP_WAIT)', 'current.join()'),
 ("actions: do not escape command arguments", "atlas/actions.py",
  'return f"cd {shlex.quote(cwd)} && " + " ".join(shlex.quote(p) for p in parts)\n\n\ndef new_session_command',
  'return f"cd {cwd} && " + " ".join(parts)\n\n\ndef new_session_command'),
 ("actions+db: both the early return and the UNIQUE index removed", "atlas/db.py",
  "CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_active", "CREATE INDEX IF NOT EXISTS ux_jobs_active"),
 ("runner: send data out without permission", "atlas/runner.py",
  'raise EgressDenied(', 'return None or EgressDenied('),
 ("runner: treat litellm as local", "atlas/runner.py",
  'LOCAL_BACKENDS = {"ollama", "lmstudio", "llamacpp"}',
  'LOCAL_BACKENDS = {"ollama", "lmstudio", "llamacpp", "claude-cli"}'),
 ("enrich: repair broken JSON heuristically", "atlas/enrich.py",
  'raise ValueError(msg("enrich.no_json"))', 'return {"did": text}'),
 ("enrich: do not require handoff sections", "atlas/enrich.py",
  'if missing:', 'if False:'),
 ("server: accept a foreign Origin", "atlas/server.py",
  'if origin and origin not in ALLOWED_ORIGINS:', 'if False:'),
 ("server: do not check the CSRF token", "atlas/server.py",
  'if self.headers.get("X-Atlas-Token") != csrf_token():', 'if False:'),
 ("server: accept any export target", "atlas/server.py",
  'if label not in destinations:', 'if False:'),
 ("search: domain rule outranks the model's verdict", "atlas/search.py",
  'elif verdict and verdict["domain"]:\n        final_domains, domain_source = [verdict["domain"]], "llm"\n    elif domains:\n        final_domains, domain_source = domains, "rule"',
  'elif domains:\n        final_domains, domain_source = domains, "rule"\n    elif verdict and verdict["domain"]:\n        final_domains, domain_source = [verdict["domain"]], "llm"'),
 ("search: a manual topic does not override the model", "atlas/search.py",
  '"topic": ((override["topic"] if override and override["topic"] else None)\n                  or (verdict["topic"] if verdict else None)),',
  '"topic": (verdict["topic"] if verdict else None),'),
 ("db: classification back in the cheap derived table", "atlas/db.py",
  'DERIVED = (\n    "sources", "sessions"', 'DERIVED = (\n    "classification", "enrichment",\n    "sources", "sessions"'),
 ("db: a schema upgrade does not request a rebuild", "atlas/db.py",
  "conn.execute(\"INSERT INTO meta(key, value) VALUES('needs_reindex', '1') \"\n                 \"ON CONFLICT(key) DO UPDATE SET value='1'\")",
  "pass"),
 ("index: ensure_indexed does nothing", "atlas/index.py",
  '    if not reindex_due(conn):\n        return None',
  '    if True:\n        return None'),
 ("classify: sensitive sessions are sent out", "atlas/classify.py",
  "AND COALESCE((SELECT sensitivity FROM user_overrides u WHERE u.session_id = s.session_id),\n                       s.sensitivity_rule) != 'sensitive'", "AND 1=1"),
 ("classify: «misc» with high confidence passes", "atlas/classify.py",
  'and confidence >= 0.5:', 'and False:'),
 ("classify: a non-canonical domain is accepted", "atlas/classify.py",
  'if ids and domain not in ids:', 'if False:'),
 ("parse: do not expand the slash command", "atlas/parse.py",
  'prompt = readable_prompt(text)', 'prompt = text'),
 ("search: do not strip the summary preamble", "atlas/search.py",
  'if marker in summary[:400]:', 'if False:'),
 ("classify: do not return the one-line description", "atlas/classify.py",
  'summary = " ".join((data.get("summary") or "").split())[:200]', 'summary = None'),
 ("runner: summaries and prompts are cut first", "atlas/runner.py",
  'take(t_summaries, facts.summaries)\n    take(t_prompts, facts.user_text)\n    take(t_answers, facts.assistant_text)',
  'take(t_answers, facts.assistant_text)\n    take(t_summaries, facts.summaries)\n    take(t_prompts, facts.user_text)'),
 ("runner: take replies from the start, not the end", "atlas/runner.py",
  'for text in reversed(items):', 'for text in items:'),
 ("runner: chars per token as for English", "atlas/runner.py",
  'CHARS_PER_TOKEN = 2.1', 'CHARS_PER_TOKEN = 4.0'),
 ("runner: do not pre-check a large call", "atlas/runner.py",
  'if len(prompt) > PREFLIGHT_ABOVE:\n        preflight(effort=effort)', 'pass'),
 ("search: do not limit prompt length in the card", "atlas/search.py",
  '    if len(out) <= limit:\n        return out', '    return out'),
 ("web: a long path in the snippet stretches the card", "web/js/atlas.css",
  'white-space:pre-wrap;overflow-wrap:anywhere}', 'white-space:pre-wrap}'),
 ("runner: look for claude only in PATH", "atlas/runner.py",
  '''    for candidate in CLAUDE_CANDIDATES:
        path = os.path.expanduser(candidate)
        if os.access(path, os.X_OK):
            return path
''', ''),
 ("actions: renaming overwrites the transcript", "atlas/actions.py",
  'with open(row["source_path"], "a", encoding="utf-8") as fh:',
  'with open(row["source_path"], "w", encoding="utf-8") as fh:'),
 ("search: a manual title does not override the recorded one", "atlas/search.py",
  '"title": (override["title"] if override and override["title"] else row["title"]),',
  '"title": row["title"],'),
 ("db: do not migrate the old schema", "atlas/db.py",
  'if int(row["value"]) >= SCHEMA_VERSION:\n        return', 'if True:\n        return'),
 ("active: accept a foreign process with the same PID", "atlas/active.py",
  'return proc_start is None or table[pid][1] == " ".join(proc_start.split())', 'return True'),
 ("active: show background runs", "atlas/active.py",
  'return data.get("kind") == "interactive" and data.get("entrypoint") not in HEADLESS_ENTRYPOINTS',
  'return True'),
 ("active: do not sort by the last message", "atlas/active.py",
  'out.sort(key=lambda s: _as_datetime(s["last_message_at"]), reverse=True)', 'pass'),
 ("active: freshness only from the index", "atlas/active.py",
  'tail = found["last_at"]', 'tail = None'),
 ("active: notifications and summaries count as a message", "atlas/active.py",
  'return kind == "assistant" or not text.startswith(NOT_A_MESSAGE)', 'return True'),
 ("active: do not look past a tail of tool calls", "atlas/active.py",
  'window *= 4           # a tail made only of tool calls', 'return out            # a tail made only of tool calls'),
 ("runner: handoff without the 1M window", "atlas/runner.py",
  'NATIVE_1M = {"claude-opus-5-5"}', 'NATIVE_1M = set()'),
 ("active: reply tail is the start, not the end", "atlas/active.py",
  '    tail = text[cut:]\n', '    tail = text[:limit]\n'),
 ("active: waiting_for on an idle session too", "atlas/active.py",
  'return own.get("status"), own.get("waitingFor") if own.get("status") == "waiting" else None',
  'return own.get("status"), own.get("waitingFor")'),
 ("uploads: accept any bytes as an image", "atlas/uploads.py",
  'if ext is None:\n        raise UploadError', 'if False:\n        raise UploadError'),
 ("uploads: the file is world-readable", "atlas/uploads.py",
  'os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600', 'os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644'),
 ("uploads: do not clean up old ones", "atlas/uploads.py",
  'if now - os.stat(path).st_mtime > KEEP_SECONDS:', 'if False:'),
 ("active: do not count shell status as work", "atlas/active.py",
  'if status in ("busy", "shell"):', 'if status == "busy":'),
 ("active: a lone /goal already counts as «in background»", "atlas/active.py",
  'if background["shells"] or background["agents"] or background["wake_at"] \\',
  'if background["goal"] or background["shells"] or background["agents"] or background["wake_at"] \\'),
 ("active: count MCP servers as background commands", "atlas/active.py",
  'if row[0] == pid and len(row) > 2 and SHELL_TASK_MARK in row[2])',
  'if row[0] == pid and len(row) > 2)'),
 ("active: a past wakeup still waits", "atlas/active.py",
  'if wake and wake > now:', 'if wake:'),
 ("active: do not reopen a code block in the tail", "atlas/active.py",
  'return (FENCE + "\\n" + tail) if fences % 2 else tail', 'return tail'),
 ("active: cut the tail mid-line", "atlas/active.py",
  'if 0 <= line < len(text) - 1:\n        cut = line + 1', 'if False:\n        cut = line + 1'),
 ("active: treat command output as the user's message", "atlas/active.py",
  '"<local-command-stdout>", ', ''),
 ("active: command with tags, not as typed", "atlas/active.py",
  '    m = _COMMAND_RE.search(text)\n    if m:', '    m = None\n    if m:'),
 ("costs: count one reply per line", "atlas/costs.py",
  'if key in seen or msg.get("model") == SYNTHETIC:', 'if msg.get("model") == SYNTHETIC:'),
 ("costs: 1-hour cache write priced as 5-minute", "atlas/costs.py",
  'WRITE_5M, WRITE_1H = 1.25, 2.0', 'WRITE_5M, WRITE_1H = 1.25, 1.25'),
 ("costs: do not reset incremental counting on writes", "atlas/costs.py",
  'recorded, stamp, after = float(rec["totalCostUSD"]), last_ts, 0.0',
  'recorded, stamp = float(rec["totalCostUSD"]), last_ts'),
 ("costs: count subagents before the write too", "atlas/costs.py",
  'if stamp and ts > stamp)', ')'),
 ("costs: internal replies are a model without a price", "atlas/costs.py",
  'if key in seen or msg.get("model") == SYNTHETIC:', 'if key in seen:'),
 ("autoclassify: on by default", "atlas/autoclassify.py",
  'return _meta(conn, KEY_ENABLED) == "1"', 'return _meta(conn, KEY_ENABLED) != "0"'),
 ("autoclassify: no hourly pause", "atlas/autoclassify.py",
  'if last and now - float(last) < INTERVAL_SECONDS:', 'if False:'),
 ("autoclassify: classified sessions without a mark are all recomputed", "atlas/autoclassify.py",
  'if r["done"] and r["seen"] is None:', 'if False:'),
 ("autoclassify: changes go unnoticed", "atlas/autoclassify.py",
  'elif not r["done"] or r["seen"] != r["sig"]:', 'elif not r["done"]:'),
 ("autoclassify: no per-pass limit", "atlas/autoclassify.py", 'return out[:MAX_PER_RUN]', 'return out'),
 ("autoclassify: runs on top of a running classification", "atlas/autoclassify.py",
  'if not enabled(conn) or not runner.llm_enabled() or _job_running(conn):',
  'if not enabled(conn) or not runner.llm_enabled():'),
 ("autoclassify: fresh sessions too", "atlas/autoclassify.py",
  "WHERE s.session_kind = 'interactive' AND s.started_at <= ?",
  "WHERE s.session_kind = 'interactive' AND ? IS NOT NULL"),
 ("autoclassify: sensitive sessions are sent out", "atlas/autoclassify.py",
  "'unclassified') != 'sensitive'", "'unclassified') != 'никогда'"),
 ("autoclassify: no «What was done»", "atlas/autoclassify.py", '            summary(conn, sid, job_id)\n', ''),
 ("autoclassify: no mark after a pass", "atlas/autoclassify.py",
  '        _mark(conn, sid, sig)                  # on failure', '        pass                  # on failure'),
 ("autoclassify: «What was done» without an egress grant", "atlas/autoclassify.py",
  '    runner.grant_egress(conn, session_id, payload["content_hash"], SUMMARY_KIND,\n'
  '                        runner.EXTERNAL_BACKEND, model)\n', ''),
 ("server: every Active poll recomputes", "atlas/server.py",
  'time.monotonic() - _active_cached["at"] < ACTIVE_REUSE_SECONDS:', 'False:'),
 ("active: an interruption counts as a message", "atlas/active.py",
  '"A session-scoped Stop hook is now active", "Caveat: The messages below",\n                 "[Request interrupted by user")',
  '"A session-scoped Stop hook is now active", "Caveat: The messages below")'),
 ("active: an interruption is not marked", "atlas/active.py",
  'out["interrupted_at"] = rec.get("timestamp")', 'pass'),
 ("launch: the typed folder is not checked", "atlas/launch.py",
  "        cwd = folders.check(cwd)\n", "        pass\n"),
 ("folders: a relative path is taken as is", "atlas/folders.py",
  "    return None\n\n\ndef resolve", "    return text\n\n\ndef resolve"),
 ("folders: .. walks out of the typed folder", "atlas/folders.py",
  'if ".." in path.split("/"):', "if False:"),
 ("folders: a file passes as a folder", "atlas/folders.py",
  "    if not os.path.isdir(path):\n        raise FolderError", "    if False:\n        raise FolderError"),
 ("folders: a temporary folder is accepted", "atlas/folders.py",
  "    if (path + \"/\").startswith(SKIP_PREFIXES):", "    if False:"),
 ("folders: hidden subfolders are suggested", "atlas/folders.py",
  "                if entry.name.startswith(\".\"):\n                    continue", "                pass"),
 ("folders: files are suggested as folders", "atlas/folders.py",
  "                    if entry.is_dir():", "                    if True:"),
 ("folders: a root lists its siblings, not what is inside", "atlas/folders.py",
  'at_root = raw.endswith("/") or', 'at_root = False and'),
 ("launch: the prompt is not escaped", "atlas/actions.py",
  '        parts.append(prompt_word(prompt))\n    return f"cd {shlex.quote(cwd)} && " + " ".join(shlex.quote(p) for p in parts)',
  '        parts.append(prompt_word(prompt))\n    return f"cd {shlex.quote(cwd)} && " + " ".join(parts)'),
 ("launch: a session scratchpad in the list", "atlas/launch.py",
  'and "/scratchpad" not in path', 'and True'),
 ("launch: hidden folders in the list", "atlas/launch.py",
  'and not any(part.startswith(".") for part in path.split(os.sep))', ''),
 ("queue: dequeue does not remove", "atlas/prompt_queue.py",
  'elif op == "dequeue":\n            if queue:\n                queue.pop(0)', 'elif op == "dequeue":\n            pass'),
 ("queue: dequeue removes from the end", "atlas/prompt_queue.py",
  'if queue:\n                queue.pop(0)', 'if queue:\n                queue.pop()'),
 ("queue: popAll does not clear", "atlas/prompt_queue.py", 'queue.clear()', 'pass'),
 ("queue: notifications are shown as prompts", "atlas/prompt_queue.py",
  'if q["text"].strip() and not q["text"].startswith(SYSTEM_PREFIXES)]', 'if q["text"].strip()]'),
 ("queue: remove by position, not by text", "atlas/prompt_queue.py",
  'same = [i for i, q in enumerate(queue) if content and q["text"] == content]', 'same = [0] if queue else []'),
 ("feed: the window does not grow", "atlas/feed.py", 'window *= 4', 'return built[-turns:]'),
 ("feed: a notification starts a new turn", "atlas/feed.py",
  'if kind == "user" and active.is_message(rec):', 'if kind == "user":'),
 ("feed: edited files counted by calls", "atlas/feed.py",
  'files = len(g["detail"]) or n\n            text = nplural("feed.edited"', 'files = n\n            text = nplural("feed.edited"'),
 ("feed: the reply is the turn's first text", "atlas/feed.py",
  'turn["reply"] = block["text"].strip()', 'turn["reply"] = turn["reply"] or block["text"].strip()'),
 ("feed: an interruption is not marked", "atlas/feed.py", 'turn["interrupted"] = True', 'pass'),
 ("feed: the tail of an earlier turn shows up", "atlas/feed.py",
  '        if not turns:\n            continue', '        if not turns:\n            turns.append(_new_turn(rec))'),
 ("commands: a skill named by its name field", "atlas/commands.py",
  'out.append({"name": prefix + name, "kind": kind,',
  'out.append({"name": prefix + (_frontmatter(md).get("name") or name), "kind": kind,'),
 ("commands: a built-in command is duplicated", "atlas/commands.py",
  '        if c["name"] not in seen:', '        if True:'),
 ("commands: internal skills in the list", "atlas/commands.py",
  'if name.startswith(("_", ".")) or not os.path.isfile(md):', 'if not os.path.isfile(md):'),
 ("context: the window is always 200k", "atlas/costs.py",
  'if tokens and tokens > WINDOW_DEFAULT:\n        return WINDOW_1M', 'if False:\n        return WINDOW_1M'),
 ("context: a subagent changes the session context", "atlas/costs.py",
  'if not rec.get("isSidechain"):\n            ctx, model', 'if True:\n            ctx, model'),
 ("context: cache writes not counted", "atlas/costs.py",
  '("input_tokens", "cache_read_input_tokens", "cache_creation_input_tokens"))', '("input_tokens", "cache_read_input_tokens"))'),
 ("limits: a reset given as a string is not read", "atlas/limits.py",
  'if value.replace(".", "").isdigit():\n            return _iso(float(value))', 'if False:\n            return None'),
 ("statusline: garbage overwrites the file", "atlas/statusline.py",
  'if isinstance(data, dict) and _has_window(data.get("rate_limits")):',
  'if isinstance(data, dict) and isinstance(data.get("rate_limits"), dict):'),
 ("statusline: crashes on garbage", "atlas/statusline.py",
  'limits = limits if isinstance(limits, dict) else {}', 'limits = limits or {}'),
 ("relocate: a session already in Obsidian is killed too", "atlas/relocate.py",
  'if app == "Obsidian":\n        raise RelocateError(msg("relocate.in_obsidian"))', 'if False:\n        pass'),
 ("relocate: a foreign session by PID", "atlas/relocate.py",
  'if data.get("sessionId") != session_id or not active.is_interactive(data):',
  'if not active.is_interactive(data):'),
 ("relocate: a reused PID", "atlas/relocate.py",
  'if not active._alive(pid, start, table):\n            raise',
  'if pid not in table:\n            raise'),
 ("relocate: a zombie counts as alive", "atlas/relocate.py",
  '\n        or _command(table, pid).strip() == "<defunct>"', ''),
 ("relocate: the app is the nearest .app", "atlas/relocate.py",
  '        if m:\n            found = m.group(1)\n    return found', '        if m:\n            return m.group(1)\n    return found'),
 ("models: force_1m does not add the [1m] suffix", "atlas/runner.py",
  '        model += "[1m]"\n', '        pass\n'),
 ("models: «What was done» on medium", "atlas/config.py",
  '"catalog_summary": ["sonnet", "low"],', '"catalog_summary": ["sonnet", "medium"],'),
 ("enrich: «What was done» template via format", "atlas/enrich.py",
  'return template.replace("{payload}", text)', 'return template.format(payload=text)'),
 ("commands: frequent ones not first", "atlas/commands.py",
  'return first + rest', 'return sorted(pool, key=lambda c: c["name"].lower())'),
 ("commands: a disabled plugin in the list", "atlas/commands.py",
  '(entry.get("scope") != "user" or enabled.get(full))', 'True'),
 ("commands: no organization plugins", "atlas/commands.py",
  '    for manifest in glob.glob(', '    for manifest in []:  # glob.glob('),
 ("codex: a repeated token_count counts as a second reply", "atlas/codex_parse.py",
  "        if signature == self.last_total:\n            return\n", ""),
 ("codex: cached input counted as fresh input", "atlas/codex_parse.py",
  'max(0, int(usage.get("input_tokens") or 0) - cached - written)',
  'max(0, int(usage.get("input_tokens") or 0) - written)'),
 ("codex: reasoning counted twice in output", "atlas/codex_parse.py",
  '"output": int(usage.get("output_tokens") or 0),',
  '"output": int(usage.get("output_tokens") or 0) + int(usage.get("reasoning_output_tokens") or 0),'),
 ("codex: cache writes counted as fresh input", "atlas/codex_parse.py",
  "- cached - written)", "- cached)"),
 ("codex: stats ignore the agent filter", "atlas/stats.py",
  "    if agents:\n        params.update", "    if False:\n        params.update"),
 ("codex: previous period ignores the agent filter", "atlas/stats.py",
  "since - (until - since), since, automation, agents)", "since - (until - since), since, automation)"),
 ("codex: Codex replies left unpriced in stats", "atlas/stats.py",
  'if r["agent"] == CODEX and r["kind"] == "a":', 'if False:'),
 ("codex: an unpriced period shows $0", "atlas/stats.py",
  'round(t["cost"], 2) if t["priced"] or not unknown else None', 'round(t["cost"], 2)'),
 ("codex: an unpriced breakdown row shows $0", "atlas/stats.py",
  'round(v["cost"], 2) if v["priced"] or not v["answers"] else None', 'round(v["cost"], 2)'),
 ("codex: by_agent sessions counted per row", "atlas/stats.py",
  'agent_sessions[r["agent"]].add(r["sid"])', 'agent_sessions[r["agent"]].add(r["key"])'),
 ("codex: cached input billed at the full input price", "atlas/openai_costs.py",
  "(pin if cached_price is None else cached_price)", "pin"),
 ("codex: an empty token_count counts as an unpriced model", "atlas/openai_costs.py",
  "        return 0.0              # Codex writes", "        pass                    # Codex writes"),
 ("codex: config price override ignored", "atlas/openai_costs.py",
  "if isinstance(overrides, dict) and name in overrides:", "if False:"),
 ("codex: a null override keeps the built-in price", "atlas/openai_costs.py",
  "        if fixed is None:\n            return None\n", "        if fixed is None:\n            fixed = {}\n"),
 ("codex: a prompt reported as event and item counts twice", "atlas/codex_parse.py",
  "        if other.get(text):", "        if False:"),
 ("codex: prompts sharing a timestamp collapse", "atlas/codex_parse.py",
  ':{hashlib.sha1(text.encode()).hexdigest()[:12]}"', '"'),
 ("codex: the line-head skip swallows tool calls", "atlas/codex_parse.py",
  'rb\'"type":\\s*"response_item".{0,80}"payload":\\s*\\{"type":\\s*"(?:message|reasoning|\'',
  'rb\'"type":\\s*"response_item".{0,80}"payload":\\s*\\{"type":\\s*"(?:message|function_call|reasoning|\''),
 ("codex: a fork's second session_meta overrides the thread", "atlas/codex_parse.py",
  "    if r.meta_seen:\n        return\n", ""),
 ("codex: compaction summary dropped", "atlas/codex_parse.py",
  '                facts.summaries.append(summary)\n', ''),
 ("codex: codex exec counted as interactive", "atlas/resolve.py",
  '"sdk-py", "codex_exec"}', '"sdk-py"}'),
 ("codex: subagent thread counted as interactive", "atlas/resolve.py",
  "if entrypoint in HEADLESS_ENTRYPOINTS or spawned:", "if entrypoint in HEADLESS_ENTRYPOINTS:"),
 ("codex: a Codex session is stored as claude", "atlas/store.py",
  "hexdigest()[:32], facts.agent,", 'hexdigest()[:32], "claude",'),
 ("codex: Codex's own title ignored", "atlas/index.py",
  'title = titles.get(codex_parse.session_id_of(path) or "")', "title = None"),
 ("codex: a rename in Codex does not reindex", "atlas/index.py",
  '    return sig + ("|t:" + hashlib.sha1(title.encode()).hexdigest()[:12] if title else "")',
  "    return sig"),
 ("codex: an archived rollout's session is purged", "atlas/index.py",
  "                if not moved:\n", "                if True:\n"),
 ("codex: agent filter ignored in search", "atlas/search.py",
  "    if agents:\n        where.append(f\"s.agent IN", "    if False:\n        where.append(f\"s.agent IN"),
 ("codex: unknown agent values narrow the filter", "atlas/agents.py",
  "if part in ALL and part not in picked:", "if part and part not in picked:"),
 ("codex: resume command is Claude's for Codex", "atlas/actions.py",
  '    if agent == "codex":\n        if fork:', '    if False:\n        if fork:'),
 ("codex: rename appends to a Codex rollout", "atlas/actions.py",
  '        elif row["agent"] != "claude":', '        elif False:'),
 ("codex: AI payload read with the Claude parser", "atlas/runner.py",
  'agents.parse_session(row["source_path"], session_id, row["agent"])',
  'agents.parse_session(row["source_path"], session_id, "claude")'),
 # --- Active, feed, move and delete for Codex ---
 ("codex: active: codex exec gets a card", "atlas/codex_procs.py",
  "        return word not in NOT_INTERACTIVE", "        return True"),
 ("codex: active: an option's value read as the subcommand", "atlas/codex_procs.py",
  "            skip = word in VALUE_FLAGS", "            skip = False"),
 ("codex: active: a rollout outside the Codex home accepted", "atlas/codex_procs.py",
  " and _inside(path, home) and ", " and "),
 ("codex: active: lsof runs on every poll", "atlas/codex_procs.py",
  "if fresh or key not in _map_cache or now - _map_cache[key][0] > MAP_TTL]", "if True]"),
 ("codex: active: no command-line fallback without lsof", "atlas/codex_procs.py",
  "(0.0, _from_argv(table[pid][2], home))", "(0.0, None)"),
 ("codex: active: a subagent rollout becomes the card", "atlas/codex_procs.py",
  'own = [p for p in paths if not session_meta(p).get("subagent")] or paths', "own = paths"),
 ("codex: active: a running turn shown idle", "atlas/codex_tail.py",
  '"busy" if kind == "task_started" else "idle"', '"idle"'),
 ("codex: active: an aborted turn not reported", "atlas/codex_tail.py",
  'if kind == "turn_aborted" and out["last_at"] is None', 'if False and out["last_at"] is None'),
 ("codex: active: the reply in task_complete ignored", "atlas/codex_tail.py",
  '                self.reply(p.get("last_agent_message"), ts)', "                pass"),
 ("codex: active: an answered prompt shown as unanswered", "atlas/codex_tail.py",
  'if not self.replied and out["prompt"] is None:', 'if out["prompt"] is None:'),
 ("codex: active: Codex cards left out", "atlas/active.py",
  "    out += codex_live.list_live(conn, table, run=run, home=codex_home)\n", ""),
 ("codex: active: two processes on one thread make two cards", "atlas/codex_live.py",
  'if made and made["session_id"] not in seen:', "if made:"),
 ("codex: active: agent filter ignored on /api/active", "atlas/server.py",
  'if not picked or s.get("agent", agents.CLAUDE) in picked]', "if True]"),
 ("codex: active: recently closed ignore the agent filter", "atlas/active.py",
  'f" AND s.agent IN (', 'f" AND s.agent NOT IN ('),
 ("codex: active: empty limit windows hide older limits", "atlas/codex_tail.py",
  'any(isinstance(rl.get(k), dict) for k in ("primary", "secondary"))', "True"),
 ("codex: active: Codex limits keyed apart from Claude's", "atlas/codex_tail.py",
  "        key = WINDOW_KEYS.get(minutes, name)", "        key = name"),
 ("codex: limits: a per-model bucket in a rollout stands in for the account's", "atlas/codex_tail.py",
  'rl.get("limit_id") in (None, "codex")', "True"),
 ("codex: usage: the codex bucket of the multi-bucket view ignored", "atlas/codex_usage.py",
  "if isinstance(by_id, dict) and _has_windows(by_id.get(BUCKET)):", "if False:"),
 ("codex: usage: a foreign single bucket taken", "atlas/codex_usage.py",
  'single.get("limitId") in (None, BUCKET)', "True"),
 ("codex: usage: no cache, Codex asked on every poll", "atlas/codex_usage.py",
  'due = _state["tried"] is None or time.monotonic() - _state["tried"] >= TTL', "due = True"),
 ("codex: usage: Codex asked without the page asking", "atlas/codex_usage.py",
  "go = start and due", "go = due"),
 ("codex: usage: a hung app server is waited for", "atlas/codex_usage.py",
  "_lines(proc.stdout.fileno(), time.monotonic() + timeout)", "_lines(proc.stdout.fileno(), time.monotonic() + 30)"),
 ("codex: usage: a failed read drops the last good numbers", "atlas/codex_usage.py",
  'if _state["home"] == home and data is not None:', 'if _state["home"] == home:'),
 ("codex: usage: old live numbers beat a newer rollout", "atlas/codex_live.py",
  'if asked and (not seen or (asked["captured_at"] or "") >= (seen["captured_at"] or "")):', "if asked:"),
 ("codex: usage: the plugin's poll starts a read", "atlas/server.py",
  'live=(query.get("codex_usage") or [""])[0] == "1"', "live=True"),
 ("limits: an old status line file called live", "atlas/limits.py",
  '"live": age is not None and age <= LIVE_FOR}', '"live": True}'),
 ("codex: feed: a rollout read as a Claude transcript", "atlas/feed.py",
  "    if codex_parse.session_id_of(path):\n        return codex_feed.records(lines)",
  "    if False:\n        return codex_feed.records(lines)"),
 ("codex: feed: a failed command looks fine", "atlas/codex_feed.py",
  "    if code in (None, 0):", "    if True:"),
 ("codex: feed: event and item copies doubled", "atlas/codex_feed.py",
  "if not text or self.last[role] == text:", "if not text:"),
 ("codex: feed: a real repeated prompt dropped", "atlas/codex_feed.py",
  '        self.last["assistant" if role == "user" else "user"] = None', "        pass"),
 ("codex: feed: an aborted turn not interrupted", "atlas/codex_feed.py",
  "            return [_user(ts, INTERRUPTED)]", "            return []"),
 ("codex: feed: a failed patch listed as a changed file", "atlas/codex_feed.py",
  "    if failed or not isinstance(changes, dict):", "    if not isinstance(changes, dict):"),
 ("codex: feed: files view reads a rollout as Claude's", "atlas/touched.py",
  "    if codex_parse.session_id_of(path):\n        return codex_feed.session_files(path)",
  "    if False:\n        return codex_feed.session_files(path)"),
 ("codex: relocate: any process stopped as the thread", "atlas/relocate.py",
  "    if not codex_procs.owner(pid, session_id, table, run=run):\n        return None",
  "    if False:\n        return None"),
 ("codex: relocate: resume command is Claude's", "atlas/server.py",
  'agent = stopped.get("agent") or agents.session_agent(conn, sid)', "agent = None"),
 ("codex: delete: rollouts left on disk", "atlas/delete.py",
  '[("rollout", p) for p in codex_procs.all_rollouts(session_id)] if codex', "[] if codex"),
 ("codex: delete: a running thread gets deleted", "atlas/delete.py",
  '"running": _codex_running(session_id) if codex else is_running(session_id),',
  '"running": is_running(session_id),'),
 ("codex: delete: the Codex home is not the allowed root", "atlas/delete.py",
  "    home = index.codex_home() if codex else claude_home()\n    roots",
  "    home = claude_home()\n    roots"),
 ("codex: delete: Codex input history kept", "atlas/delete.py",
  'return rec.get("sessionId") or rec.get("session_id")', 'return rec.get("sessionId")'),
 ("codex: delete: no note about Codex's own list", "atlas/delete.py",
  '"notes": [msg("delete.codex_app_note")] if codex else [],', '"notes": [],'),
 ("codex launch: a Codex source starts Claude Code", "atlas/server.py",
  "actions.new_session_command(cwd, new_id, path, agent=agent)", "actions.new_session_command(cwd, new_id, path)"),
 ("codex launch: Codex launches share one handoff file", "atlas/actions.py",
  'return f"launch-{source_session_id[:8]}-{uuid.uuid4().hex[:12]}.md"', 'return f"launch-{source_session_id[:8]}.md"'),
 ("codex launch: a flag-like prompt becomes a flag", "atlas/actions.py",
  'return " " + prompt if prompt.startswith("-") or len(prompt.split()) < 2 else prompt',
  'return " " + prompt if len(prompt.split()) < 2 else prompt'),
 ("codex launch: a one-word prompt becomes a subcommand", "atlas/actions.py",
  'if prompt.startswith("-") or len(prompt.split()) < 2 else prompt', 'if prompt.startswith("-") else prompt'),
 ("codex launch: the new thread is never linked", "atlas/store.py",
  "    actions.link_codex_launch(conn, session_id, facts.first_user_text)\n", ""),
 ("codex launch: linked by any prompt, not the first", "atlas/store.py",
  "actions.link_codex_launch(conn, session_id, facts.first_user_text)",
  'actions.link_codex_launch(conn, session_id, "\\n".join(facts.user_text))'),
 ("codex launch: a Claude launch taken by a Codex thread", "atlas/actions.py",
  "if CODEX_HANDOFF_NAME.match(os.path.basename(path)) and path in first_prompt:", "if path in first_prompt:"),
 ("codex launch: one launch links every thread", "atlas/actions.py",
  '"SELECT new_session_id, handoff_path FROM pending_launches WHERE confirmed_at IS NULL "',
  '"SELECT new_session_id, handoff_path FROM pending_launches WHERE 1 "'),
 ("codex launch: a linked thread is linked again", "atlas/actions.py",
  '    if not first_prompt or conn.execute(\n            "SELECT 1 FROM pending_launches WHERE new_session_id=?", (session_id,)).fetchone():',
  "    if not first_prompt:"),
 ("codex launch: + Session ignores the agent", "atlas/server.py",
  'body.get("agent", agents.CLAUDE)))', "agents.CLAUDE))"),
 ("codex launch: any agent value accepted", "atlas/launch.py",
  '    if agent not in agents.ALL:\n        raise LaunchError(msg("launch.bad_agent"))\n', ""),
 ("codex launch: + Session gives Codex a made-up id", "atlas/launch.py",
  "session_id = str(uuid.uuid4()) if agent == agents.CLAUDE else None", "session_id = str(uuid.uuid4())"),
 ("codex launch: script ignores the first prompt", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'codex "${flags[@]}" "${first[@]}"', 'codex "${flags[@]}"'),
 ("codex launch: script repeats the prompt after a restart", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  '      upsert_resume_id codex "$instance" "prompt-sent"\n', ""),
 ("codex launch: script sends a flag-like prompt as a flag", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  '[[ "$SEED_PROMPT" == -* ]] && first=(" $SEED_PROMPT") || first=("$SEED_PROMPT")', 'first=("$SEED_PROMPT")'),
 ("codex launch: script sends the prompt to a restored tab", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'if [[ -z "$session_id" && "$SEED_MODE" == new && -n "${SEED_PROMPT//[[:space:]]/}" ]]; then',
  'if [[ "$SEED_MODE" == new && -n "${SEED_PROMPT//[[:space:]]/}" ]]; then'),
 ("script: Claude Code's config dir ignored", 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  'CLAUDE_HOME_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"', 'CLAUDE_HOME_DIR="$HOME/.claude"'),
 ('script: archived Codex threads are not found', 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  ' "$CODEX_ARCHIVED_DIR"/**/rollout-*-"$1".jsonl(N.))', ')'),
 ('script: a Codex thread is resumed only in the folder it ran in', 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  '  (( ${#found} > 0 ))\n}\n\n# Any project folder', '  (( ${#found} > 0 )) && codex_rollout_in_cwd "$found[1]"\n}\n\n# Any project folder'),
 ("script: a new tab claims another folder's thread", 'obsidian-plugin/scripts/agent-resume-terminal.zsh',
  '    codex_rollout_in_cwd "$file" || continue\n', ''),
 ('script: a running job is resumed after a restart', 'obsidian-plugin/scripts/agent-resume-terminal.zsh',
  'if [[ -n "$session_id" ]] && job="$(claude_live_job "$session_id")"; then', 'if false; then'),
 ('script: a running job is resumed from the catalog', 'obsidian-plugin/scripts/agent-resume-terminal.zsh',
  'elif [[ -z "$session_id" && "$SEED_MODE" == resume ]] && job="$(claude_live_job "$SEED_ID")"; then', 'elif false; then'),
 ('script: an attach seed of an ended job attaches', 'obsidian-plugin/scripts/agent-resume-terminal.zsh',
  '    if [[ -n "$job_session" ]] && ! claude_live_job "$job_session" >/dev/null', '    if false'),
 ('script: the attached job is not kept for a restart', 'obsidian-plugin/scripts/agent-resume-terminal.zsh',
  '  job_session="$(claude_job_session "$job")" && upsert_resume_id claude "$instance" "$job_session"\n', ''),
 ('script: any attach argument accepted', 'obsidian-plugin/scripts/agent-resume-terminal.zsh',
  '{ [[ "$APP" != claude ]] || ! valid_job_id "$SEED_ID"; }', 'false'),
 ('script: the job id check is loose', 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  '[[ "$1" =~ \'^[0-9a-f]{8}$\' ]]', '[[ "$1" =~ \'^[0-9a-f]{8}\' ]]'),
 ('script: an ended job counts as running', 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  '    _claude_process_alive "$(_json_field "$text" pid)" "$(_json_field "$text" procStart)" || continue\n', ''),
 ('script: a reused PID passes for the job', 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  '  [[ -n "$started" ]] || return 0\n', '  return 0\n'),
 ('script: a spare passes for a job', 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  '    [[ "$text" == *\'"spare":true\'* ]] && continue\n', ''),
 ("script: the parent's transcript does not lead to its job", 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  'sed -n \'s/.*"continuedInSessionId"', 'sed -n \'s/.*"continuedInSessionIdX"'),
 ("script: the parked parent's file does not lead to its job", 'obsidian-plugin/scripts/agent-sessions-lib.zsh',
  '    jobs+=("$(_json_field "$text" parkedJobId)")\n', ''),
 ('resume with: rollouts in spaced JSON', 'atlas/convert_write.py',
  'json.dumps(r, ensure_ascii=False, separators=(",", ":"))', 'json.dumps(r, ensure_ascii=False)'),
 ('resume with: session_meta without session_id', 'atlas/convert_write.py',
  '"payload": {"session_id": new_id, "id": new_id,', '"payload": {"id": new_id,'),
 ('jobs: a spare passes for a job', 'atlas/jobs.py',
  ' and d.get("spare") is not True}', '}'),
 ('jobs: the parent that continued in a job is resumed', 'atlas/jobs.py',
  '            sessions.add(row["continued_in"])\n', '            pass\n'),
 ("jobs: the parked parent's file ignored", 'atlas/jobs.py',
  '        if job in wanted or str(d["sessionId"]) in sessions:', '        if str(d["sessionId"]) in sessions:'),
 ('jobs: attach takes any id', 'atlas/jobs.py',
  '    if not cwd or not JOB_ID_RE.match(job_id or ""):', '    if not cwd:'),
 ('actions: a running job gets --resume', 'atlas/actions.py',
  '    if job:\n        cwd = cwd or', '    if False:\n        cwd = cwd or'),
 ('active: an attached job has no card', 'atlas/active.py',
  '        if job_id in clients and job_id not in parked:', '        if False:'),
 ("active: a parked parent's job gets a second card", 'atlas/active.py',
  ' and job_id not in parked:', ':'),
 ("active: the attached job's card points at the job's process", 'atlas/active.py',
  '        "pid": tab_pid or pid,', '        "pid": pid,'),
 ("active: the attached job's tab is not found", 'atlas/active.py',
  '        "ancestors": ancestors(tab_pid or pid, table),', '        "ancestors": ancestors(pid, table),'),
 ("relocate: another session's attach client is moved", 'atlas/relocate.py',
  '    return bool(job) and str(job["sessionId"]) == session_id', '    return bool(job)'),
 ("resume with: thinking is copied", "atlas/convert_read.py",
  '        elif kind == "text":\n            text = str(block.get("text") or "").strip()',
  '        elif kind in ("text", "thinking"):\n            text = str(block.get("text") or block.get("thinking") or "").strip()'),
 ("resume with: Codex reasoning is copied", "atlas/convert_read.py",
  "            # reasoning (with its encrypted content), developer messages, token counts: never copied",
  '            elif kind == "response_item" and sub == "reasoning":\n'
  '                message("assistant", "event", p.get("encrypted_content"), ts)'),
 ("resume with: a summary does not start the copy", "atlas/convert_read.py",
  "            conv.summary, conv.items = summary, []", "            conv.summary = summary"),
 ("resume with: Codex turns before the compaction are copied", "atlas/convert_read.py",
  "                conv.items, calls, pending = [], {}, {}", "                calls = {}"),
 ("resume with: a rewound branch is copied", "atlas/convert_read.py",
  "    for rec in reversed(chain) if linked else records.values():", "    for rec in records.values():"),
 ("resume with: a prompt and its item copy both copied", "atlas/convert_read.py",
  "        if text and first_copy(role, channel, text):", "        if text:"),
 ("resume with: tool output not clipped", "atlas/convert_read.py",
  '        item["output"] = clip(_output_text(output), OUTPUT_LIMIT)', '        item["output"] = _output_text(output)'),
 ("resume with: no budget", "atlas/convert_write.py",
  "    while start > 0 and used + len(_item_text(conv.items[start - 1])) <= room:", "    while start > 0:"),
 ("resume with: no note about the omitted part", "atlas/prompts.py",
  "    return (OMITTED[lg].format(id=session_id) + \"\\n\\n\" + note) if omitted else note", "    return note"),
 ("resume with: a copy stamped after the conversion", "atlas/convert_write.py",
  "        value = min(value, cap)\n", ""),
 ("resume with: an existing session file overwritten", "atlas/convert_write.py",
  "os.O_WRONLY | os.O_CREAT | os.O_EXCL", "os.O_WRONLY | os.O_CREAT | os.O_TRUNC"),
 ("resume with: session_meta without cli_version", "atlas/convert_write.py",
  '"cli_version": CODEX_VERSION, ', ""),
 ("resume with: the configured Codex provider ignored", "atlas/convert_write.py",
  "        if m:\n            return m.group(1)", "        if m:\n            return \"openai\""),
 ("resume with: the own agent writes a copy", "atlas/convert.py",
  "    src = _source(conn, session_id, target)\n    if src[\"agent\"] == target:\n        return {\"agent\": target, \"session_id\"",
  "    src = _source(conn, session_id, target)\n    if False:\n        return {\"agent\": target, \"session_id\""),
 ("resume with: the copy is written without the confirmation", "atlas/server.py",
  '        if body.get("confirmed") is not True:\n            return self._json(400, {"error": msg("server.need_confirm")})\n        try:\n            result = convert.resume_with',
  "        try:\n            result = convert.resume_with"),
 ("resume with: the index counts the copied records", "atlas/store.py",
  '"SELECT source_session_id AS session_id, at FROM conversions WHERE session_id=?"',
  '"SELECT source_session_id AS session_id, at FROM conversions WHERE 0 AND session_id=?"'),
 ("resume with: Codex copies counted", "atlas/codex_parse.py",
  "    return bool(facts.copied_until and ts and ts <= facts.copied_until)", "    return False"),
 ("resume with: a copy nobody typed in is not in search", "atlas/store.py",
  "        facts.started_at = facts.last_activity_at = facts.copied_until\n", "        pass\n"),
 ("resume with: a copy without its source's title", "atlas/store.py",
  '        facts.title, facts.title_source = row["title"], "converted"', "        pass"),
 ("resume with: deleting a copy keeps its link", "atlas/delete.py",
  '"egress_grants",\n             "conversions")', '"egress_grants")'),
 ("tab script: a running Claude session is started a second time", "obsidian-plugin/scripts/agent-sessions-lib.zsh",
  '    [[ -n "$(_json_field "$text" jobId)" ]] && continue\n    pid="$(_json_field "$text" pid)"\n    _claude_process_alive "$pid" "$(_json_field "$text" procStart)" || continue\n    print -r -- "$pid"\n    return 0',
  '    return 1'),
 ("tab script: a Codex thread open elsewhere is resumed again", "obsidian-plugin/scripts/agent-sessions-lib.zsh",
  '[[ "${argv[1]:t}" == codex* ]] && { print -r -- "$pid"; return 0; }', ':'),
 ("tab script: the take-over ignores the answer", "obsidian-plugin/scripts/agent-sessions-lib.zsh",
  '[[ "$answer" == [yY]* ]] || {', '[[ -n "$answer" ]] || {'),
 ("tab script: the take-over does not end the other process", "obsidian-plugin/scripts/agent-sessions-lib.zsh",
  '  kill -TERM "$pid" 2>/dev/null\n  local i', '  local i'),
]
JS_MUT = [
 ("plugin: a reload ends agents in background tabs", "obsidian-plugin/src/held.js",
  "    window.clearTimeout(held.timer);\n    held.timer = null;\n    kept.push(key);", "    kept.push(key);"),
 ("plugin: reload treated as «disabled by user» (closes tabs)", "obsidian-plugin/src/reload.js",
  "await plugins.disablePlugin(id);", "await plugins.disablePlugin(id, true);"),
 ("plugin: an old-version server is not replaced", "obsidian-plugin/src/runtime.js",
  "if (!stale) return { ok: true, reason: null };", "if (true) return { ok: true, reason: null };"),
 ("plugin: a new build on disk is not picked up", "obsidian-plugin/src/reload.js",
  "if (this.reloadInPlace()) new Notice", "if (false) new Notice"),
 ("plugin: first launch overwrites agent arguments", "obsidian-plugin/src/main.js",
  "if (!saved.agentArgs && this.adoptAgentArgs()) await this.saveData(this.settings);", ""),
 ("runtime: python without CLT is used anyway", "obsidian-plugin/src/runtime.js",
  '.filter((p) => p !== "/usr/bin/python3" || clt);', ";"),
 ("runtime: old files are not removed", "obsidian-plugin/src/runtime.js",
  "if (!keep.has(path.join(sub, rel))) fsSync.rmSync(path.join(root, rel), { force: true });", ""),
 ("runtime: a foreign server on the port is taken as ours", "obsidian-plugin/src/runtime.js",
  'if (health && health.app === "session-atlas") {\n      // A server', 'if (health) {\n      // A server'),
 ("pty: size is not set before start", "obsidian-plugin/src/pty.js",
  """const INNER = 'stty rows "$1" cols "$2" 2>/dev/null; shift 2; exec "$@"';""",
  """const INNER = 'shift 2; exec "$@"';"""),
 ("pty: closing does not kill the group", "obsidian-plugin/src/pty.js",
  "try { process.kill(-child.pid, signal); }", "try { process.kill(child.pid, signal); }"),
 ("config-form: duplicate domains", "obsidian-plugin/src/config-form.js",
  " || out.some((d) => d.id === id)) continue;", ") continue;"),
 ("plugin: parsing lets ; and $ through", "obsidian-plugin/src/agents.js",
  "    } else {\n      return null;\n    }\n  }\n  if (cur !== null) out.push(cur);",
  "    } else {\n      cur = (cur || \"\") + c; i++;\n    }\n  }\n  if (cur !== null) out.push(cur);"),
 ("plugin: extra claude flags are accepted", "obsidian-plugin/src/agents.js",
  'if (flag === "--resume" && rest.length === 0)', 'if (flag === "--resume")'),
 ("plugin: prompt unquoted in tab arguments", "obsidian-plugin/src/agents.js",
  "if (seed.prompt) parts.push(shellQuote(seed.prompt));", "if (seed.prompt) parts.push(seed.prompt);"),
 ('plugin: attach takes a session id', 'obsidian-plugin/src/agents.js',
  'JOB_ID.test(id || "") ? start("attach", id)', 'id ? start("attach", id)'),
 ('plugin: attach takes extra words', 'obsidian-plugin/src/agents.js',
  'return rest.length === 0 && JOB_ID.test', 'return JOB_ID.test'),
 ('plugin: any command line reads as an attach client', 'obsidian-plugin/src/attach.js',
  'const ATTACH = /^(?:\\S*\\/)?claude attach ([0-9a-f]{8})$/;', 'const ATTACH = /claude attach ([0-9a-f]{8})/;'),
 ('plugin: a spare reads as the attached job', 'obsidian-plugin/src/attach.js',
  ' && data.spare !== true', ''),
 ('plugin: an ended job reads as attached', 'obsidian-plugin/src/attach.js',
  ' && running(data.pid)', ''),
 ('plugin: an attach client has no session before input', 'obsidian-plugin/src/terminal.js',
  ' || attachedSessionState(pid, SESSIONS_DIR)', ''),
 ("plugin: directory bypasses the script", "obsidian-plugin/src/terminal.js",
  'if (launch && (await this.openAgent(launch.agent, { cwd: launch.cwd, seed: launch, label }))) return;', ''),
 ("plugin: pointerdown on the close button is not suppressed", "obsidian-plugin/src/guard.js",
  "    if (!this.guardKind(leaf)) return;\n    event.preventDefault();\n    event.stopPropagation();\n    event.stopImmediatePropagation();\n    if (ask)",
  "    if (!this.guardKind(leaf) || !ask) return;\n    event.preventDefault();\n    event.stopPropagation();\n    event.stopImmediatePropagation();\n    if (ask)"),
 ("plugin: ⌘W without confirmation", "obsidian-plugin/src/guard.js",
  "if (leaf && original.call(this, true)) {", "if (false) {"),
 ("plugin: file explorer duplicates an open file", "obsidian-plugin/src/explorer.js",
  "    if (open) {", "    if (false) {"),
 ("plugin: file explorer swallows a folder click", "obsidian-plugin/src/explorer.js",
  "if (!(file instanceof TFile)) return;", "if (!file) return;"),
 ("plugin: restore without delay", "obsidian-plugin/src/restore.js",
  "&& Date.now() - (this.loadedAt || 0) >= RESTORE_GRACE_MS", ""),
 ("plugin: the close guard is skipped after a plugin reload", "obsidian-plugin/src/guard.js",
  "    if (!doc || this.guardedDocs.has(doc)) return;\n    this.guardedDocs.add(doc);",
  "    if (!doc || doc.__sessionAtlasGuard) return;\n    doc.__sessionAtlasGuard = true;"),
 ("plugin: popouts open at load get no close guard", "obsidian-plugin/src/guard.js",
  "      if (el && el.ownerDocument) this.installCloseGuard(el.ownerDocument);", ""),
 ("terminal: ⌥ held does not select over a program holding the mouse", "obsidian-plugin/src/term-copy.js",
  "!!(event && (event.altKey || event.shiftKey))", "!!(event && event.shiftKey)"),
 ("terminal: ⌥-drag selects a block", "obsidian-plugin/src/term-copy.js",
  "service.shouldColumnSelect = () => false;", ";"),
 ("terminal: ⌘C on a Cyrillic layout does not copy", "obsidian-plugin/src/term-copy.js",
  ' || (!/^[a-z]$/.test(key) && e.code === "KeyC")', ""),
 ("terminal: a refused clipboard loses the copy", "obsidian-plugin/src/term-copy.js",
  "return clip.writeText(text).then(() => true, () => fallback());", "return clip.writeText(text).then(() => true, () => false);"),
 ("terminal: Copy in the menu without a selection", "obsidian-plugin/src/term-copy.js",
  "disabled: !(term && term.hasSelection())", "disabled: false"),
 ("held: an offered agent still ends after two minutes", "obsidian-plugin/src/held.js",
  "held.timer = window.setTimeout(() => releaseHeld(key), OFFER_HOLD_MS);", "held.timer = window.setTimeout(() => releaseHeld(key), RECLAIM_MS);"),
 ("held: every poll restarts the offer", "obsidian-plugin/src/held.js",
  "    if (!held.offeredAt) {", "    if (true) {"),
 ("held: a tab still in the layout is offered too", "obsidian-plugin/src/held.js",
  "if (!held.held || wanted.has(key)) continue;", "if (!held.held) continue;"),
 ("held: End kills a process attached to a tab", "obsidian-plugin/src/held.js",
  "  if (!held || !held.held) return false;", "  if (!held) return false;"),
 ("held: a notice on every poll", "obsidian-plugin/src/held.js",
  "    if (fresh.length) {", "    if (held.length) {"),
 ("held: the page does not get held tabs", "obsidian-plugin/src/main.js",
  "held: this.heldTabs().map(({ ptyPid, title, agent }) => ({ ptyPid, title, agent })),", "held: [],"),
 ("held: Go to on a held session does nothing", "obsidian-plugin/src/main.js",
  '    if (!tab && type === "focus-tab" && (await this.reattachHeld([ptyPid]))) return;\n', ""),
 ("held: a held session is forgotten for the restart", "obsidian-plugin/src/restore.js",
  " || this.heldForSession(s)", ""),
 ("page: a restore list not ready yet is shown", "web/js/active-restore.js",
  'restorable = restorableReady ? d.sessions.filter(x => x && typeof x.session_id === "string") : [];',
  'restorable = d.sessions.filter(x => x && typeof x.session_id === "string");'),
 ("page: held tabs get no banner", "web/js/active-restore.js",
  "  const held = heldRow();\n", "  const held = null;\n"),
 ("page: a held session is not found by its process tree", "web/js/active-state.js",
  "return (s.ancestors || []).find(pid => hostHeld.has(pid)) || null;", "return null;"),
 ("plugin: Obsidian language is ignored", "obsidian-plugin/src/i18n.js",
  'return String(obsidianLanguage || "").toLowerCase().startsWith("ru") ? "ru" : "en";', 'return "en";'),
 ("logic: jump — one word is enough", "web/js/logic.js",
  "if (!words.every(w => hay.includes(w))) return;", "if (!words.some(w => hay.includes(w))) return;"),
 ("logic: jump — closed ranked equal to live", "web/js/logic.js",
  'scored.push([it.kind === "live" ? 0 : 1, head, i, it]);', "scored.push([0, head, i, it]);"),
 ("logic: jump — title prefix does not matter", "web/js/logic.js",
  "const head = words.length && title.startsWith(words[0]) ? 0 : 1;", "const head = 0;"),
 ("plugin: plan — text without checking the field", "obsidian-plugin/src/input.js",
  "if (!(await seen((f) => f.selected))) {", "if (false) {"),
 ("plugin: plan — Enter without verifying the text", "obsidian-plugin/src/input.js",
  "if (!(await seen((f) => f.selected && squash(f.typed) === squash(text)))) {", "if (false) {"),
 ("plugin: typed answer — text over what is already typed in the field", "obsidian-plugin/src/input.js",
  "data.text !== field.label || field.typed) {", "data.text !== field.label) {"),
 ("plugin: typed answer — the field became another dialog's", "obsidian-plugin/src/input.js",
  "const f = d && d.kind === dialog.kind ? textField(d) : null;\n        if (f && f.n === field.n && f.label === field.label && test(f))",
  "const f = d ? textField(d) : null;\n        if (f && f.n === field.n && test(f))"),
 ("plugin: plan — feedback into the wrong option", "obsidian-plugin/src/input.js",
  "if (!field || field.n !== data.option ||", "if (!field ||"),
 ("plugin: plan — line breaks not removed", "obsidian-plugin/src/input.js",
  '.replace(/\\s+/g, " ").trim();\n    if (!text', '.trim();\n    if (!text'),
 ("plugin: plan not recognized as a plan", "obsidian-plugin/src/dialog.js",
  "  const plan = parsePlanDialog(rows);\n  if (plan) return plan;\n", ""),
 ("plugin: feedback field among the buttons", "obsidian-plugin/src/dialog.js",
  "feedback = options.pop();", "feedback = options[options.length - 1];"),
 ("page: top level calls a function from a later file", "web/js/active-feed.js",
  'let feedView = loadStored(FEED_VIEW_KEY, "turns");', 'let feedView = closedSection(FEED_VIEW_KEY);'),
 ("logic: error filter lets everything through", "web/js/logic.js",
  'error: ev => ev.status === "error"', 'error: ev => true'),
 ("logic: a sibling folder's path counts as own", "web/js/logic.js",
  'path.startsWith(cwd.replace(/\\/$/, "") + "/")', 'path.startsWith(cwd)'),
 ("page: same-named function in two files", "web/js/stats.js",
  "function saveStatsPrefs() {", "function segmented() {}\nfunction saveStatsPrefs() {"),
 ("logic: tasks without status marks", "web/js/logic.js",
  "`${TASK_MARK[i.status] || \"○\"} ${i.subject}`", "i.subject"),
 ("logic: show an empty task list", "web/js/logic.js",
  "if (!t || !t.total) return null;", "if (!t) return null;"),
 ("stats-logic: billions shown as millions", "web/js/stats-logic.js",
  "if (a >= 1e9)", "if (a >= 1e19)"),
 ("stats-logic: growth with a minus sign", "web/js/stats-logic.js",
  '(pct > 0 ? "+" : "−")', '"−"'),
 ("stats-logic: division by zero in comparison", "web/js/stats-logic.js",
  "|| prev <= 0) return null", ") return null"),
 ("stats-logic: sorting not by the measure", "web/js/stats-logic.js",
  ".sort((a, b) => b[metric] - a[metric])", ".sort(() => 0)"),
 ("stats-logic: empty values not dropped", "web/js/stats-logic.js",
  ".filter(i => i[metric] > 0)", ".filter(() => true)"),
 ("plugin: do not check message origin", "obsidian-plugin/src/main.js",
  'if (event.origin !== this.atlasOrigin()) return;', 'if (false) return;'),
 ("plugin: do not check message source", "obsidian-plugin/src/main.js",
  'if (!data || data.source !== "session-atlas") return;', 'if (!data) return;'),
 ("plugin: accept any action type", "obsidian-plugin/src/main.js",
  'if (data.type === "resume" || data.type === "new-session") {', 'if (true) {'),
 ("plugin: inline iframe with an extra scrollbar", "obsidian-plugin/styles.css",
  '.session-atlas-frame {\n  display: block;\n', '.session-atlas-frame {\n'),
 ("plugin: type into a session with an open dialog", "obsidian-plugin/src/input.js",
  'if (state.status === "waiting") {', 'if (false) {'),
 ("plugin: do not check that the process belongs to this tab", "obsidian-plugin/src/input.js",
  'if (!this.isDescendant(data.claudePid, data.ptyPid)) {', 'if (false) {'),
 ("plugin: do not verify the session id", "obsidian-plugin/src/input.js",
  'if (!state || !state.sessionIds.includes(data.sessionId)) return', 'if (!state) return'),
 ("plugin: let control characters through", "obsidian-plugin/src/terminal.js",
  '.replace(/[\\x00-\\x08\\x0b-\\x1f\\x7f]/g, "")', ''),
 ("plugin: multiline without paste", "obsidian-plugin/src/input.js",
  'stdin.write(text.includes("\\n") ? PASTE_START + text + PASTE_END : text);', 'stdin.write(text);'),
 ("plugin: no Enter after the text", "obsidian-plugin/src/input.js",
  'window.setTimeout(() => stdin.write("\\r"),', 'window.setTimeout(() => null,'),
 ("plugin: images from any folder", "obsidian-plugin/src/terminal.js",
  'if (!full.startsWith(root) || !IMAGE_EXT.test(full)', 'if (!IMAGE_EXT.test(full)'),
 ("plugin: image path without a separate paste", "obsidian-plugin/src/input.js",
  'for (const image of images) stdin.write(PASTE_START + image + PASTE_END + " ");',
  'for (const image of images) stdin.write(image + " ");'),
 ("plugin: close a tab without confirmation", "obsidian-plugin/src/main.js",
  'this.confirmClose(tab.leaf, title || tab.title);', 'tab.leaf.detach();'),
 ("plugin: send the tab list to any origin", "obsidian-plugin/src/main.js",
  '}, this.atlasOrigin());\n  }\n\n  /**\n   * A tab for the page.', '}, "*");\n  }\n\n  /**\n   * A tab for the page.'),
 ("plugin: wait for a hung terminal without a timeout", "obsidian-plugin/src/terminal.js",
  'new Promise((resolve) => window.setTimeout(() => resolve(null), PTY_WAIT_MS)),',
  'new Promise(() => {}),'),
 ("plugin: do not check that the command is a string", "obsidian-plugin/src/main.js",
  'if (typeof data.command !== "string" || !data.command) return;', ''),
 ("page: a javascript: link is clickable", "web/js/markdown.js",
  r'const SAFE_URL = /^(https?:\/\/|mailto:)/i;', 'const SAFE_URL = /./;'),
 ("page: snake_case turns italic", "web/js/markdown.js",
  "{ re: /(^|[^\\w*])\\*([^*\\s][^*\\n]*?)\\*(?!\\w)/,", "{ re: /(^|[^*])\\*([^*\\n]*?)\\*/,"),
 ("page: a trailing period goes into the URL link", "web/js/markdown.js",
  """[^\\s<>()\\].,;:!?'"»]/,""", """/,"""),
 ("page: a code block parses markup", "web/js/markdown.js",
  'blocks.push({ t: "pre", text: body.join("\\n") });', 'blocks.push({ t: "p", lines: body.map(parseInline) });'),
 ("page: switching - to 1. without a new list", "web/js/markdown.js",
  '&& stack[stack.length - 1].list.ordered !== ordered) stack.pop();', '&& false) stack.pop();'),
 ("page: list filters — AND instead of OR", "web/js/logic.js",
  'valuesOf(s, key, now).some(v => want.has(v))', '[...want].every(v => valuesOf(s, key, now).includes(v))'),
 ("page: the counter applies its own filter", "web/js/logic.js",
  'sessions.filter(s => passes(s, filters, key, now))', 'sessions.filter(s => passes(s, filters, null, now))'),
 ("page: layout without a limit", "web/js/logic.js",
  'return m && +m[1] <= max && +m[2] <= max ?', 'return m ?'),
 ("page: yesterday counts as this week", "web/js/logic.js",
  'if (days === 1) return "yesterday";', ''),
 ("page: a sent item is not cleared once the transcript catches up", "web/js/logic.js",
  '|| t(s.prompt_at) >= t(sent.at) - 2000)', ')'),
 ("page: down moves one card, not one row", "web/js/logic.js",
  'ArrowDown: cols, ArrowUp: -cols', 'ArrowDown: 1, ArrowUp: -1'),
 ("page: navigation goes past the edge", "web/js/logic.js",
  'return ids[Math.max(0, Math.min(ids.length - 1, i + step))];', 'return ids[i + step];'),
 ("page: the current estimate has no increment", "web/js/logic.js",
  's.cost_now - s.cost_usd >= 0.005', 'true'),
 ("page: a silent plugin is «checking» forever", "web/js/logic.js",
  'if (askedAt && now - askedAt > HOST_REPLY_MS) {', 'if (false) {'),
 ("plugin: tabs without a process — connection «on»", "obsidian-plugin/src/terminal.js",
  'if (leaves.length && !tabs.length) {', 'if (false) {'),
 ("plugin: notify about a new session", "obsidian-plugin/src/notify.js",
  'if (was === undefined || was === now) continue;', 'if (was === now) continue;'),
 ("plugin: notify with the setting off", "obsidian-plugin/src/notify.js",
  'if (this.settings && this.settings.notify) {', 'if (this.settings) {'),
 ("plugin: notify while the tab is being viewed", "obsidian-plugin/src/notify.js",
  'if (focused && tab && this.activeLeaf() === tab.leaf) return;', ''),
 ("plugin: server silent — counter drops to zero", "obsidian-plugin/src/notify.js",
  'if (!data || !Array.isArray(data.sessions)) return;', 'if (!data) data = { sessions: [] };'),
 ("plugin: title without a counter", "obsidian-plugin/src/notify.js",
  'return count ? `AI Session Atlas (${count})` : "AI Session Atlas";', 'return "AI Session Atlas";'),
 ("plugin: Resume opens a second tab next to the session's own", "obsidian-plugin/src/terminal.js",
  'if (launch && launch.mode === "resume" && this.revealSessionTab(launch.sessionId)) return;', ''),
 ("plugin: another session's tab is taken for this one", "obsidian-plugin/src/terminal.js",
  'if (instance && session === sessionId) out.add(instance);', 'if (instance) out.add(instance);'),
 ("plugin: a page-wide copy takes another tab's selection", "obsidian-plugin/src/term-copy.js",
  'leaf !== activeLeaf ||', ''),
 ("plugin: a text field's copy is taken by the terminal", "obsidian-plugin/src/term-copy.js",
  'return !field && !(target && target.isContentEditable);', 'return true;'),
 ("notices: sticky ignored", "obsidian-plugin/src/notify.js",
  'return value === "sticky" ? 0 : Number(value) * 1000;', 'return value === "sticky" ? 10000 : Number(value) * 1000;'),
 ("notices: the setting ignored", "obsidian-plugin/src/notify.js",
  'const hold = this.settings && this.settings.noticeHold;', 'const hold = DEFAULT_NOTICE_HOLD;'),
 ("notices: close opens the tab", "obsidian-plugin/src/notify.js",
  'event.stopPropagation();      // closing', '// closing'),
 ("notices: close leaves it on screen", "obsidian-plugin/src/notify.js",
  '        this.hideNotice(s.session_id, notice);\n      });', '      });'),
 ("notices: a session piles up duplicates", "obsidian-plugin/src/notify.js",
  'if (old) this.hideNotice(id, old);', ''),
 ("notices: no cap on the stack", "obsidian-plugin/src/notify.js",
  'while (this.openNotices.size > MAX_NOTICES) {', 'while (false) {'),
 ("notices: clicked-away ones still count", "obsidian-plugin/src/notify.js",
  'if (el && el.isConnected === false) this.openNotices.delete(key);', ''),
 ("notices: stale ones stay", "obsidian-plugin/src/notify.js",
  '      this.dropStaleNotices(sessions);\n', ''),
 ("notices: working sessions keep theirs", "obsidian-plugin/src/notify.js",
  'const waiting = new Set(sessions.filter((s) => s && isWaiting(s)).map((s) => s.session_id));',
  'const waiting = new Set(sessions.filter(Boolean).map((s) => s.session_id));'),
 ("dialog: the text field answered with its digit alone", "obsidian-plugin/src/dialog.js",
  "return !!option && !option.freeText && option.text === text;", "return !!option && option.text === text;"),
 ("dialog: the text field not found once text is typed over its label", "obsidian-plugin/src/dialog.js",
  ": chat ? options[beforeRule] : options.find(", ": options.find("),
 ("dialog: a fresh session's dialog at the top of the screen is missed", "obsidian-plugin/src/dialog.js",
  "  while (end > 0 && !rows[end - 1].trim()) end--;\n  let footer = -1;", "  let footer = -1;"),
 ("logic: the typed answer keeps its line breaks", "web/js/logic.js",
  'const line = String(text || "").replace(/\\s+/g, " ").trim();', 'const line = String(text || "").trim();'),
 ("logic: Codex's decline is not answered with text", "web/js/logic.js",
  "return d.feedback ? d.options.find(", "return false ? d.options.find("),
 ("logic: a permission's option taken for the text field", "web/js/logic.js",
  'return d.kind === "question" ? d.options.find(o => o.freeText) || null : null;',
  'return d.options.find(o => o.freeText || o.n === 3) || null;'),
 ("dialog: several questions answered with a digit", "obsidian-plugin/src/dialog.js",
  'answerable: !multi && choices.length > 0,', 'answerable: choices.length > 0,'),
 ("dialog: a wrapped permission label is not joined", "obsidian-plugin/src/dialog.js",
  'if (kind === "permission") {\n    options.forEach', 'if (false) {\n    options.forEach'),
 ("dialog: footer is optional", "obsidian-plugin/src/dialog.js",
  'if (footer < 0) return null;', 'if (footer < 0) footer = rows.length;'),
 ("plugin: answer without matching the label on screen", "obsidian-plugin/src/input.js",
  'if (!sameOption(dialog, data.option, data.text)) {', 'if (!dialog) {'),
 ("plugin: dialog answer with Enter", "obsidian-plugin/src/input.js",
  'stdin.write(String(data.option));', 'stdin.write(String(data.option) + "\\r");'),
 ("plugin: answer when the dialog is already closed", "obsidian-plugin/src/input.js",
  'if (state.status !== "waiting") return reply(false, this.t("input.dialogClosed"));', ''),
 ("plugin: «Stop» while idle", "obsidian-plugin/src/input.js",
  'if (!STOPPABLE.has(state.status)) return reply(false, this.t("input.notRunning"));', ''),
 ("plugin: «Stop» with two Esc", "obsidian-plugin/src/input.js",
  'stdin.write(ESC);', 'stdin.write(ESC + ESC);'),
 ("plugin: «Stop» without verifying the session", "obsidian-plugin/src/input.js",
  'const { error, tab, state } = await this.checkTarget(data);\n    if (error) return reply(false, error);\n    if (!STOPPABLE',
  'const { error, tab, state } = await this.checkTarget(Object.assign({}, data, { sessionId: '
  '(this.readSessionState(data.claudePid) || {}).sessionId }));\n    if (error) return reply(false, error);\n    if (!STOPPABLE'),
 ("page: an interrupted prompt «awaits a reply»", "web/js/logic.js",
  'interrupted: t(s.interrupted_at) >= t(s.prompt_at) }', 'interrupted: false }'),
 ("page: delivery without a queue", "web/js/logic.js",
  'if (head && (s.queued || []).some(q => (q.text || "").trim().startsWith(head))) return "queued";', ''),
 ("page: delivery does not clear", "web/js/logic.js",
  'if (head && now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS) return "lost";', ''),
 ("page: an image without text — «lost»", "web/js/logic.js",
  'if (head && now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS)', 'if (now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS)'),
 ("plugin: macOS notification even with the window in front", "obsidian-plugin/src/notify.js",
  'if (!focused && this.settings && this.settings.systemNotify) this.systemNotify(s, go);',
  'if (this.settings && this.settings.systemNotify) this.systemNotify(s, go);'),
 ("plugin: macOS notification without the setting", "obsidian-plugin/src/notify.js",
  'if (!focused && this.settings && this.settings.systemNotify)', 'if (!focused)'),
 ("plugin: silent when the tab is active in a minimized window", "obsidian-plugin/src/notify.js",
  'if (focused && tab && this.activeLeaf() === tab.leaf) return;',
  'if (tab && this.activeLeaf() === tab.leaf) return;'),
 ("plugin: clicking the macOS notification does not open the tab", "obsidian-plugin/src/notify.js",
  '      raiseWindow();\n      go();', '      raiseWindow();'),
 ("page: suggestions after a space too", "web/js/logic.js",
  'const m = /^\\/([^\\s]*)$/.exec(text || "");', 'const m = /^\\/(\\S*)/.exec(text || "");'),
 ("page: suggestions without prefix matches first", "web/js/logic.js",
  'return starts.concat(inside);', 'return inside.concat(starts);'),
 ("page: history does not restore the draft", "web/js/logic.js",
  'const next = Math.max(-1,', 'const next = Math.max(0,'),
 ("page: 80% context raises no alert", "web/js/logic.js", 'tone: pct >= 80 ? "warn"', 'tone: pct >= 95 ? "warn"'),
 ("page: live limits get an age", "web/js/logic.js",
  "const age = l.live === true || l.age_seconds == null ? null", "const age = l.age_seconds == null ? null"),
 ("page: old limits carry no age", "web/js/logic.js",
  "const age = l.live === true || l.age_seconds == null ? null", "const age = true ? null"),
 ("page: a spent window not marked", "web/js/logic.js",
  '+ (w.used_percentage >= 100 ? I18.i18n("logic.limits.reached") : "")', '+ ""'),
 ("page: Codex asked with Codex hidden", "web/js/logic.js",
  '(agents || []).includes("codex") ? ["codex_usage=1"] : []', '["codex_usage=1"]'),
 ("page: order by message recency", "web/js/logic.js",
  'const started = s => new Date(s.process_started_at || s.started_at || 0).getTime();',
  'const started = s => new Date(s.last_message_at || 0).getTime();'),
 ("page: pinned ones not first", "web/js/logic.js",
  'if (pa !== pb) return (pa < 0 ? 1e9 : pa) - (pb < 0 ? 1e9 : pb);', ''),
 ("page: a hidden one does not return on a new message", "web/js/logic.js",
  '&& hid[s.session_id] === (s.last_message_at || "");', ';'),
 ("page: hidden entries accumulate", "web/js/logic.js",
  'return !s || hid[id] !== (s.last_message_at || "");', 'return false;'),
 ("plugin: live sessions also offered for restore", "obsidian-plugin/src/restore.js",
  '.filter((x) => !alive.has(x.session_id) && fresh(x));', '.filter((x) => fresh(x));'),
 ("plugin: old sessions also offered for restore", "obsidian-plugin/src/restore.js",
  'now - (x.at || 0) < RESTORE_MAX_AGE_MS : true;', 'true : true;'),
 ("plugin: remember sessions not from tabs too", "obsidian-plugin/src/restore.js",
  'if ((await this.tabForSession(s)) || this.heldForSession(s)) {', 'if (true) {'),
 ("plugin: restore list to any origin", "obsidian-plugin/src/restore.js",
  '    }, this.atlasOrigin());', '    }, "*");'),
 ("plugin: «not needed» does not forget", "obsidian-plugin/src/restore.js",
  'this.restorable = drop ? (this.restorable || []).filter((x) => !drop.has(x.session_id)) : [];',
  'this.restorable = this.restorable || [];'),
 ("plugin: «Restore» twice — two launches", "obsidian-plugin/src/main.js",
  'if (this.raisingServer) return;', ''),
 ("plugin: «Restore» answers any origin", "obsidian-plugin/src/main.js",
  'type: "server-ensured", ok, reason }, this.atlasOrigin());', 'type: "server-ensured", ok, reason }, "*");'),
 ("page: estimate without ≈", "web/js/logic.js", 'return (estimate ? "≈" : "") + "$"', 'return "$"'),
 ("page: 1M window shown as 1000k", "web/js/logic.js",
  'return n >= 1e6 ? (n / 1e6)', 'return n >= 1e9 ? (n / 1e6)'),
 ("plugin: command response is not read", "obsidian-plugin/src/input.js",
  'if (command && !images.length\n        && (codex ? this.codexScreenCommand(command[1]) : SCREEN_COMMANDS.has(command[1]))) {', 'if (false) {'),
 ("plugin: screen is read after any message", "obsidian-plugin/src/input.js",
  'if (command && !images.length\n        && (codex ? this.codexScreenCommand(command[1]) : SCREEN_COMMANDS.has(command[1]))) {', 'if (!images.length) {'),
 ("dialog: panel not recognized", "obsidian-plugin/src/dialog.js",
  'if (PANEL_RULE.test(rows[i])) { panel = i; break; }', ''),
 ("dialog: command echo stays in the reply", "obsidian-plugin/src/dialog.js",
  '        body = body.slice(i + 1);\n        break;', '        break;'),
 ("dialog: ⎿ marker in the reply", "obsidian-plugin/src/dialog.js",
  'body.map((l) => l.replace(/^(\\s*)⎿ {1,2}/, "$1"))', 'body'),
 ("plugin: panel is not shown instead of «not parsed»", "obsidian-plugin/src/input.js",
  '    if (panel && panel.panel) {', '    if (false) {'),
 ("codex: an answer is pressed after the option changed", "obsidian-plugin/src/input-codex.js",
  "    if (!sameOption(dialog, data.option, data.text)) return reply(false, this.t(\"input.dialogChanged\"));", ""),
 ("codex: a working turn is read as idle", "obsidian-plugin/src/dialog-codex.js",
  '  if (rows.slice(-15).some((l) => WORKING.test(l))) return "busy";\n', ""),
 ("codex: feedback sent without checking the composer", "obsidian-plugin/src/input-codex.js",
  "if (!(await seen((lines) => squash(composerText(lines)) === squash(text)))) {",
  "if (false) {"),
 ("codex: text typed into an unknown screen", "obsidian-plugin/src/input.js",
  '    if (state.agent === "codex" && !state.status) return reply(false, this.t("input.codexScreen"));', ""),
 ("codex: an approval on the tab does not notify", "obsidian-plugin/src/notify.js",
  'out.push(waiting ? { ...s, status: "waiting", activity: "waiting" } : s);', "out.push(s);"),
 ("codex: a dialog without the footer hint", "obsidian-plugin/src/dialog-codex.js",
  "  if (footer < 0) return null;\n  const block = optionBlock(rows, footer);",
  "  const block = optionBlock(rows, footer < 0 ? rows.length : footer);"),
 ("page: 11 inflected like 1", "web/js/logic.js",
  'if (m10 === 1 && m100 !== 11) return one;', 'if (m10 === 1) return one;'),
 ("codex: page: Claude-only controls on Codex cards", "web/js/agent-filter.js",
  'const claude = AtlasLogic.agentOf(s) === "claude";', "const claude = true;"),
 ("codex: page: plan dialog on a Codex card", "web/js/active-dialog.js",
  'd.kind === "plan" && agentControls(s).plan', 'd.kind === "plan"'),
 ("codex: page: a waiting Codex screen ignored", "web/js/agent-filter.js",
  'if (AtlasLogic.agentOf(s) !== "codex" || screen !== "waiting") return s;', "return s;"),
 ("codex: page: a Codex dialog without details breaks the card", "web/js/active-dialog.js",
  "const details = Array.isArray(d.details) ? d.details : [];", "const details = d.details;"),
 ("codex: page: tab screens not applied to the cards", "web/js/active-state.js",
  "    return withTabScreen(s, pid ? hostScreens.get(pid) : null);", "    return s;"),
 ("codex launch: parser takes any word after codex as a prompt", "obsidian-plugin/src/agents.js",
  'if (args.length === 1 && plainPrompt(args[0])) return start("new", "", args[0]);',
  'if (args.length === 1) return start("new", "", args[0]);'),
 ("codex launch: parser takes a flag-like prompt", "obsidian-plugin/src/agents.js",
  'return text.startsWith(" ") || (!text.startsWith("-") && text.trim().split(/\\s+/).length >= 2);',
  'return text.startsWith(" ") || text.trim().split(/\\s+/).length >= 2;'),
 ("codex launch: parser takes a one-word prompt", "obsidian-plugin/src/agents.js",
  '(!text.startsWith("-") && text.trim().split(/\\s+/).length >= 2)', '!text.startsWith("-")'),
 ("codex launch: parser takes extra Codex arguments", "obsidian-plugin/src/agents.js",
  'return args.length === 2 && args[0] === "resume" && UUID.test(args[1])', 'return args[0] === "resume" && UUID.test(args[1])'),
 ("codex launch: claude new takes any prompt again", "obsidian-plugin/src/agents.js",
  'if (flag === "--session-id" && rest.length === 1 && plainPrompt(rest[0]))', 'if (flag === "--session-id" && rest.length === 1)'),
 ("codex launch: an empty id drops out of the tab arguments", "obsidian-plugin/src/agents.js",
  "seed.sessionId ? shellQuote(seed.sessionId) : \"''\"", "seed.sessionId"),
 ("codex launch: the page is not told which agents are on", "obsidian-plugin/src/main.js",
  'agents: { claude: this.agentEnabled("claude"), codex: this.agentEnabled("codex") },', ""),
 ("codex launch: page offers Codex while it is off", "web/js/logic.js",
  'return hostAgents && hostAgents.codex === true ? AGENTS.slice() : ["claude"];', "return AGENTS.slice();"),
 ("codex launch: page forgets the remembered agent", "web/js/logic.js",
  'return offered.includes(remembered) ? remembered : "claude";', 'return "claude";'),
 ("codex launch: page shows a choice of one", "web/js/active-new.js",
  '$("#ns-agent-row").hidden = offered.length < 2;', '$("#ns-agent-row").hidden = false;'),
 ("resume with: page offers an agent the plugin has off", "web/js/resume-with.js",
  'const on = !embedded || (agent === "claude" ? !(host && host.claude === false) : !!(host && host.codex === true));',
  "const on = true;"),
 ("resume with: the own agent disabled with its switch off", "web/js/resume-with.js",
  "enabled: agent === own || on", "enabled: on"),
 ("folder pick: arrows do not wrap around", "web/js/folder-pick.js",
  "return active < 0 ? 0 : (active + 1) % count;", "return active < 0 ? 0 : Math.min(active + 1, count - 1);"),
 ("folder pick: one word of the query is enough", "web/js/folder-pick.js",
  "Math.max(...words.map((w) => wordScore(w, text)))", "Math.min(...words.map((w) => wordScore(w, text)))"),
 ("folder pick: subfolders come after known folders while typing a path", "web/js/folder-pick.js",
  "looksLikePath(q) ? fromDirs.concat(fromKnown) : fromKnown.concat(fromDirs)", "fromKnown.concat(fromDirs)"),
 ("folder pick: an older listing is shown whole", "web/js/folder-pick.js",
  "listing.text === text ? listing.dirs : listing.dirs.filter(", "listing.dirs || listing.dirs.filter("),
 ("folder pick: Tab adds a second slash", "web/js/folder-pick.js",
  'item.text.endsWith("/") ? item.text : item.text + "/"', 'item.text + "/"'),
 ("folder pick: the list runs past the Start row", "web/js/folder-pick.js",
  "Math.min(max, stopAt - fieldBottom - 8)", "max"),
 ("folder pick: the error hides suggestions that help", "web/js/folder-pick.js",
  "if (listing.error && !items.length)", "if (listing.error)"),
 ("folder pick: scattered letters match in any order", "web/js/folder-pick.js",
  "      at = text.indexOf(c, at);", "      at = text.indexOf(c);"),
 ("resume with: arrows stop on a disabled item", "web/js/resume-with.js",
  "const idx = enabled.map((on, i) => (on ? i : -1)).filter((i) => i >= 0);", "const idx = enabled.map((on, i) => i);"),
]



# Node test files that cover each plugin/page source; the first matching prefix wins.
JS_TESTS = [
    ("obsidian-plugin/src/pty.js", ["tests/js/pty.test.mjs"]),
    ("obsidian-plugin/src/config-form.js", ["tests/js/config-form.test.mjs"]),
    ("obsidian-plugin/src/statusline.js", ["tests/js/statusline.test.mjs"]),
    ("obsidian-plugin/src/runtime.js", ["tests/js/bundle.test.mjs", "tests/js/plugin.test.mjs"]),
    ("obsidian-plugin/src/attach.js", ["tests/js/attach.test.mjs"]),
    ("obsidian-plugin/src/agents.js", ["tests/js/attach.test.mjs", "tests/js/plugin.test.mjs"]),
    ("obsidian-plugin/src/terminal.js", ["tests/js/attach.test.mjs", "tests/js/plugin.test.mjs"]),
    ("obsidian-plugin/src/", ["tests/js/plugin.test.mjs"]),
    ("obsidian-plugin/styles.css", ["tests/js/plugin.test.mjs"]),
    ("web/js/resume-with.js", ["tests/js/resume-with.test.mjs", "tests/js/i18n.test.mjs"]),
    ("web/js/folder-pick.js", ["tests/js/folder-pick.test.mjs", "tests/js/i18n.test.mjs"]),
    ("web/js/active-restore.js", ["tests/js/held-page.test.mjs", "tests/js/page.test.mjs", "tests/js/i18n.test.mjs"]),
    ("web/js/active-state.js", ["tests/js/held-page.test.mjs", "tests/js/page.test.mjs", "tests/js/i18n.test.mjs",
                                "tests/js/codex-active.test.mjs"]),
    ("web/js/", ["tests/js/page.test.mjs", "tests/js/i18n.test.mjs", "tests/js/codex-active.test.mjs"]),
]


def js_tests(path):
    for prefix, files in JS_TESTS:
        if path.startswith(prefix):
            return files
    raise SystemExit(f"no Node tests mapped for {path}")


def drop_pycache():
    for folder in ("atlas/__pycache__", "tests/__pycache__", "tools/__pycache__"):
        shutil.rmtree(folder, ignore_errors=True)


# A mutation can make a test wait forever (a process that never exits); that counts as caught.
RUN_LIMIT_S = 600


def _run(cmd):
    # Own process group: on timeout the whole tree goes, or its open pipes would block the wait.
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
    try:
        return proc.wait(timeout=RUN_LIMIT_S)
    except subprocess.TimeoutExpired:
        os.killpg(proc.pid, signal.SIGKILL)
        proc.wait()
        return 124


def run_python():
    return _run([sys.executable, "-m", "pytest", "-q", "-x", "-p", "no:cacheprovider"])


def run_node(path):
    return _run(["node", "--test", "--test-force-exit", "--test-timeout=120000", *js_tests(path)])


def mutate(path, old, new, run):
    """Applies one mutation, runs the tests, restores the file byte for byte; True = a test failed."""
    with open(path, "rb") as fh:
        original = fh.read()
    backup = path + ".bak"
    shutil.copy2(path, backup)
    try:
        with open(path, "wb") as fh:
            fh.write(original.decode("utf-8").replace(old, new, 1).encode("utf-8"))
        drop_pycache()
        return run() != 0
    finally:
        with open(path, "wb") as fh:
            fh.write(original)
        os.remove(backup)
        # The restored file must not keep the mutated file's mtime: if it matches the one recorded in .pyc,
        # Python treats the cache as valid and keeps running mutated bytecode after the rollback.
        os.utime(path, None)
        drop_pycache()


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only verify that every snippet applies")
    parser.add_argument("--only", metavar="SUBSTR", help="run only mutations whose name contains SUBSTR")
    kind = parser.add_mutually_exclusive_group()
    kind.add_argument("--python", action="store_true", help="only the Python mutations")
    kind.add_argument("--js", action="store_true", help="only the JavaScript mutations")
    parser.add_argument("--shard", metavar="I/N", help="run only every N-th mutation starting at I (1-based)")
    args = parser.parse_args()
    os.chdir(ROOT)

    jobs = ([] if args.js else [(m, False) for m in MUT]) + ([] if args.python else [(m, True) for m in JS_MUT])
    if args.only:
        jobs = [job for job in jobs if args.only in job[0][0]]
    if args.shard:
        index, count = (int(x) for x in args.shard.split("/"))
        jobs = jobs[index - 1::count]
    caught = missed = not_applied = 0
    for (name, path, old, new), is_js in jobs:
        with open(path, encoding="utf-8") as fh:
            if old not in fh.read():
                not_applied += 1
                print(f"  {'NOT APPLIED':12} {name}  [{path}]", flush=True)
                continue
        if args.check:
            continue
        ok = mutate(path, old, new, functools.partial(run_node, path) if is_js else run_python)
        caught += ok
        missed += not ok
        print(f"  {'caught' if ok else 'MISSED':12} {name}", flush=True)

    if args.check:
        print(f"\n{len(jobs) - not_applied}/{len(jobs)} mutations apply")
    else:
        print(f"\n{caught}/{len(jobs)} mutations caught, {missed} missed, {not_applied} not applied")
    return 1 if missed or not_applied else 0


if __name__ == "__main__":
    sys.exit(main())
