"""Mutation testing: break a behaviour and make sure a test turns red.

    python3.11 tools/mutations.py              # every mutation (Python ones via pytest, JS ones via node --test)
    python3.11 tools/mutations.py --check      # only verify that every snippet still applies
    python3.11 tools/mutations.py --only steps # mutations whose name contains "steps"

Each entry is (name, path, old, new): the first occurrence of `old` in `path` becomes `new`. A snippet
that is no longer in the file is a failure, like a mutation the tests miss.

TODO: the full run has not been done since the snippets were re-synced; run it and triage every MISSED.
"""
import argparse
import functools
import os
import shutil
import signal
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MUT = [
 ("installer: a staged install keeps the self-reload marker", "tools/install_plugin.py",
  "        elif os.path.exists(path):\n            os.remove(path)\n", ""),
 ("delete: a running session gets deleted", "atlas/delete.py",
  '    if plan["running"]:\n        raise DeleteError(msg("delete.running"))\n', ""),
 ("delete: other sessions' lines leave the input history", "atlas/delete.py",
  "not (session_id in line and _line_sid(line) == session_id)", "not (session_id in line)"),
 ("delete: deletion outside the Claude Code folder", "atlas/delete.py",
  '            raise DeleteError(msg("delete.outside", path=item["path"]))', "            pass"),
 ("llm: the model is called with AI features off", "atlas/runner.py",
  "    require_llm()                  # last line of defense", "    pass                           # last line of defense"),
 ("llm: model routes stay open with AI features off", "atlas/server.py",
  "                runner.require_llm()\n", "                pass\n"),
 ("llm: the schedule runs with AI features off", "atlas/autoclassify.py",
  "or not runner.llm_enabled() ", ""),
 ("llm: auto-classification cannot be turned off", "atlas/server.py",
  'and body.get("enabled") is False', "and False"),
 ("config: nested user keys get lost", "atlas/config.py",
  "out[key] = dict(base[key], **value)", "out[key] = {k: v for k, v in value.items() if k in base[key]}"),
 ("config: changing settings does not rebuild the index", "atlas/index.py",
  'if db.get_meta(conn, "config_fingerprint") != fingerprint:', "if False:"),
 ("config: tickets are matched even without prefixes", "atlas/config.py",
  "    if not valid:\n        return None", "    if not valid:\n        return re.compile(r\"\\b[A-Z]+-\\d{2,}\\b\")"),
 ("prompts: domains not taken from settings", "atlas/prompts.py",
  '.replace("{domain_ids}", safe(ids))', '.replace("{domain_ids}", "work")'),
 ("runner: 1M without the setting", "atlas/runner.py",
  'if config.get("force_1m") and not has_1m_window(model):', "if not has_1m_window(model):"),
 ("resolve: vault from code, not from settings", "atlas/resolve.py",
  "    for vault, vault_id in config.vaults():\n        if _under(p, vault):", "    for vault, vault_id in [(os.path.join(HOME, \"Notes\"), \"vault\")]:\n        if _under(p, vault):"),
 ("script: start takes priority over the registry", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'elif [[ -z "$session_id" && "$SEED_MODE" == resume* ]]', 'elif [[ "$SEED_MODE" == resume* ]]'),
 ("script: fork without --fork-session", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'claude "${flags[@]}" --resume "$SEED_ID" --fork-session', 'claude "${flags[@]}" --resume "$SEED_ID"'),
 ("script: the hook is not passed", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  '--settings "$(hook_settings)")', ')'),
 ("script: a new session is not written to the registry", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'upsert_resume_id claude "$instance" "$SEED_ID"\n    print "Starting', 'print "Starting'),
 ("script: the transcript is searched only in the vault's folder", "obsidian-plugin/scripts/agent-resume-terminal.zsh",
  'local -a found=("$CLAUDE_PROJECTS_DIR"/*/"$session_id".jsonl(N))',
  'local -a found=("$CLAUDE_PROJECTS_DIR/$(claude_project_slug)/$session_id".jsonl(N))'),
 ("install: scripts are not installed", "tools/install_plugin.py",
  '        shutil.copy(os.path.join(PLUGIN_DIR, "scripts", name), dest)\n', '        pass\n'),
 ("steps: a call error is not shown", "atlas/steps.py",
  'if block.get("is_error"):', 'if False:'),
 ("steps: reads are not merged", "atlas/steps.py",
  'and ev["status"] == "ok" and prev["status"] == "ok"):', 'and False):'),
 ("steps: the reply is repeated as a step", "atlas/steps.py",
  'if reply and events and events[-1]["kind"] == "text":', 'if False:'),
 ("steps: a long turn shows the first steps", "atlas/steps.py",
  'return {"events": merged[hidden:], "earlier": hidden,', 'return {"events": merged[:MAX_EVENTS], "earlier": hidden,'),
 ("steps: the result is not tied to its call", "atlas/feed.py",
  '            turn["collector"].result(rec, content)\n', ''),
 ("touched: subagents are not counted", "atlas/touched.py",
  'sources = [main] + [_scan(p)[0] for p in', 'sources = [main] + [] and [_scan(p)[0] for p in'),
 ("touched: edit lines count the whole text", "atlas/touched.py",
  'if len(a) + len(b) > MAX_DIFF_LINES:', 'if True:'),
 ("touched: the tail is re-read in full", "atlas/touched.py",
  'if cached and cached[0] == st.st_ino and cached[1] <= st.st_size:', 'if False:'),
 ("touched: a rewritten file is read incrementally", "atlas/touched.py",
  'and cached[1] <= st.st_size:', ':'),
 ("closed: live sessions also listed as closed", "atlas/active.py",
  'if r["session_id"] not in live_ids][:limit]', '][:limit]'),
 ("closed: background runs listed as closed", "atlas/active.py",
  "WHERE s.session_kind = 'interactive' AND s.last_activity_at >= ?", "WHERE s.last_activity_at >= ?"),
 ("closed: no time window", "atlas/active.py",
  "AND s.last_activity_at >= ?\n            ORDER BY", "AND ? IS NOT NULL\n            ORDER BY"),
 ("tasks: count deleted ones", "atlas/tasks.py",
  'if not isinstance(task, dict) or task.get("status") == "deleted":', 'if not isinstance(task, dict):'),
 ("tasks: order by file name, not by number", "atlas/tasks.py",
  '"*.json")), key=_number):', '"*.json"))):'),
 ("tasks: empty without activeForm", "atlas/tasks.py",
  't["active_form"] or t["subject"] for t in items', 't["active_form"] for t in items'),
 ("stats: do not collapse reply copies", "atlas/stats.py",
  "   GROUP BY a.key)", "   GROUP BY a.key, a.session_id, a.ts)"),
 ("stats: pauses count as work", "atlas/activity.py",
  "return gap if gap <= IDLE_SECONDS else 0.0", "return gap"),
 ("stats: subagent time counts as work", "atlas/activity.py",
  "0.0 if sub else r[\"active_s\"]", "r[\"active_s\"]"),
 ("stats: the gap is not credited to the reply", "atlas/activity.py",
  "    row[\"active_s\"] += facts.pending_active\n", ""),
 ("stats: an incrementally read reply overwrites the time", "atlas/activity.py",
  "active_s = active_s + excluded.active_s", "active_s = excluded.active_s"),
 ("stats: do not merge parallel sessions", "atlas/stats.py",
  "if cur_end is None or start > cur_end:", "if True:"),
 ("stats: MCP per call", "atlas/stats.py",
  "return \"tools\", \"MCP \" + name.split(\"__\")[1]", "return \"tools\", name"),
 ("stats: skill without a name", "atlas/activity.py",
  "name = \"Skill:\" + str(args[\"skill\"])", "pass"),
 ("stats: slash command not shown", "atlas/activity.py",
  "\"tools\": _command(rec)}", "\"tools\": []}"),
 ("stats: period without a start", "atlas/stats.py",
  "WHERE a.ts >= :since AND", "WHERE 1 AND"),
 ("parse: index tool_result", "atlas/parse.py",
  'if block.get("type") != _TEXT_BLOCK:\n            continue  # tool_result / image / document: never indexed',
  'if False:\n            continue'),
 ("parse: treat the compaction summary as a prompt", "atlas/parse.py",
  'if text.startswith(COMPACT_PREFIX):', 'if False:'),
 ("parse: read an unfinished line too", "atlas/parse.py",
  'if not raw.endswith(b"\\n"):\n            break', 'if False:\n            break'),
 ("index: always treat the file as unchanged", "atlas/index.py",
  'return row is None or row["sig"] != sig', 'return row is None'),
 ("index: ignore subagents in the signature", "atlas/index.py",
  'for path in [session_path, *subagents]:', 'for path in [session_path]:'),
 ("query: stem identifiers and numbers", "atlas/query.py",
  'if IDENTIFIER_RE.search(word):\n        return "exact"', 'if False:\n        return "exact"'),
 ("resolve: a file in the ~/Code root becomes a project", "atlas/resolve.py",
  'if rel_to_prefix == name and (name.startswith(".") or os.path.splitext(name)[1]):',
  'if False:'),
 ("resolve: claude-desktop goes to automation", "atlas/resolve.py",
  'if entrypoint in HEADLESS_ENTRYPOINTS:', 'if entrypoint and entrypoint != "cli":'),
 ("search: show automation by default", "atlas/search.py",
  'if not include_automation and not kinds:\n        where.append("s.session_kind = \'interactive\'")',
  'if False:\n        where.append("s.session_kind = \'interactive\'")'),
 ("index: do not clear old rows before writing", "atlas/store.py",
  '    purge(conn, session_id)\n    activity.store(', '    activity.store('),
 ("index: incremental read without clearing metadata", "atlas/store.py",
  '    purge(conn, session_id, keep_text=True)\n', ''),
 ("index: incremental read does not rewrite the last turn", "atlas/store.py",
  'conn.execute("DELETE FROM fts WHERE session_id=? AND turn>=?", (session_id, first))', 'pass'),
 ("index: read incrementally after a rewritten file", "atlas/store.py",
  'or row["sub_sig"] != sub_sig or tail_sig(path, row["offset"]) != row["tail_sig"]:',
  'or row["sub_sig"] != sub_sig:'),
 ("index: do not remove vanished sources", "atlas/index.py",
  'if path not in present:', 'if False:'),
 ("db: rebuild also wipes manual edits", "atlas/db.py",
  'DERIVED = (', 'DERIVED = ("user_overrides",\n'),
 ("resolve: a scratchpad becomes a project", "atlas/resolve.py",
  'if SCRATCHPAD_RE.match(p):', 'if False:'),
 ("resolve: sensitivity defaults to normal", "atlas/resolve.py",
  'return UNCLASSIFIED', 'return "normal"'),
 ("resolve: path comparison via startswith", "atlas/resolve.py",
  'return os.path.commonpath([os.path.normpath(path), root]) == root',
  'return os.path.normpath(path).startswith(root)'),
 ("query: no truncation to the stem", "atlas/query.py",
  'return token[: max(STEM_FLOOR, n - cut)]', 'return token'),
 ("query: always cut the trailing consonant of a stem", "atlas/query.py",
  'if not cut and low[-1] in _SOFT_TAIL:', 'if not cut:'),
 ("query: short Russian words without word forms", "atlas/query.py",
  'if SHORT_CYR_RE.match(word):\n        return "forms"', 'if False:\n        return "forms"'),
 ("query: OR works as AND", "atlas/query.py",
  'parsed.groups[-1].append(term)', 'parsed.groups.append([term])'),
 ("query: minus does not exclude", "atlas/query.py",
  'parsed.excluded.append(term)', 'parsed.groups.append([term])'),
 ("query: the match is not highlighted", "atlas/query.py",
  'add(text[a:b], True)', 'add(text[a:b], False)'),
 ("query: snippet window ignores distinct words", "atlas/query.py",
  'key = (len(set(inside)), len(inside))', 'key = (0, 0)'),
 ("search: do not report the matched field", "atlas/search.py",
  'if not hits:\n                continue\n            distinct', 'if True:\n                continue\n            distinct'),
 ("search: snippet from the first turn, not the best one", "atlas/search.py",
  'if (distinct, hits) > slot["_best"]:', 'if slot["_best"] == (-1, -1):'),
 ("search: the title counts in the total match count", "atlas/search.py",
  'body = [m for m in matches if m["field"] != "title"] or matches', 'body = matches'),
 ("search: total covers only the page", "atlas/search.py",
  'out["total"] = len(rows)', 'out["total"] = len(rows[:limit])'),
 ("search: stay silent about matches outside prompts", "atlas/search.py",
  'if scope == "prompts":\n        wide', 'if False:\n        wide'),
 ("search: relevance is plain bm25", "atlas/search.py",
  'return sorted(cands, key=lambda c: (c[0] not in in_title, -pairs[c[0]], position[c[0]]))',
  'return cands'),
 ("db: write the schema on every connection", "atlas/db.py",
  'if _schema_is_current(conn):\n        return conn', 'if False:\n        return conn'),
 ("server: do not catch up the index for the list", "atlas/server.py",
  'indexing = catch_up()', 'indexing = False'),
 ("server: catch up on every keystroke", "atlas/server.py",
  'if time.monotonic() - _catchup_at < CATCHUP_EVERY:\n            return False', 'if False:\n            return False'),
 ("server: wait for another process's running pass too", "atlas/server.py",
  'return True     # do not wait for another pass', 'current = _catchup_proc  # do not wait for another pass'),
 ("server: wait for a long pass to finish", "atlas/server.py",
  'current.join(CATCHUP_WAIT)', 'current.join()'),
 ("actions: do not escape command arguments", "atlas/actions.py",
  'return f"cd {shlex.quote(cwd)} && " + " ".join(shlex.quote(p) for p in parts)\n\n\ndef new_session_command',
  'return f"cd {cwd} && " + " ".join(parts)\n\n\ndef new_session_command'),
 ("actions+db: both the early return and the UNIQUE index removed", "atlas/db.py",
  "CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_active", "CREATE INDEX IF NOT EXISTS ux_jobs_active"),
 ("runner: send data out without permission", "atlas/runner.py",
  'raise EgressDenied(', 'return None or EgressDenied('),
 ("runner: treat litellm as local", "atlas/runner.py",
  'LOCAL_BACKENDS = {"ollama", "lmstudio", "llamacpp"}',
  'LOCAL_BACKENDS = {"ollama", "lmstudio", "llamacpp", "claude-cli"}'),
 ("enrich: repair broken JSON heuristically", "atlas/enrich.py",
  'raise ValueError(msg("enrich.no_json"))', 'return {"did": text}'),
 ("enrich: do not require handoff sections", "atlas/enrich.py",
  'if missing:', 'if False:'),
 ("server: accept a foreign Origin", "atlas/server.py",
  'if origin and origin not in ALLOWED_ORIGINS:', 'if False:'),
 ("server: do not check the CSRF token", "atlas/server.py",
  'if self.headers.get("X-Atlas-Token") != csrf_token():', 'if False:'),
 ("server: accept any export target", "atlas/server.py",
  'if label not in destinations:', 'if False:'),
 ("search: domain rule outranks the model's verdict", "atlas/search.py",
  'elif verdict and verdict["domain"]:\n        final_domains, domain_source = [verdict["domain"]], "llm"\n    elif domains:\n        final_domains, domain_source = domains, "rule"',
  'elif domains:\n        final_domains, domain_source = domains, "rule"\n    elif verdict and verdict["domain"]:\n        final_domains, domain_source = [verdict["domain"]], "llm"'),
 ("search: a manual topic does not override the model", "atlas/search.py",
  '"topic": ((override["topic"] if override and override["topic"] else None)\n                  or (verdict["topic"] if verdict else None)),',
  '"topic": (verdict["topic"] if verdict else None),'),
 ("db: classification back in the cheap derived table", "atlas/db.py",
  'DERIVED = (\n    "sources", "sessions"', 'DERIVED = (\n    "classification", "enrichment",\n    "sources", "sessions"'),
 ("db: a schema upgrade does not request a rebuild", "atlas/db.py",
  "conn.execute(\"INSERT INTO meta(key, value) VALUES('needs_reindex', '1') \"\n                 \"ON CONFLICT(key) DO UPDATE SET value='1'\")",
  "pass"),
 ("index: ensure_indexed does nothing", "atlas/index.py",
  'if db.get_meta(conn, "needs_reindex") != "1":\n        return None',
  'if True:\n        return None'),
 ("classify: sensitive sessions are sent out", "atlas/classify.py",
  "AND COALESCE((SELECT sensitivity FROM user_overrides u WHERE u.session_id = s.session_id),\n                       s.sensitivity_rule) != 'sensitive'", "AND 1=1"),
 ("classify: «misc» with high confidence passes", "atlas/classify.py",
  'and confidence >= 0.5:', 'and False:'),
 ("classify: a non-canonical domain is accepted", "atlas/classify.py",
  'if ids and domain not in ids:', 'if False:'),
 ("parse: do not expand the slash command", "atlas/parse.py",
  'prompt = readable_prompt(text)', 'prompt = text'),
 ("search: do not strip the summary preamble", "atlas/search.py",
  'if marker in summary[:400]:', 'if False:'),
 ("classify: do not return the one-line description", "atlas/classify.py",
  'summary = " ".join((data.get("summary") or "").split())[:200]', 'summary = None'),
 ("runner: summaries and prompts are cut first", "atlas/runner.py",
  'take(t_summaries, facts.summaries)\n    take(t_prompts, facts.user_text)\n    take(t_answers, facts.assistant_text)',
  'take(t_answers, facts.assistant_text)\n    take(t_summaries, facts.summaries)\n    take(t_prompts, facts.user_text)'),
 ("runner: take replies from the start, not the end", "atlas/runner.py",
  'for text in reversed(items):', 'for text in items:'),
 ("runner: chars per token as for English", "atlas/runner.py",
  'CHARS_PER_TOKEN = 2.1', 'CHARS_PER_TOKEN = 4.0'),
 ("runner: do not pre-check a large call", "atlas/runner.py",
  'if len(prompt) > PREFLIGHT_ABOVE:\n        preflight(effort=effort)', 'pass'),
 ("search: do not limit prompt length in the card", "atlas/search.py",
  '    if len(out) <= limit:\n        return out', '    return out'),
 ("web: a long path in the snippet stretches the card", "web/js/atlas.css",
  'white-space:pre-wrap;overflow-wrap:anywhere}', 'white-space:pre-wrap}'),
 ("runner: look for claude only in PATH", "atlas/runner.py",
  '''    for candidate in CLAUDE_CANDIDATES:
        path = os.path.expanduser(candidate)
        if os.access(path, os.X_OK):
            return path
''', ''),
 ("actions: renaming overwrites the transcript", "atlas/actions.py",
  'with open(row["source_path"], "a", encoding="utf-8") as fh:',
  'with open(row["source_path"], "w", encoding="utf-8") as fh:'),
 ("search: a manual title does not override the recorded one", "atlas/search.py",
  '"title": (override["title"] if override and override["title"] else row["title"]),',
  '"title": row["title"],'),
 ("db: do not migrate the old schema", "atlas/db.py",
  'if int(row["value"]) >= SCHEMA_VERSION:\n        return', 'if True:\n        return'),
 ("active: accept a foreign process with the same PID", "atlas/active.py",
  'return proc_start is None or table[pid][1] == " ".join(proc_start.split())', 'return True'),
 ("active: show background runs", "atlas/active.py",
  'return data.get("kind") == "interactive" and data.get("entrypoint") not in HEADLESS_ENTRYPOINTS',
  'return True'),
 ("active: do not sort by the last message", "atlas/active.py",
  'out.sort(key=lambda s: _as_datetime(s["last_message_at"]), reverse=True)', 'pass'),
 ("active: freshness only from the index", "atlas/active.py",
  'tail = found["last_at"]', 'tail = None'),
 ("active: notifications and summaries count as a message", "atlas/active.py",
  'return kind == "assistant" or not text.startswith(NOT_A_MESSAGE)', 'return True'),
 ("active: do not look past a tail of tool calls", "atlas/active.py",
  'window *= 4           # a tail made only of tool calls', 'return out            # a tail made only of tool calls'),
 ("runner: handoff without the 1M window", "atlas/runner.py",
  'NATIVE_1M = {"claude-opus-5-5"}', 'NATIVE_1M = set()'),
 ("active: reply tail is the start, not the end", "atlas/active.py",
  '    tail = text[cut:]\n', '    tail = text[:limit]\n'),
 ("active: waiting_for on an idle session too", "atlas/active.py",
  '"waiting_for": data.get("waitingFor") if data.get("status") == "waiting" else None,',
  '"waiting_for": data.get("waitingFor"),'),
 ("uploads: accept any bytes as an image", "atlas/uploads.py",
  'if ext is None:\n        raise UploadError', 'if False:\n        raise UploadError'),
 ("uploads: the file is world-readable", "atlas/uploads.py",
  'os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600', 'os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644'),
 ("uploads: do not clean up old ones", "atlas/uploads.py",
  'if now - os.stat(path).st_mtime > KEEP_SECONDS:', 'if False:'),
 ("active: do not count shell status as work", "atlas/active.py",
  'if status in ("busy", "shell"):', 'if status == "busy":'),
 ("active: a lone /goal already counts as «in background»", "atlas/active.py",
  'if background["shells"] or background["agents"] or background["wake_at"] \\',
  'if background["goal"] or background["shells"] or background["agents"] or background["wake_at"] \\'),
 ("active: count MCP servers as background commands", "atlas/active.py",
  'if row[0] == pid and len(row) > 2 and SHELL_TASK_MARK in row[2])',
  'if row[0] == pid and len(row) > 2)'),
 ("active: a past wakeup still waits", "atlas/active.py",
  'if wake and wake > now:', 'if wake:'),
 ("active: do not reopen a code block in the tail", "atlas/active.py",
  'return (FENCE + "\\n" + tail) if fences % 2 else tail', 'return tail'),
 ("active: cut the tail mid-line", "atlas/active.py",
  'if 0 <= line < len(text) - 1:\n        cut = line + 1', 'if False:\n        cut = line + 1'),
 ("active: treat command output as the user's message", "atlas/active.py",
  '"<local-command-stdout>", ', ''),
 ("active: command with tags, not as typed", "atlas/active.py",
  '    m = _COMMAND_RE.search(text)\n    if m:', '    m = None\n    if m:'),
 ("costs: count one reply per line", "atlas/costs.py",
  'if key in seen or msg.get("model") == SYNTHETIC:', 'if msg.get("model") == SYNTHETIC:'),
 ("costs: 1-hour cache write priced as 5-minute", "atlas/costs.py",
  'WRITE_5M, WRITE_1H = 1.25, 2.0', 'WRITE_5M, WRITE_1H = 1.25, 1.25'),
 ("costs: do not reset incremental counting on writes", "atlas/costs.py",
  'recorded, stamp, after = float(rec["totalCostUSD"]), last_ts, 0.0',
  'recorded, stamp = float(rec["totalCostUSD"]), last_ts'),
 ("costs: count subagents before the write too", "atlas/costs.py",
  'if stamp and ts > stamp)', ')'),
 ("costs: internal replies are a model without a price", "atlas/costs.py",
  'if key in seen or msg.get("model") == SYNTHETIC:', 'if key in seen:'),
 ("autoclassify: on by default", "atlas/autoclassify.py",
  'return _meta(conn, KEY_ENABLED) == "1"', 'return _meta(conn, KEY_ENABLED) != "0"'),
 ("autoclassify: no hourly pause", "atlas/autoclassify.py",
  'if last and now - float(last) < INTERVAL_SECONDS:', 'if False:'),
 ("autoclassify: classified sessions without a mark are all recomputed", "atlas/autoclassify.py",
  'if r["done"] and r["seen"] is None:', 'if False:'),
 ("autoclassify: changes go unnoticed", "atlas/autoclassify.py",
  'elif not r["done"] or r["seen"] != r["sig"]:', 'elif not r["done"]:'),
 ("autoclassify: no per-pass limit", "atlas/autoclassify.py", 'return out[:MAX_PER_RUN]', 'return out'),
 ("autoclassify: runs on top of a running classification", "atlas/autoclassify.py",
  'if not enabled(conn) or not runner.llm_enabled() or _job_running(conn):',
  'if not enabled(conn) or not runner.llm_enabled():'),
 ("autoclassify: fresh sessions too", "atlas/autoclassify.py",
  "WHERE s.session_kind = 'interactive' AND s.started_at <= ?",
  "WHERE s.session_kind = 'interactive' AND ? IS NOT NULL"),
 ("autoclassify: sensitive sessions are sent out", "atlas/autoclassify.py",
  "'unclassified') != 'sensitive'", "'unclassified') != 'никогда'"),
 ("autoclassify: no «What was done»", "atlas/autoclassify.py", '            summary(conn, sid, job_id)\n', ''),
 ("autoclassify: no mark after a pass", "atlas/autoclassify.py",
  '        _mark(conn, sid, sig)                  # on failure', '        pass                  # on failure'),
 ("autoclassify: «What was done» without an egress grant", "atlas/autoclassify.py",
  '    runner.grant_egress(conn, session_id, payload["content_hash"], SUMMARY_KIND,\n'
  '                        runner.EXTERNAL_BACKEND, model)\n', ''),
 ("server: every Active poll recomputes", "atlas/server.py",
  'time.monotonic() - _active_cached["at"] < ACTIVE_REUSE_SECONDS:', 'False:'),
 ("active: an interruption counts as a message", "atlas/active.py",
  '"A session-scoped Stop hook is now active", "Caveat: The messages below",\n                 "[Request interrupted by user")',
  '"A session-scoped Stop hook is now active", "Caveat: The messages below")'),
 ("active: an interruption is not marked", "atlas/active.py",
  'out["interrupted_at"] = rec.get("timestamp")', 'pass'),
 ("launch: a folder not from the list", "atlas/launch.py",
  'if not isinstance(cwd, str) or cwd not in {w["path"] for w in workdirs(conn)}:',
  'if not isinstance(cwd, str):'),
 ("launch: a prompt starting with - goes as a flag", "atlas/launch.py",
  'parts.append(" " + prompt if prompt.startswith("-") else prompt)', 'parts.append(prompt)'),
 ("launch: the prompt is not escaped", "atlas/launch.py",
  '" ".join(shlex.quote(p) for p in parts)', '" ".join(parts)'),
 ("launch: a session scratchpad in the list", "atlas/launch.py",
  'and "/scratchpad" not in path', 'and True'),
 ("launch: hidden folders in the list", "atlas/launch.py",
  'and not any(part.startswith(".") for part in path.split(os.sep))', ''),
 ("queue: dequeue does not remove", "atlas/prompt_queue.py",
  'elif op == "dequeue":\n            if queue:\n                queue.pop(0)', 'elif op == "dequeue":\n            pass'),
 ("queue: dequeue removes from the end", "atlas/prompt_queue.py",
  'if queue:\n                queue.pop(0)', 'if queue:\n                queue.pop()'),
 ("queue: popAll does not clear", "atlas/prompt_queue.py", 'queue.clear()', 'pass'),
 ("queue: notifications are shown as prompts", "atlas/prompt_queue.py",
  'if q["text"].strip() and not q["text"].startswith(SYSTEM_PREFIXES)]', 'if q["text"].strip()]'),
 ("queue: remove by position, not by text", "atlas/prompt_queue.py",
  'same = [i for i, q in enumerate(queue) if content and q["text"] == content]', 'same = [0] if queue else []'),
 ("feed: the window does not grow", "atlas/feed.py", 'window *= 4', 'return built[-turns:]'),
 ("feed: a notification starts a new turn", "atlas/feed.py",
  'if kind == "user" and active.is_message(rec):', 'if kind == "user":'),
 ("feed: edited files counted by calls", "atlas/feed.py",
  'files = len(g["detail"]) or n\n            text = nplural("feed.edited"', 'files = n\n            text = nplural("feed.edited"'),
 ("feed: the reply is the turn's first text", "atlas/feed.py",
  'turn["reply"] = block["text"].strip()', 'turn["reply"] = turn["reply"] or block["text"].strip()'),
 ("feed: an interruption is not marked", "atlas/feed.py", 'turn["interrupted"] = True', 'pass'),
 ("feed: the tail of an earlier turn shows up", "atlas/feed.py",
  '        if not turns:\n            continue', '        if not turns:\n            turns.append(_new_turn(rec))'),
 ("commands: a skill named by its name field", "atlas/commands.py",
  'out.append({"name": prefix + name, "kind": kind,',
  'out.append({"name": prefix + (_frontmatter(md).get("name") or name), "kind": kind,'),
 ("commands: a built-in command is duplicated", "atlas/commands.py",
  '        if c["name"] not in seen:', '        if True:'),
 ("commands: internal skills in the list", "atlas/commands.py",
  'if name.startswith(("_", ".")) or not os.path.isfile(md):', 'if not os.path.isfile(md):'),
 ("context: the window is always 200k", "atlas/costs.py",
  'if tokens and tokens > WINDOW_DEFAULT:\n        return WINDOW_1M', 'if False:\n        return WINDOW_1M'),
 ("context: a subagent changes the session context", "atlas/costs.py",
  'if not rec.get("isSidechain"):\n            ctx, model', 'if True:\n            ctx, model'),
 ("context: cache writes not counted", "atlas/costs.py",
  '("input_tokens", "cache_read_input_tokens", "cache_creation_input_tokens"))', '("input_tokens", "cache_read_input_tokens"))'),
 ("limits: a reset given as a string is not read", "atlas/limits.py",
  'if value.replace(".", "").isdigit():\n            return _iso(float(value))', 'if False:\n            return None'),
 ("statusline: garbage overwrites the file", "atlas/statusline.py",
  'if isinstance(data, dict) and _has_window(data.get("rate_limits")):',
  'if isinstance(data, dict) and isinstance(data.get("rate_limits"), dict):'),
 ("statusline: crashes on garbage", "atlas/statusline.py",
  'limits = limits if isinstance(limits, dict) else {}', 'limits = limits or {}'),
 ("relocate: a session already in Obsidian is killed too", "atlas/relocate.py",
  'if app == "Obsidian":\n        raise RelocateError(msg("relocate.in_obsidian"))', 'if False:\n        pass'),
 ("relocate: a foreign session by PID", "atlas/relocate.py",
  'if not data or data.get("sessionId") != session_id or not active.is_interactive(data):',
  'if not data or not active.is_interactive(data):'),
 ("relocate: a reused PID", "atlas/relocate.py",
  'if not active._alive(pid, data.get("procStart"), table):\n        raise',
  'if pid not in table:\n        raise'),
 ("relocate: a zombie counts as alive", "atlas/relocate.py",
  '\n        or _command(table, pid).strip() == "<defunct>"', ''),
 ("relocate: the app is the nearest .app", "atlas/relocate.py",
  '        if m:\n            found = m.group(1)\n    return found', '        if m:\n            return m.group(1)\n    return found'),
 ("models: force_1m does not add the [1m] suffix", "atlas/runner.py",
  '        model += "[1m]"\n', '        pass\n'),
 ("models: «What was done» on medium", "atlas/config.py",
  '"catalog_summary": ["sonnet", "low"],', '"catalog_summary": ["sonnet", "medium"],'),
 ("enrich: «What was done» template via format", "atlas/enrich.py",
  'return template.replace("{payload}", text)', 'return template.format(payload=text)'),
 ("commands: frequent ones not first", "atlas/commands.py",
  'return first + rest', 'return sorted(pool, key=lambda c: c["name"].lower())'),
 ("commands: a disabled plugin in the list", "atlas/commands.py",
  '(entry.get("scope") != "user" or enabled.get(full))', 'True'),
 ("commands: no organization plugins", "atlas/commands.py",
  '    for manifest in glob.glob(', '    for manifest in []:  # glob.glob('),
]
JS_MUT = [
 ("plugin: a reload ends agents in background tabs", "obsidian-plugin/src/term-view.js",
  "    window.clearTimeout(held.timer);\n    held.timer = null;\n    kept.push(key);", "    kept.push(key);"),
 ("plugin: reload treated as «disabled by user» (closes tabs)", "obsidian-plugin/src/reload.js",
  "await plugins.disablePlugin(id);", "await plugins.disablePlugin(id, true);"),
 ("plugin: an old-version server is not replaced", "obsidian-plugin/src/runtime.js",
  "if (!stale) return { ok: true, reason: null };", "if (true) return { ok: true, reason: null };"),
 ("plugin: a new build on disk is not picked up", "obsidian-plugin/src/reload.js",
  "if (this.reloadInPlace()) new Notice", "if (false) new Notice"),
 ("plugin: first launch overwrites agent arguments", "obsidian-plugin/src/main.js",
  "if (!saved.agentArgs && this.adoptAgentArgs()) await this.saveData(this.settings);", ""),
 ("runtime: python without CLT is used anyway", "obsidian-plugin/src/runtime.js",
  '.filter((p) => p !== "/usr/bin/python3" || clt);', ";"),
 ("runtime: old files are not removed", "obsidian-plugin/src/runtime.js",
  "if (!keep.has(path.join(sub, rel))) fsSync.rmSync(path.join(root, rel), { force: true });", ""),
 ("runtime: a foreign server on the port is taken as ours", "obsidian-plugin/src/runtime.js",
  'if (health && health.app === "session-atlas") {\n      // A server', 'if (health) {\n      // A server'),
 ("pty: size is not set before start", "obsidian-plugin/src/pty.js",
  """const INNER = 'stty rows "$1" cols "$2" 2>/dev/null; shift 2; exec "$@"';""",
  """const INNER = 'shift 2; exec "$@"';"""),
 ("pty: closing does not kill the group", "obsidian-plugin/src/pty.js",
  "try { process.kill(-child.pid, signal); }", "try { process.kill(child.pid, signal); }"),
 ("config-form: duplicate domains", "obsidian-plugin/src/config-form.js",
  " || out.some((d) => d.id === id)) continue;", ") continue;"),
 ("plugin: parsing lets ; and $ through", "obsidian-plugin/src/agents.js",
  "    } else {\n      return null;\n    }\n  }\n  if (cur !== null) out.push(cur);",
  "    } else {\n      cur = (cur || \"\") + c; i++;\n    }\n  }\n  if (cur !== null) out.push(cur);"),
 ("plugin: extra claude flags are accepted", "obsidian-plugin/src/agents.js",
  'if (flag === "--resume" && rest.length === 0)', 'if (flag === "--resume")'),
 ("plugin: prompt unquoted in tab arguments", "obsidian-plugin/src/agents.js",
  "if (seed.prompt) parts.push(shellQuote(seed.prompt));", "if (seed.prompt) parts.push(seed.prompt);"),
 ("plugin: directory bypasses the script", "obsidian-plugin/src/terminal.js",
  'if (launch && (await this.openAgent("claude", { cwd: launch.cwd, seed: launch, label }))) return;', ''),
 ("plugin: pointerdown on the close button is not suppressed", "obsidian-plugin/src/guard.js",
  "    if (!this.guardKind(leaf)) return;\n    event.preventDefault();\n    event.stopPropagation();\n    event.stopImmediatePropagation();\n    if (ask)",
  "    if (!this.guardKind(leaf) || !ask) return;\n    event.preventDefault();\n    event.stopPropagation();\n    event.stopImmediatePropagation();\n    if (ask)"),
 ("plugin: ⌘W without confirmation", "obsidian-plugin/src/guard.js",
  "if (leaf && original.call(this, true)) {", "if (false) {"),
 ("plugin: file explorer duplicates an open file", "obsidian-plugin/src/explorer.js",
  "    if (open) {", "    if (false) {"),
 ("plugin: file explorer swallows a folder click", "obsidian-plugin/src/explorer.js",
  "if (!(file instanceof TFile)) return;", "if (!file) return;"),
 ("plugin: restore without delay", "obsidian-plugin/src/restore.js",
  "&& Date.now() - (this.loadedAt || 0) >= RESTORE_GRACE_MS", ""),
 ("plugin: Obsidian language is ignored", "obsidian-plugin/src/i18n.js",
  'return String(obsidianLanguage || "").toLowerCase().startsWith("ru") ? "ru" : "en";', 'return "en";'),
 ("logic: jump — one word is enough", "web/js/logic.js",
  "if (!words.every(w => hay.includes(w))) return;", "if (!words.some(w => hay.includes(w))) return;"),
 ("logic: jump — closed ranked equal to live", "web/js/logic.js",
  'scored.push([it.kind === "live" ? 0 : 1, head, i, it]);', "scored.push([0, head, i, it]);"),
 ("logic: jump — title prefix does not matter", "web/js/logic.js",
  "const head = words.length && title.startsWith(words[0]) ? 0 : 1;", "const head = 0;"),
 ("plugin: plan — text without checking the field", "obsidian-plugin/src/input.js",
  "if (!(await seen((f) => f.n === field.n && f.selected))) {", "if (false) {"),
 ("plugin: plan — Enter without verifying the text", "obsidian-plugin/src/input.js",
  "if (!(await seen((f) => squash(f.typed) === squash(text)))) {", "if (false) {"),
 ("plugin: plan — feedback into the wrong option", "obsidian-plugin/src/input.js",
  "if (!field || field.n !== data.option ||", "if (!field ||"),
 ("plugin: plan — line breaks not removed", "obsidian-plugin/src/input.js",
  '.replace(/\\s+/g, " ").trim();\n    if (!text', '.trim();\n    if (!text'),
 ("plugin: plan not recognized as a plan", "obsidian-plugin/src/dialog.js",
  "  const plan = parsePlanDialog(rows);\n  if (plan) return plan;\n", ""),
 ("plugin: feedback field among the buttons", "obsidian-plugin/src/dialog.js",
  "feedback = options.pop();", "feedback = options[options.length - 1];"),
 ("page: top level calls a function from a later file", "web/js/active-feed.js",
  'let feedView = loadStored(FEED_VIEW_KEY, "turns");', 'let feedView = closedSection(FEED_VIEW_KEY);'),
 ("logic: error filter lets everything through", "web/js/logic.js",
  'error: ev => ev.status === "error"', 'error: ev => true'),
 ("logic: a sibling folder's path counts as own", "web/js/logic.js",
  'path.startsWith(cwd.replace(/\\/$/, "") + "/")', 'path.startsWith(cwd)'),
 ("page: same-named function in two files", "web/js/stats.js",
  "function saveStatsPrefs() {", "function segmented() {}\nfunction saveStatsPrefs() {"),
 ("logic: tasks without status marks", "web/js/logic.js",
  "`${TASK_MARK[i.status] || \"○\"} ${i.subject}`", "i.subject"),
 ("logic: show an empty task list", "web/js/logic.js",
  "if (!t || !t.total) return null;", "if (!t) return null;"),
 ("stats-logic: billions shown as millions", "web/js/stats-logic.js",
  "if (a >= 1e9)", "if (a >= 1e19)"),
 ("stats-logic: growth with a minus sign", "web/js/stats-logic.js",
  '(pct > 0 ? "+" : "−")', '"−"'),
 ("stats-logic: division by zero in comparison", "web/js/stats-logic.js",
  "|| prev <= 0) return null", ") return null"),
 ("stats-logic: sorting not by the measure", "web/js/stats-logic.js",
  ".sort((a, b) => b[metric] - a[metric])", ".sort(() => 0)"),
 ("stats-logic: empty values not dropped", "web/js/stats-logic.js",
  ".filter(i => i[metric] > 0)", ".filter(() => true)"),
 ("plugin: do not check message origin", "obsidian-plugin/src/main.js",
  'if (event.origin !== this.atlasOrigin()) return;', 'if (false) return;'),
 ("plugin: do not check message source", "obsidian-plugin/src/main.js",
  'if (!data || data.source !== "session-atlas") return;', 'if (!data) return;'),
 ("plugin: accept any action type", "obsidian-plugin/src/main.js",
  'if (data.type === "resume" || data.type === "new-session") {', 'if (true) {'),
 ("plugin: inline iframe with an extra scrollbar", "obsidian-plugin/styles.css",
  '.session-atlas-frame {\n  display: block;\n', '.session-atlas-frame {\n'),
 ("plugin: type into a session with an open dialog", "obsidian-plugin/src/input.js",
  'if (state.status === "waiting") {', 'if (false) {'),
 ("plugin: do not check that the process belongs to this tab", "obsidian-plugin/src/input.js",
  'if (!this.isDescendant(data.claudePid, data.ptyPid)) {', 'if (false) {'),
 ("plugin: do not verify the session id", "obsidian-plugin/src/input.js",
  'if (!state || state.sessionId !== data.sessionId) return', 'if (!state) return'),
 ("plugin: let control characters through", "obsidian-plugin/src/terminal.js",
  '.replace(/[\\x00-\\x08\\x0b-\\x1f\\x7f]/g, "")', ''),
 ("plugin: multiline without paste", "obsidian-plugin/src/input.js",
  'stdin.write(text.includes("\\n") ? PASTE_START + text + PASTE_END : text);', 'stdin.write(text);'),
 ("plugin: no Enter after the text", "obsidian-plugin/src/input.js",
  'window.setTimeout(() => stdin.write("\\r"),', 'window.setTimeout(() => null,'),
 ("plugin: images from any folder", "obsidian-plugin/src/terminal.js",
  'if (!full.startsWith(root) || !IMAGE_EXT.test(full)', 'if (!IMAGE_EXT.test(full)'),
 ("plugin: image path without a separate paste", "obsidian-plugin/src/input.js",
  'for (const image of images) stdin.write(PASTE_START + image + PASTE_END + " ");',
  'for (const image of images) stdin.write(image + " ");'),
 ("plugin: close a tab without confirmation", "obsidian-plugin/src/main.js",
  'this.confirmClose(tab.leaf, title || tab.title);', 'tab.leaf.detach();'),
 ("plugin: send the tab list to any origin", "obsidian-plugin/src/main.js",
  '}, this.atlasOrigin());\n  }\n\n  async actOnTab', '}, "*");\n  }\n\n  async actOnTab'),
 ("plugin: wait for a hung terminal without a timeout", "obsidian-plugin/src/terminal.js",
  'new Promise((resolve) => window.setTimeout(() => resolve(null), PTY_WAIT_MS)),',
  'new Promise(() => {}),'),
 ("plugin: do not check that the command is a string", "obsidian-plugin/src/main.js",
  'if (typeof data.command !== "string" || !data.command) return;', ''),
 ("page: a javascript: link is clickable", "web/js/markdown.js",
  r'const SAFE_URL = /^(https?:\/\/|mailto:)/i;', 'const SAFE_URL = /./;'),
 ("page: snake_case turns italic", "web/js/markdown.js",
  "{ re: /(^|[^\\w*])\\*([^*\\s][^*\\n]*?)\\*(?!\\w)/,", "{ re: /(^|[^*])\\*([^*\\n]*?)\\*/,"),
 ("page: a trailing period goes into the URL link", "web/js/markdown.js",
  """[^\\s<>()\\].,;:!?'"»]/,""", """/,"""),
 ("page: a code block parses markup", "web/js/markdown.js",
  'blocks.push({ t: "pre", text: body.join("\\n") });', 'blocks.push({ t: "p", lines: body.map(parseInline) });'),
 ("page: switching - to 1. without a new list", "web/js/markdown.js",
  '&& stack[stack.length - 1].list.ordered !== ordered) stack.pop();', '&& false) stack.pop();'),
 ("page: list filters — AND instead of OR", "web/js/logic.js",
  'valuesOf(s, key, now).some(v => want.has(v))', '[...want].every(v => valuesOf(s, key, now).includes(v))'),
 ("page: the counter applies its own filter", "web/js/logic.js",
  'sessions.filter(s => passes(s, filters, key, now))', 'sessions.filter(s => passes(s, filters, null, now))'),
 ("page: layout without a limit", "web/js/logic.js",
  'return m && +m[1] <= max && +m[2] <= max ?', 'return m ?'),
 ("page: yesterday counts as this week", "web/js/logic.js",
  'if (days === 1) return "yesterday";', ''),
 ("page: a sent item is not cleared once the transcript catches up", "web/js/logic.js",
  '|| t(s.prompt_at) >= t(sent.at) - 2000)', ')'),
 ("page: down moves one card, not one row", "web/js/logic.js",
  'ArrowDown: cols, ArrowUp: -cols', 'ArrowDown: 1, ArrowUp: -1'),
 ("page: navigation goes past the edge", "web/js/logic.js",
  'return ids[Math.max(0, Math.min(ids.length - 1, i + step))];', 'return ids[i + step];'),
 ("page: the current estimate has no increment", "web/js/logic.js",
  's.cost_now - s.cost_usd >= 0.005', 'true'),
 ("page: a silent plugin is «checking» forever", "web/js/logic.js",
  'if (askedAt && now - askedAt > HOST_REPLY_MS) {', 'if (false) {'),
 ("plugin: tabs without a process — connection «on»", "obsidian-plugin/src/terminal.js",
  'if (leaves.length && !tabs.length) {', 'if (false) {'),
 ("plugin: notify about a new session", "obsidian-plugin/src/notify.js",
  'if (was === undefined || was === now) continue;', 'if (was === now) continue;'),
 ("plugin: notify with the setting off", "obsidian-plugin/src/notify.js",
  'if (this.settings && this.settings.notify) {', 'if (this.settings) {'),
 ("plugin: notify while the tab is being viewed", "obsidian-plugin/src/notify.js",
  'if (focused && tab && this.activeLeaf() === tab.leaf) return;', ''),
 ("plugin: server silent — counter drops to zero", "obsidian-plugin/src/notify.js",
  'if (!data || !Array.isArray(data.sessions)) return;', 'if (!data) data = { sessions: [] };'),
 ("plugin: title without a counter", "obsidian-plugin/src/notify.js",
  'return count ? `Session Atlas (${count})` : "Session Atlas";', 'return "Session Atlas";'),
 ("dialog: text-input options shown as buttons", "obsidian-plugin/src/dialog.js",
  'const choices = options.filter((o) => !NEEDS_TEXT.test(o.text));', 'const choices = options;'),
 ("dialog: several questions answered with a digit", "obsidian-plugin/src/dialog.js",
  'answerable: !multi && choices.length > 0,', 'answerable: choices.length > 0,'),
 ("dialog: a wrapped permission label is not joined", "obsidian-plugin/src/dialog.js",
  'if (kind === "permission") {\n    options.forEach', 'if (false) {\n    options.forEach'),
 ("dialog: footer is optional", "obsidian-plugin/src/dialog.js",
  'if (footer < 0) return null;', 'if (footer < 0) footer = rows.length;'),
 ("plugin: answer without matching the label on screen", "obsidian-plugin/src/input.js",
  'if (!sameOption(dialog, data.option, data.text)) {', 'if (!dialog) {'),
 ("plugin: dialog answer with Enter", "obsidian-plugin/src/input.js",
  'stdin.write(String(data.option));', 'stdin.write(String(data.option) + "\\r");'),
 ("plugin: answer when the dialog is already closed", "obsidian-plugin/src/input.js",
  'if (state.status !== "waiting") return reply(false, this.t("input.dialogClosed"));', ''),
 ("plugin: «Stop» while idle", "obsidian-plugin/src/input.js",
  'if (!STOPPABLE.has(state.status)) return reply(false, this.t("input.notRunning"));', ''),
 ("plugin: «Stop» with two Esc", "obsidian-plugin/src/input.js",
  'stdin.write(ESC);', 'stdin.write(ESC + ESC);'),
 ("plugin: «Stop» without verifying the session", "obsidian-plugin/src/input.js",
  'const { error, tab, state } = await this.checkTarget(data);\n    if (error) return reply(false, error);\n    if (!STOPPABLE',
  'const { error, tab, state } = await this.checkTarget(Object.assign({}, data, { sessionId: '
  '(this.readSessionState(data.claudePid) || {}).sessionId }));\n    if (error) return reply(false, error);\n    if (!STOPPABLE'),
 ("page: an interrupted prompt «awaits a reply»", "web/js/logic.js",
  'interrupted: t(s.interrupted_at) >= t(s.prompt_at) }', 'interrupted: false }'),
 ("page: delivery without a queue", "web/js/logic.js",
  'if (head && (s.queued || []).some(q => (q.text || "").trim().startsWith(head))) return "queued";', ''),
 ("page: delivery does not clear", "web/js/logic.js",
  'if (head && now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS) return "lost";', ''),
 ("page: an image without text — «lost»", "web/js/logic.js",
  'if (head && now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS)', 'if (now - new Date(sent.at).getTime() > DELIVERY_WAIT_MS)'),
 ("plugin: macOS notification even with the window in front", "obsidian-plugin/src/notify.js",
  'if (!focused && this.settings && this.settings.systemNotify) this.systemNotify(s, go);',
  'if (this.settings && this.settings.systemNotify) this.systemNotify(s, go);'),
 ("plugin: macOS notification without the setting", "obsidian-plugin/src/notify.js",
  'if (!focused && this.settings && this.settings.systemNotify)', 'if (!focused)'),
 ("plugin: silent when the tab is active in a minimized window", "obsidian-plugin/src/notify.js",
  'if (focused && tab && this.activeLeaf() === tab.leaf) return;',
  'if (tab && this.activeLeaf() === tab.leaf) return;'),
 ("plugin: clicking the macOS notification does not open the tab", "obsidian-plugin/src/notify.js",
  '      raiseWindow();\n      go();', '      raiseWindow();'),
 ("page: suggestions after a space too", "web/js/logic.js",
  'const m = /^\\/([^\\s]*)$/.exec(text || "");', 'const m = /^\\/(\\S*)/.exec(text || "");'),
 ("page: suggestions without prefix matches first", "web/js/logic.js",
  'return starts.concat(inside);', 'return inside.concat(starts);'),
 ("page: history does not restore the draft", "web/js/logic.js",
  'const next = Math.max(-1,', 'const next = Math.max(0,'),
 ("page: 80% context raises no alert", "web/js/logic.js", 'tone: pct >= 80 ? "warn"', 'tone: pct >= 95 ? "warn"'),
 ("page: stale limits are not marked", "web/js/logic.js",
  'const stale = l.age_seconds != null && l.age_seconds > 6 * 3600;', 'const stale = false;'),
 ("page: order by message recency", "web/js/logic.js",
  'const started = s => new Date(s.process_started_at || s.started_at || 0).getTime();',
  'const started = s => new Date(s.last_message_at || 0).getTime();'),
 ("page: pinned ones not first", "web/js/logic.js",
  'if (pa !== pb) return (pa < 0 ? 1e9 : pa) - (pb < 0 ? 1e9 : pb);', ''),
 ("page: a hidden one does not return on a new message", "web/js/logic.js",
  '&& hid[s.session_id] === (s.last_message_at || "");', ';'),
 ("page: hidden entries accumulate", "web/js/logic.js",
  'return !s || hid[id] !== (s.last_message_at || "");', 'return false;'),
 ("plugin: live sessions also offered for restore", "obsidian-plugin/src/restore.js",
  '.filter((x) => !alive.has(x.session_id) && fresh(x));', '.filter((x) => fresh(x));'),
 ("plugin: old sessions also offered for restore", "obsidian-plugin/src/restore.js",
  'now - (x.at || 0) < RESTORE_MAX_AGE_MS : true;', 'true : true;'),
 ("plugin: remember sessions not from tabs too", "obsidian-plugin/src/restore.js",
  'if (await this.tabForSession(s)) {', 'if (true) {'),
 ("plugin: restore list to any origin", "obsidian-plugin/src/restore.js",
  '    }, this.atlasOrigin());', '    }, "*");'),
 ("plugin: «not needed» does not forget", "obsidian-plugin/src/restore.js",
  'this.restorable = drop ? (this.restorable || []).filter((x) => !drop.has(x.session_id)) : [];',
  'this.restorable = this.restorable || [];'),
 ("plugin: «Restore» twice — two launches", "obsidian-plugin/src/main.js",
  'if (this.raisingServer) return;', ''),
 ("plugin: «Restore» answers any origin", "obsidian-plugin/src/main.js",
  'type: "server-ensured", ok, reason }, this.atlasOrigin());', 'type: "server-ensured", ok, reason }, "*");'),
 ("page: estimate without ≈", "web/js/logic.js", 'return (estimate ? "≈" : "") + "$"', 'return "$"'),
 ("page: 1M window shown as 1000k", "web/js/logic.js",
  'return n >= 1e6 ? (n / 1e6)', 'return n >= 1e9 ? (n / 1e6)'),
 ("plugin: command response is not read", "obsidian-plugin/src/input.js",
  'if (command && SCREEN_COMMANDS.has(command[1]) && !images.length) {', 'if (false) {'),
 ("plugin: screen is read after any message", "obsidian-plugin/src/input.js",
  'if (command && SCREEN_COMMANDS.has(command[1]) && !images.length) {', 'if (!images.length) {'),
 ("dialog: panel not recognized", "obsidian-plugin/src/dialog.js",
  'if (PANEL_RULE.test(rows[i])) { panel = i; break; }', ''),
 ("dialog: command echo stays in the reply", "obsidian-plugin/src/dialog.js",
  '        body = body.slice(i + 1);\n        break;', '        break;'),
 ("dialog: ⎿ marker in the reply", "obsidian-plugin/src/dialog.js",
  'body.map((l) => l.replace(/^(\\s*)⎿ {1,2}/, "$1"))', 'body'),
 ("plugin: panel is not shown instead of «not parsed»", "obsidian-plugin/src/input.js",
  '    if (panel && panel.panel) {', '    if (false) {'),
 ("page: 11 inflected like 1", "web/js/logic.js",
  'if (m10 === 1 && m100 !== 11) return one;', 'if (m10 === 1) return one;'),
]



# Node test files that cover each plugin/page source; the first matching prefix wins.
JS_TESTS = [
    ("obsidian-plugin/src/pty.js", ["tests/js/pty.test.mjs"]),
    ("obsidian-plugin/src/config-form.js", ["tests/js/config-form.test.mjs"]),
    ("obsidian-plugin/src/statusline.js", ["tests/js/statusline.test.mjs"]),
    ("obsidian-plugin/src/runtime.js", ["tests/js/bundle.test.mjs", "tests/js/plugin.test.mjs"]),
    ("obsidian-plugin/src/", ["tests/js/plugin.test.mjs"]),
    ("obsidian-plugin/styles.css", ["tests/js/plugin.test.mjs"]),
    ("web/js/", ["tests/js/page.test.mjs", "tests/js/i18n.test.mjs"]),
]


def js_tests(path):
    for prefix, files in JS_TESTS:
        if path.startswith(prefix):
            return files
    raise SystemExit(f"no Node tests mapped for {path}")


def drop_pycache():
    for folder in ("atlas/__pycache__", "tests/__pycache__", "tools/__pycache__"):
        shutil.rmtree(folder, ignore_errors=True)


# A mutation can make a test wait forever (a process that never exits); that counts as caught.
RUN_LIMIT_S = 600


def _run(cmd):
    # Own process group: on timeout the whole tree goes, or its open pipes would block the wait.
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
    try:
        return proc.wait(timeout=RUN_LIMIT_S)
    except subprocess.TimeoutExpired:
        os.killpg(proc.pid, signal.SIGKILL)
        proc.wait()
        return 124


def run_python():
    return _run([sys.executable, "-m", "pytest", "-q", "-x", "-p", "no:cacheprovider"])


def run_node(path):
    return _run(["node", "--test", "--test-force-exit", "--test-timeout=120000", *js_tests(path)])


def mutate(path, old, new, run):
    """Applies one mutation, runs the tests, restores the file byte for byte; True = a test failed."""
    with open(path, "rb") as fh:
        original = fh.read()
    backup = path + ".bak"
    shutil.copy2(path, backup)
    try:
        with open(path, "wb") as fh:
            fh.write(original.decode("utf-8").replace(old, new, 1).encode("utf-8"))
        drop_pycache()
        return run() != 0
    finally:
        with open(path, "wb") as fh:
            fh.write(original)
        os.remove(backup)
        # The restored file must not keep the mutated file's mtime: if it matches the one recorded in .pyc,
        # Python treats the cache as valid and keeps running mutated bytecode after the rollback.
        os.utime(path, None)
        drop_pycache()


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only verify that every snippet applies")
    parser.add_argument("--only", metavar="SUBSTR", help="run only mutations whose name contains SUBSTR")
    kind = parser.add_mutually_exclusive_group()
    kind.add_argument("--python", action="store_true", help="only the Python mutations")
    kind.add_argument("--js", action="store_true", help="only the JavaScript mutations")
    parser.add_argument("--shard", metavar="I/N", help="run only every N-th mutation starting at I (1-based)")
    args = parser.parse_args()
    os.chdir(ROOT)

    jobs = ([] if args.js else [(m, False) for m in MUT]) + ([] if args.python else [(m, True) for m in JS_MUT])
    if args.only:
        jobs = [job for job in jobs if args.only in job[0][0]]
    if args.shard:
        index, count = (int(x) for x in args.shard.split("/"))
        jobs = jobs[index - 1::count]
    caught = missed = not_applied = 0
    for (name, path, old, new), is_js in jobs:
        with open(path, encoding="utf-8") as fh:
            if old not in fh.read():
                not_applied += 1
                print(f"  {'NOT APPLIED':12} {name}  [{path}]", flush=True)
                continue
        if args.check:
            continue
        ok = mutate(path, old, new, functools.partial(run_node, path) if is_js else run_python)
        caught += ok
        missed += not ok
        print(f"  {'caught' if ok else 'MISSED':12} {name}", flush=True)

    if args.check:
        print(f"\n{len(jobs) - not_applied}/{len(jobs)} mutations apply")
    else:
        print(f"\n{caught}/{len(jobs)} mutations caught, {missed} missed, {not_applied} not applied")
    return 1 if missed or not_applied else 0


if __name__ == "__main__":
    sys.exit(main())
